### ISSUE TITLE
Go find references javascript error: Unknown document

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1067]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/repos.go#L92:17&tab=references

```
ResponseError: unknown document
    at handleResponse (webpack-internal:///../shared/src/api/protocol/jsonrpc2/connection.ts:348:36)
    at processMessageQueue (webpack-internal:///../shared/src/api/protocol/jsonrpc2/connection.ts:182:9)
    at setImmediateCompat (webpack-internal:///../shared/src/api/protocol/jsonrpc2/connection.ts:165:7)
    at module.exports (webpack-internal:///../node_modules/core-js/modules/_invoke.js:7:19)
    at queue.(anonymous function) (webpack-internal:///../node_modules/core-js/modules/_task.js:45:7)
    at Number.run (webpack-internal:///../node_modules/core-js/modules/_task.js:27:5)
    at MessagePort.listener (webpack-internal:///../node_modules/core-js/modules/_task.js:32:7)
```

![image](https://user-images.githubusercontent.com/754768/48741010-87646100-ec0e-11e8-9c4a-c49a084374db.png)

**Comment by nicksnyder** [comment]
This was resolved by disabling sqs/sourcegraph-python for the Sourcegraph org on sourcegraph.com

**Comment by nicksnyder** [comment]
unable to reproduce
