### ISSUE TITLE
Replace forked ts-graphql-plugin-based type query generator

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#12177]
For integration tests, we currently use a mostly-copy-pasted adapted version of `ts-graphql-plugin`: https://github.com/sourcegraph/sourcegraph/blob/master/shared/dev/gql2ts-transformer.ts

The generator has multiple bugs in the typings it generates (see casts in integration tests), but lacks comments and is hard for us to maintain. It would be better to rely on a better-working open source tool, e.g. [GraphQL code generator](https://graphql-code-generator.com/) which could be combined with [graphql-tag-pluck](https://www.graphql-tools.com/docs/graphql-tag-pluck/) to extract the types out of our TypeScript code.

The current bugs also likely make it not useable for the general use case of typing queries.

**Comment by twop** [comment]
WIP research results

The good:
GraphQL code generator can potentially do 90% of what we need today for integration tests specifically
It can also replace our current codegen gql2ts because
It has watch mode
writing our own plugin to generate a big interface for gql operations seems doable
It has graphql-tag-pluck built in

The not so good:
graphql-tag-pluck has several issues with our current code base and I don’t know the scope of the problems yet. One of them: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@870221e07c86de5e67d3900a804ce6547b595fd3/-/blob/web/src/search/backend.tsx#L16:7 
it requires unique fragment names.
I’m not sure yet if it^ implies that we cannot reuse fragments across queries.

Summary so far:
It seems like the right tool for the job
I will continue to invest time to make it work

**Comment by felixfbecker** [comment]
> it requires unique fragment names.

This doesn't seem like a problem - just like unique query names, unique fragment names have other benefits, e.g. you can easily grep/sourcegraph for them to find them in the codebase.

> graphql-tag-pluck has several issues with our current code base and I don’t know the scope of the problems yet. One of them: sourcegraph.com/github.com/sourcegraph/sourcegraph@870221e07c86de5e67d3900a804ce6547b595fd3/-/blob/web/src/search/backend.tsx#L16:7

The issue linked in that comment is https://github.com/graph-gophers/graphql-go/issues/241. @sourcegraph/cloud do you have thoughts on this?
cc @eseliger who wrote that comment.

> I’m not sure yet if it^ implies that we cannot reuse fragments across queries.

Intuitively I don't see why that would be the case, but maybe I'm missing something.

**Comment by twop** [comment]
Good news on Fragments reuse

this code works:
```ts
import gql from 'graphql-tag';

const SharedUser = gql`
  fragment SharedUser on User {
    id
    username
  }
`;

export const QueryA = gql`
  query findUserA($userId: ID!) {
    user(id: $userId) {
      ...SharedUser
    }
    ${SharedUser}
  }
`;

const SharedUserDup = gql`
  fragment SharedUser on User {
    id
    username
  }
`;

export const QueryB = gql`
  query findUserB($userId: ID!) {
    user(id: $userId) {
      ...SharedUser
    }
    ${SharedUserDup}
  }
`;
```

But changing it too

```ts
const SharedUserDup = gql`
  fragment SharedUser on User {
    id
    username
    someOtherField <-----
  }
`;
```

will result in an error. 

It seems that the tooling checks structural equality vs picking just declarations from code, which is awesome!

So as long as unique names represent different structures we are free to organize code however we want :)

**Comment by twop** [comment]
Upd:
1. custom `gql` tag works with no extra configuration (our usecase)
2. Confirmed that [string concatenation]( https://github.com/sourcegraph/sourcegraph/blob/master/shared/dev/gql2ts-transformer.ts) breaks the tooling 

```ts
// Not using "graphql-tag"
import { gql } from './gql';

const SharedUser = `
    id
    username
`;
// const SharedUser = gql`
//   fragment SharedUser on User {
//     id
//     username
//   }
// `;

export const QueryB = gql`
  query findUserB($userId: ID!) {
      user(id: $userId){
        ${SharedUser}
      }
  }
`;
```

Error output
```
    GraphQLError: Syntax Error: Expected Name, found "}".
        at syntaxError (/Users/twop.sk/work/gql-stub/node_modules/graphql/error/syntaxError.js:15:10)
        at Parser.expectToken (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:1423:40)
        at Parser.parseName (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:92:22)
        at Parser.parseField (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:289:28)
        at Parser.parseSelection (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:278:81)
        at Parser.many (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:1537:26)
        at Parser.parseSelectionSet (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:265:24)
        at Parser.parseField (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:306:68)
        at Parser.parseSelection (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:278:81)
        at Parser.many (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:1537:26)
        at Parser.parseSelectionSet (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:265:24)
        at Parser.parseOperationDefinition (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:193:26)
        at Parser.parseDefinition (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:131:23)
        at Parser.many (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:1537:26)
        at Parser.parseDocument (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:109:25)
        at Object.parse (/Users/twop.sk/work/gql-stub/node_modules/graphql/language/parser.js:36:17)
```

So I think it might make sense just to copypaste the shared fragment with a comment "copied because of X", not ideal but probably not as critical.

**Comment by felixfbecker** [comment]
As I understand it, copy-pasting the fragment wouldn't solve this panic issue: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@870221e07c86de5e67d3900a804ce6547b595fd3/-/blob/web/src/search/backend.tsx#L16:7 (or are we talking about another issue?)
If there is only one case where we're not using a proper fragment because of a backend bug, we could also just not use the `gql` tag there.

**Comment by twop** [comment]
copy pasting === inlining, which is our workaround today. We cannot use fragments but a normal query is OK.
@eseliger is that true?

**Comment by eseliger** [comment]
Yes a normal query should work :) not sure why I didn’t take that tradeoff🤔

**Comment by twop** [comment]
Ok I made a plugin that generates our interface thing.
The best part that this is pretty much it:
```ts
import { Types, PluginFunction } from '@graphql-codegen/plugin-helpers';
import { GraphQLSchema, concatAST, visit } from 'graphql';
import { capitalCase } from 'change-case';

type Operation = {
  type: 'query' | 'mutation' | 'subscription';
  name: string;
};

export const plugin: PluginFunction<{}, string> = (
  schema: GraphQLSchema,
  documents: Types.DocumentFile[],
  config: {}
) => {
  // const identifierName = config.identifierName || 'namedOperations';
  const allAst = concatAST(documents.map(v => v.document));
  const allOperations: Operation[] = [];

  visit(allAst, {
    enter: {
      OperationDefinition: node => {
        if (node.name?.value) {
          allOperations.push({ type: node.operation, name: node.name.value });
        }
      },
    },
  });

  const interfaceFields = allOperations.map(({ type, name }) => {
    const fullname = `${capitalCase(name, { delimiter: '' })}${capitalCase(
      type
    )}`;
    return `${name}: (variables: ${fullname}Variables) => ${fullname};`;
  });

  if (interfaceFields.length === 0) {
    // eslint-disable-next-line no-console
    console.warn(
      `Plugin "named-operations-object" has an empty output, since there are no valid operations!`
    );

    return '';
  }

  return `export interface AllOperations {
${interfaceFields.join('\n')}
}`;
};
```
It outputs this code:
```ts
export interface AllOperations {
findUserA: (variables: FindUserAQueryVariables) => FindUserAQuery;
findUserC: (variables: FindUserCQueryVariables) => FindUserCQuery;
}
```

So yeah, super happy with it so far.

**Comment by felixfbecker** [comment]
Awesome! When's the PR coming? 🙂

**Comment by twop** [comment]
today, hopefully
