### ISSUE TITLE
 Error getting locations: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1243]
Returning an Rx Observable from a references provider compiles fine, but fails at runtime with:

![image](https://user-images.githubusercontent.com/10532611/49530801-3ebcd100-f8b9-11e8-9881-d9b7c035307c.png)

I searched for the error message and parts of it but couldn't find it anywhere in the codebase.

**Comment by felixfbecker** [comment]
Actually just realised this is probably not an error coming from Sourcegraph.

**Comment by felixfbecker** [comment]
Actually, this seems to be a bug inside Sourcegraph somewhere. This is the stack trace:

```
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at f (https://sourcegraph.com/.assets/db8ce510d929f043570c.worker.js:1:24092)
    at b (https://sourcegraph.com/.assets/db8ce510d929f043570c.worker.js:1:20004)
    at t.then.t (https://sourcegraph.com/.assets/db8ce510d929f043570c.worker.js:1:12658)
```

**Comment by felixfbecker** [comment]
It seems like at some point in the app `Symbol.observable` is available as a symbol but at a different point it is not so the shim `"@@observable"` is used. This causes the two Observables to not interop.

**Comment by felixfbecker** [comment]
https://github.com/sindresorhus/is/issues/72
