### ISSUE TITLE
Type error in search code on `frontend`

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#12806]
Just saw this stack trace on one of the frontend pods, which died:

```
t=2020-08-06T21:33:47+0000 lvl=dbug msg="TRACE HTTP" method=POST url=/.api/graphql?DefinitionAndHover routename="graphql: DefinitionAndHover" trace="#tracing_not_enabled_for_this_request_add_?trace=1_to_url_to_enable" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" user=10218 xForwardedFor=108.162.219.47 written=57 code=200 duration=28.796113ms graphql_error=false
t=2020-08-06T21:33:47+0000 lvl=dbug msg="TRACE HTTP" method=HEAD url=/github.com/golang/text@HEAD/-/raw routename=raw trace="#tracing_not_enabled_for_this_request_add_?trace=1_to_url_to_enable" userAgent=Go-http-client/2.0 user=0 xForwardedFor=162.158.78.167 written=0 code=200 duration=7.158321ms graphql_error=false
t=2020-08-06T21:33:47+0000 lvl=info msg="serving GraphQL request" name=unknown user=danzh2010 source=browser
logging complete query for unnamed GraphQL request above name=unknown user=danzh2010 source=browser:
QUERY
-----

            
        fragment SearchResults on Search {
            results {
                __typename
                results {
                    ... on FileMatch {
                        __typename
                        file {
                            path
                            commit {
                                oid
                            }
                        }
                        repository {
                            name
                        }
                        symbols {
                            name
                            kind
                            location {
                                resource {
                                    path
                                }
                                range {
                                    start {
                                        line
                                        character
                                    }
                                    end {
                                        line
                                        character
                                    }
                                }
                            }
                        }
                        lineMatches {
                            lineNumber
                            offsetAndLengths
                        }
                    }
                }
            }
        }
    
            
        fragment FileLocal on Search {
            results {
                __typename
                results {
                    ... on FileMatch {
                        symbols {
                            fileLocal
                        }
                    }
                }
            }
        }
    
            query CodeIntelSearch($query: String!) {
                search(query: $query) {
                    ...SearchResults
                    ...FileLocal
                }
            }
        

VARIABLES
---------
map[query:^factory$ type:symbol patternType:regexp case:yes file:\.(c|cc|cpp|cxx|hh|h|hpp|ino|m)$ repo:^github.com/envoyproxy/envoy$@432ee807210907d769c10de7af2e775d23502f36]

t=2020-08-06T21:33:47+0000 lvl=dbug msg="TRACE HTTP" method=POST url=/.api/updates routename=updatecheck trace="#tracing_not_enabled_for_this_request_add_?trace=1_to_url_to_enable" userAgent=Go-http-client/2.0 user=0 xForwardedFor=172.69.35.74 written=0 code=204 duration=37.295058ms graphql_error=false
t=2020-08-06T21:33:47+0000 lvl=dbug msg="TRACE HTTP" method=POST url=/.api/graphql routename="graphql: unknown" trace="#tracing_not_enabled_for_this_request_add_?trace=1_to_url_to_enable" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36" user=10218 xForwardedFor=108.162.219.47 written=597 code=200 duration=112.725392ms graphql_error=false
t=2020-08-06T21:33:48+0000 lvl=dbug msg="serving GraphQL request" name=Extensions user= source=browser
panic: interface conversion: query.QueryInfo is *query.OrdinaryQuery, not *query.AndOrQuery

goroutine 783743 [running]:
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).getExactFilePatterns(0xc032dda320, 0xc04f985580)
	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_results.go:1928 +0x193
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).sortResults(0xc032dda320, 0x2c8b520, 0xc04f985580, 0x0, 0x0, 0x0)
	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_results.go:1919 +0x58
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).doResults(0xc032dda320, 0x2c8b5a0, 0xc008744060, 0x1b7d228, 0x4, 0x0, 0x0, 0x0)
	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_results.go:1844 +0xf26
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).Suggestions.func5(0x2c8b5a0, 0xc008744060, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_suggestions.go:276 +0x13a
github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).Suggestions.func6(0xc04f985540, 0x2c8b5e0, 0xc024f21710, 0xc004612db0, 0xc05f275380, 0xc032dda320, 0xc05f275340)
	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_suggestions.go:311 +0xc5
created by github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).Suggestions
	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_suggestions.go:307 +0x572
```

@rvantonder is this up your alley? Seems like it's associated with the user query parsing code.

**Comment by rvantonder** [comment]
> panic: interface conversion: query.QueryInfo is *query.OrdinaryQuery, not *query.AndOrQuery

Yeah this is something I can looking into. Looks like an incorrect type assertion added recently.

**Comment by rvantonder** [comment]
@beyang https://github.com/sourcegraph/sourcegraph/pull/12807

**Comment by rvantonder** [comment]
@beyang fix should be live after I merged https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/3151. If not, bounce pods?

**Comment by rvantonder** [comment]
(and thanks for flagging)
