### ISSUE TITLE
campaigns: GraphQL crash when resolving diff

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#13498]
<img width="973" alt="Screen Shot 2020-08-31 at 6 06 12 PM" src="https://user-images.githubusercontent.com/103087/91777217-dea1ae80-ebb4-11ea-9f89-bb2a0b81cf6f.png">

```
18:06:00                          frontend | graphql: panic occurred: runtime error: index out of range [13] with length 13
18:06:00                          frontend | goroutine 73656 [running]:
18:06:00                          frontend | github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0x3ccc728, 0x2d47520, 0xc0015f58f0, 0x2723740, 0xc001718c20)
18:06:00                          frontend | 	/Users/efritz/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20200724075322-e542e8956484/log/log.go:21 +0x6f
18:06:00                          frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1(0xc0006c53b0, 0x2d47520, 0xc0015f58f0, 0xc001a1de90, 0xc001d90060)
18:06:00                          frontend | 	/Users/efritz/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20200724075322-e542e8956484/internal/exec/exec.go:179 +0x8d
18:06:00                          frontend | panic(0x2723740, 0xc001718c20)
18:06:00                          frontend | 	/usr/local/Cellar/go/1.15/libexec/src/runtime/panic.go:969 +0x175
18:06:00                          frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*DiffHunk).Highlight(0xc001d1fec0, 0x2d47520, 0xc0015f58f0, 0xc0003efbdc, 0x0, 0x0, 0x0)
18:06:00                          frontend | 	/Users/efritz/dev/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/repository_comparison.go:565 +0x559
18:06:00                          frontend | reflect.Value.call(0x267b0c0, 0xc0018d8220, 0x693, 0x284e1a7, 0x4, 0xc003de6150, 0x2, 0x2, 0x6, 0xc002517cf8, ...)
18:06:00                          frontend | 	/usr/local/Cellar/go/1.15/libexec/src/reflect/value.go:475 +0x8c7
18:06:00                          frontend | reflect.Value.Call(0x267b0c0, 0xc0018d8220, 0x693, 0xc003de6150, 0x2, 0x2, 0x693, 0x2, 0xc0138f81e0)
18:06:00                          frontend | 	/usr/local/Cellar/go/1.15/libexec/src/reflect/value.go:336 +0xb9
18:06:00                          frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2(0xc0006c53b0, 0x2d47520, 0xc0015f58f0, 0xc001d90060, 0xc003dd1640, 0xc001a1dee0, 0x2d47520, 0xc0015f58f0, 0x0)
18:06:00                          frontend | 	/Users/efritz/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20200724075322-e542e8956484/internal/exec/exec.go:203 +0x508
18:06:00                          frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x2d47520, 0xc0015f58f0, 0xc0006c53b0, 0xc0002f82a0, 0xc003dd1640, 0xc001d90060, 0x1)
18:06:00                          frontend | 	/Users/efritz/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20200724075322-e542e8956484/internal/exec/exec.go:223 +0x1b5
18:06:00                          frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections.func1(0xc00126b080, 0xc0006c53b0, 0x2d47520, 0xc0015f58f0, 0xc0002f82a0, 0xc001d1ff00, 0xc003dd1640)
18:06:00                          frontend | 	/Users/efritz/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20200724075322-e542e8956484/internal/exec/exec.go:83 +0x18d
18:06:00                          frontend | created by github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections
18:06:00                          frontend | 	/Users/efritz/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20200724075322-e542e8956484/internal/exec/exec.go:79 +0x625
18:06:00                          frontend | context: context.Background.WithValue(type *http.contextKey, val <not Stringer>).WithValue(type *http.contextKey, val [::1]:3082).WithCancel.WithCancel.WithValue(type ot.key, val <not Stringer>).WithValue(type opentracing.contextKey, val 18aea93f29fefc20:18aea93f29fefc20:0000000000000000:1).WithValue(type opentracing.contextKey, val 18aea93f29fefc20:4393498dfce3291d:18aea93f29fefc20:1).WithValue(type opentracing.contextKey, val 18aea93f29fefc20:4393498dfce3291d:18aea93f29fefc20:1).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val unknown).WithValue(type sessions.contextKey, val <not Stringer>).WithValue(type actor.key, val Actor UID 1, internal false).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type trace.key, val ChangesetSpecFileDiffs).WithValue(type trace.key, val <not Stringer>).WithValue(type opentracing.contextKey, val 18aea93f29fefc20:4b0c4b01da26d903:4393498dfce3291d:1)
```

**Comment by chrispine** [comment]
Adding to the 3.20 milestone (but unassigned) in case it's an easy fix we can squeeze in.
