### ISSUE TITLE
GitLab source panics when closing changesets

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13790]
I'm not sure whether this is related to https://github.com/sourcegraph/sourcegraph/issues/13648 or not, but when I closed a campaign with a GitLab changeset in it the repo-updater process crashed:

```
15:36:45  repo-updater | INFO Reconciler processing changeset, changeset: 191, action: close
15:36:45  repo-updater | panic: runtime error: invalid memory address or nil pointer dereference
15:36:45  repo-updater | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c3c0f2]
15:36:45  repo-updater | goroutine 3565 [running]:
15:36:45  repo-updater | github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos.(*GitLabSource).CloseChangeset(0xc00193e700, 0x32b44e0, 0xc0012a1980, 0xc0007c14f0, 0x0, 0x0)
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/cmd/repo-updater/repos/gitlab.go:347 +0x182
15:36:45  repo-updater | github.com/sourcegraph/sourcegraph/enterprise/internal/campaigns.(*reconciler).closeChangeset(0xc0015740c0, 0x32b44e0, 0xc0012a1980, 0xc001cda760, 0xc0015823c0, 0x0, 0x0)
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/enterprise/internal/campaigns/reconciler.go:285 +0x3ba
15:36:45  repo-updater | github.com/sourcegraph/sourcegraph/enterprise/internal/campaigns.(*reconciler).process(0xc0015740c0, 0x32b44e0, 0xc0012a1980, 0xc001cda760, 0xc0015823c0, 0x0, 0x0)
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/enterprise/internal/campaigns/reconciler.go:81 +0x635
15:36:45  repo-updater | github.com/sourcegraph/sourcegraph/enterprise/internal/campaigns.(*reconciler).HandlerFunc.func1(0x32b44e0, 0xc0012a1980, 0x32beca0, 0xc001c1d600, 0x328d000, 0xc0015823c0, 0x0, 0x0)
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/enterprise/internal/campaigns/reconciler.go:44 +0xff
15:36:45  repo-updater | github.com/sourcegraph/sourcegraph/internal/workerutil/dbworker.HandlerFunc.Handle(0xc00068f610, 0x32b44e0, 0xc0012a1980, 0x32beca0, 0xc001c1d600, 0x328d000, 0xc0015823c0, 0x0, 0x0)
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/internal/workerutil/dbworker/handler.go:31 +0x7a
15:36:45  repo-updater | github.com/sourcegraph/sourcegraph/internal/workerutil/dbworker.(*handlerShim).Handle(0xc00068f7f0, 0x32b44e0, 0xc0012a1980, 0x32b49e0, 0xc001bbb9a0, 0x328d000, 0xc0015823c0, 0x0, 0x0)
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/internal/workerutil/dbworker/handler_shim.go:25 +0xb8
15:36:45  repo-updater | github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).handle(0xc00034d7a0, 0x32b49e0, 0xc001bbb9a0, 0x328d000, 0xc0015823c0, 0xc001bbb350, 0xc0020b4ed8)
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/internal/workerutil/worker.go:190 +0x2b5
15:36:45  repo-updater | github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).dequeueAndHandle.func2(0xc00034d7a0, 0x328d000, 0xc0015823c0, 0x32b49e0, 0xc001bbb9a0)
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/internal/workerutil/worker.go:164 +0xd3
15:36:45  repo-updater | created by github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).dequeueAndHandle
15:36:45  repo-updater |    /Users/thorstenball/work/sourcegraph/internal/workerutil/worker.go:154 +0x821
15:36:45  repo-updater | Terminating repo-updater
```

cc @LawnGnome @chrispine

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/13795
