### ISSUE TITLE
Could not find item in `auth.providers` with config ID "okta-saml" and type "saml"

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1408]
Upon running `enterprise/dev/start.sh` (with the latest dev-private master checked out), I see:

```
17:33:04               frontend | t=2018-12-13T17:33:04-0800 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe."
17:33:04               frontend | panic: conf: problems with default configuration for "DevAndTesting":
17:33:04               frontend |   Could not find item in `auth.providers` with config ID "okta-saml" and type "saml"
17:33:04               frontend | goroutine 1 [running]:
17:33:04               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.mustValidate(0x1508f22, 0xd, 0x14f8bc4, 0x2, 0x155e0cd, 0x51, 0x0, 0x0, 0x0, 0x0, ...)
17:33:04               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/pkg/conf/validate.go:171 +0x2a6
17:33:04               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.MustValidateDefaults()
17:33:04               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/pkg/conf/validate.go:159 +0x78
17:33:04               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.Main(0x0, 0x0)
17:33:04               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/serve_cmd.go:85 +0x115
17:33:04               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/shared.Main()
17:33:04               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/cmd/frontend/shared/frontend.go:22 +0x2d
17:33:04               frontend | main.main()
17:33:04               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/main.go:39 +0x6c
17:33:04               frontend | Terminating frontend
```

@nicksnyder 	Related to this commit?

```
commit cab669b4d08a88383c48cafca1c906c2363f6b6a
Author: Nick Snyder <nickdsnyder@gmail.com>
Date:   Thu Dec 13 15:22:47 2018 -0800

    perform authz validation for external services (#1397)
```

**Comment by sqs** [comment]
This occurs because my `external_services` table has the following entry:

```
├─[ RECORD 6 ]─┼─────────────────────────────────────────────────────────────────────────────┤
│ id           │ 5                                                                           │
│ kind         │ GITLAB                                                                      │
│ display_name │ Migrated GitLab 1                                                           │
│ config       │ {                                                                          ↵│
│              │   "authorization": {                                                       ↵│
│              │     "authnProvider": {                                                     ↵│
│              │       "configID": "okta-saml",                                             ↵│
│              │       "gitlabProvider": "saml",                                            ↵│
│              │       "type": "saml"                                                       ↵│
│              │     }                                                                      ↵│
│              │   },                                                                       ↵│
│              │   "initialRepositoryEnablement": true,                                     ↵│
│              │   "projectQuery": [                                                        ↵│
│              │     "?"                                                                    ↵│
│              │   ],                                                                       ↵│
│              │   "repositoryPathPattern": "gitlab.sgdev.org/{pathWithNamespace}",         ↵│
│              │   "token": "Axusi-qWEEeNUBp-hv7s",                                         ↵│
│              │   "url": "https://gitlab.sgdev.org"                                        ↵│
│              │ }                                                                           │
│ created_at   │ 2018-12-13 07:24:32.692273+00                                               │
│ updated_at   │ 2018-12-13 07:24:32.692273+00                                               │
│ deleted_at   │ ¤                                                                           │
```

and the critical site config stored in the DB lacks the `"configID": "okta-saml"` property. I added it in https://github.com/sourcegraph/dev-private/commit/9b1871133adaf9f566d1b764e8f7bf6698db96e8, but I'm not able to add it to the mgmt console because enterprise/dev/start.sh terminates due to the error above, and the termination also takes down the mgmt console.

**Comment by sqs** [comment]
The temporary workaround is to run this against your dev PostgreSQL DB:

```
psql -c "delete from external_services where config like '%okta-saml%';"
```

**Comment by slimsag** [comment]
> I added it in sourcegraph/dev-private@9b18711, but I'm not able to add it to the mgmt console because enterprise/dev/start.sh terminates due to the error above, and the termination also takes down the mgmt console.

The file contents of `enterprise/dev/critical-config.json` are written to the DB on startup, but the fact that the `DevAndTesting` config is invalid does mean the panic occurs first and you can't fix it except manually. This change should have failed on CI due to the panic and shouldn't have gotten merged, I wonder how this happened? hmm

**Comment by nicksnyder** [comment]
This issue has re-appeared https://sourcegraph.slack.com/archives/C07KZF47K/p1546921091061800

**Comment by nicksnyder** [comment]
@beyang you should discuss this issue with @keegancsmith and @tsenart since they should take over ownership of auth.

**Comment by beyang** [comment]
please reopen if still an issue
