### ISSUE TITLE
run precise code intel tests in CI

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#14665]
Run the following test suite as part of CI in vagrant. These tests use the graphql API which should also be helpful for regression testing that we need to run as part of #12340

https://github.com/sourcegraph/sourcegraph/tree/main/internal/cmd/precise-code-intel-tester

**Comment by davejrt** [comment]
@efritz currently getting the following error when trying to upload:

```
dave@dave-dev:~/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester (dt/code_intel_tests)$ ./precise-code-intel-tester upload
⠸ Uploading etcd@1044a8
⠸ Uploading etcd@dfb0a4
⠸ Uploading etcd@fb77f9
⠸ Uploading tidb@2f9a48
⠸ Uploading tidb@43764a
⠸ Uploading tidb@b4f42a
⠸ Uploading titan@0ad2e7
⠸ Uploading titan@33623c
⠸ Uploading titan@aef232
⠸ Uploading zap@2aa9fa
⠸ Uploading zap@a6015e

[>                                                                        ] 0/11
panic: runtime error: index out of range [1] with length 0

goroutine 44 [running]:
main.upload(0xa05260, 0xc000216600, 0xc000242333, 0x4, 0xc0002421f8, 0x28, 0xc000214018, 0x0, 0x0, 0x0, ...)
        /home/dave/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester/upload.go:290 +0x8d1
main.makeTestUploadFunction.func1(0xa05260, 0xc000216600, 0x2, 0x0)
        /home/dave/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester/upload.go:231 +0xba
github.com/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester/util.runFunctions(0xa05260, 0xc000216600, 0xc00020e600, 0xb, 0x10, 0xc000200200, 0xc000256000, 0xc0002106c0)
        /home/dave/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester/util/parallel.go:86 +0x5f
github.com/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester/util.RunParallel.func1(0xc000204150, 0xc00020a2f0, 0xc00020e600, 0xb, 0x10, 0xc000200200, 0xc000256000, 0xc0002106c0)
        /home/dave/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester/util/parallel.go:53 +0xae
created by github.com/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester/util.RunParallel
        /home/dave/sourcegraph/sourcegraph/internal/cmd/precise-code-intel-tester/util/parallel.go:51 +0x279
```

**Comment by efritz** [comment]
@davejrt Ran into this as well with main. Pushed https://github.com/sourcegraph/sourcegraph/pull/15372 to address it.
