### ISSUE TITLE
qa: core test failing

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#15164]
Failing with the following error when running `yarn test:regression:core`

Full run [here](https://buildkite.com/sourcegraph/regression/builds/97#4fd825bc-4523-42c0-9f0d-2ba1080e3c2f)
```
    sourcegraph-qa-test:        2.2.2 User profile page:
    sourcegraph-qa-test:      Error: Could not find element with text "Update profile", options: {"action":"click"} Debug expressions: Array.from(document.querySelectorAll("*")).filter(e => e.innerText && e.innerText.match(/^Update profile$/))
    sourcegraph-qa-test: Array.from(document.querySelectorAll("*")).filter(e => e.innerText && e.innerText.match(/^Update profile\b/))
    sourcegraph-qa-test: Array.from(document.querySelectorAll("*")).filter(e => e.innerText && e.innerText.match(/^\s+Update profile$/))
    sourcegraph-qa-test: Array.from(document.querySelectorAll("*")).filter(e => e.innerText && e.innerText.match(/^\s+Update profile\b/))
    sourcegraph-qa-test:       at notFoundError (/sourcegraph/client/shared/src/testing/driver.ts:451:20)
    sourcegraph-qa-test:       at utils_1.retry.retries (/sourcegraph/client/shared/src/testing/driver.ts:465:23)
    sourcegraph-qa-test:       at runMicrotasks (<anonymous>)
    sourcegraph-qa-test:       at processTicksAndRejections (internal/process/task_queues.js:93:5)
    sourcegraph-qa-test:       at RetryOperation._fn (/sourcegraph/node_modules/p-retry/index.js:41:12)
```

**Comment by davejrt** [comment]
Fixed in #15538
