### ISSUE TITLE
qa: testing external-services fails in CI

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#15193]
The external services qa/regression tests fail in CI with the following error:

```
sourcegraph-qa-test: Test resource destroyed: Authentication provider "[TEST] GitHub.com permissions"
--
  | sourcegraph-qa-test: Test resource destroyed: External service "[TEST] Regression test: GitHub.com permissions"
  | sourcegraph-qa-test:
  | sourcegraph-qa-test: Visited routes:
  | sourcegraph-qa-test: /sign-in
  | sourcegraph-qa-test:   1 passing (55s)
  | sourcegraph-qa-test:   3 failing
  | sourcegraph-qa-test:   1) External services GUI
  | sourcegraph-qa-test:        External services: GitHub.com GUI and repositoryPathPattern:
  | sourcegraph-qa-test:      Error: RetryOperation timeout occurred
  | sourcegraph-qa-test:       at RetryOperation.retry (/sourcegraph/node_modules/retry/lib/retry_operation.js:49:26)
  | sourcegraph-qa-test:       at RetryOperation._fn (/sourcegraph/node_modules/p-retry/index.js:64:20)
  | sourcegraph-qa-test:
  | sourcegraph-qa-test:   2) External services API
  | sourcegraph-qa-test:        External services: GitLab:
  | sourcegraph-qa-test:      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/sourcegraph/client/web/src/regression/external-services.test.ts)
  | sourcegraph-qa-test:       at listOnTimeout (internal/timers.js:551:17)
  | sourcegraph-qa-test:       at processTimers (internal/timers.js:494:7)
  | sourcegraph-qa-test:
  | sourcegraph-qa-test:   3) External services permissions
  | sourcegraph-qa-test:        External services permissions: GitHub:
  | sourcegraph-qa-test:      Error: unsuccessful login
  | sourcegraph-qa-test:       at Object.login (src/regression/util/helpers.ts:183:19)
  | sourcegraph-qa-test:       at Context.<anonymous> (src/regression/external-services.test.ts:214:9)
  | sourcegraph-qa-test:
  | sourcegraph-qa-test:
  | sourcegraph-qa-test: error Command failed with exit code 3.
  | sourcegraph-qa-test:
  | sourcegraph-qa-test: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  | sourcegraph-qa-test: /sourcegraph
  | sourcegraph-qa-test: + popd
  | sourcegraph-qa-test: ++ pgrep ffmpeg
  | sourcegraph-qa-test: + PID=31805
```

Full log and artifacts here:
https://buildkite.com/sourcegraph/qa/builds/99#01c97518-b679-4dc3-be11-caeba2869ff9

**Comment by felixfbecker** [comment]
This is more the area of @sourcegraph/cloud, especially if it looks like GitHub auth is failing?

**Comment by unknwon** [comment]
Frankly, all e2e tests for external services are covered by current backend integration tests according to the [audit sheet](https://docs.google.com/spreadsheets/d/1lzKnWbI-zTlaqnHqzW5Ju1JF0dsov7s9RE6DyFeQmRk/edit#gid=0). So I'm gonna propose a PR to remove these tests.

**Comment by felixfbecker** [comment]
I'd love to do that, but we also need to think of the UI. There are no integration tests for that UI yet afaict.

**Comment by unknwon** [comment]
@felixfbecker If web team still want to have UI tests for external services, please file a separate issue for tracking.

**Comment by felixfbecker** [comment]
@unknwon I actually don't want to prescribe any testing for that UI, it's all up to you 🙂  Especially now that the cloud team has frontend resources those external services UIs should be fully owned by the cloud team, from their design to how they should be tested so that you feel confident they work correctly. They were built before by cloud team members so there should be no "hand off" needed here, the web team doesn't really have any context on the pages.
