### ISSUE TITLE
src-cli out of bounds panic

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#15719]
A customer got this panic:

```
panic: runtime error: index out of range [16] with length 16

goroutine 119 [running]:
github.com/sourcegraph/src-cli/internal/output.(*progressWithStatusBarsTTY).StatusBarResetf(0xc000508030, 0x10, 0xc000510080, 0x32, 0xc000209060, 0x13, 0x0, 0x0, 0x0)
    /home/runner/work/src-cli/src-cli/internal/output/progress_with_status_bars_tty.go:126 +0x157
main.(*campaignProgressPrinter).PrintStatuses(0xc000090140, 0xc0001ec000, 0x15, 0x15)
    /home/runner/work/src-cli/src-cli/cmd/src/campaign_progress_printer.go:161 +0xf57
github.com/sourcegraph/src-cli/internal/campaigns.(*Service).ExecuteCampaignSpec.func1(0xc00018c0f0, 0xc0001ec000, 0x15, 0x15, 0xc000118840)
    /home/runner/work/src-cli/src-cli/internal/campaigns/service.go:228 +0x72
created by github.com/sourcegraph/src-cli/internal/campaigns.(*Service).ExecuteCampaignSpec
    /home/runner/work/src-cli/src-cli/internal/campaigns/service.go:227 +0xd8c
```

**Comment by chrispine** [comment]
fixed by https://github.com/sourcegraph/src-cli/pull/378
