### ISSUE TITLE
qa: testing core failing in CI

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#15877]
Core tests fail CI: https://buildkite.com/sourcegraph/qa/builds/498#ad066fe1-9ea6-43ab-8b23-c65419cf730f/33-935

```
  1) Core functionality regression test suite
       2.2.2.1 User profile page with enableuserchanges=false:
     Error: Could not find element with text "Error: unable to change username because auth.enableUsernameChanges is false in site configuration", options: {} Debug expressions: Array.from(document.querySelectorAll("*")).filter(e => e.innerText && e.innerText.match(/^Error: unable to change username because auth\.enableUsernameChanges is false in site configuration$/))
Array.from(document.querySelectorAll("*")).filter(e => e.innerText && e.innerText.match(/^Error: unable to change username because auth\.enableUsernameChanges is false in site configuration\b/))
Array.from(document.querySelectorAll("*")).filter(e => e.innerText && e.innerText.match(/^\s+Error: unable to change username because auth\.enableUsernameChanges is false in site configuration$/))
Array.from(document.querySelectorAll("*")).filter(e => e.innerText && e.innerText.match(/^\s+Error: unable to change username because auth\.enableUsernameChanges is false in site configuration\b/))
      at notFoundError (/sourcegraph/client/shared/src/testing/driver.ts:451:20)
      at utils_1.retry.retries (/sourcegraph/client/shared/src/testing/driver.ts:465:23)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at RetryOperation._fn (/sourcegraph/node_modules/p-retry/index.js:41:12)

  2) Core functionality regression test suite
       2.2.3 User emails page:
     Error: RetryOperation timeout occurred
      at RetryOperation.retry (/sourcegraph/node_modules/retry/lib/retry_operation.js:49:26)
      at RetryOperation._fn (/sourcegraph/node_modules/p-retry/index.js:64:20)
```

**Comment by pecigonzalo** [comment]
@flying-robot that seems likely, I believe @davejrt also mentioned this worked before, and he had to adapt the tests for the previous release, so its likely we changed something again/back. Could you correct those tests? We dont really own these tests, we are just reporting on them.

**Comment by unknwon** [comment]
You can confidently remove these two tests as I believe they've been covered equivalently in backend integration/unit tests. 

Audit sheet: https://docs.google.com/spreadsheets/d/1lzKnWbI-zTlaqnHqzW5Ju1JF0dsov7s9RE6DyFeQmRk/edit#gid=0
