### ISSUE TITLE
Concurrent map writes panic in src-cli

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#16149]
I haven't dug deeper, but saw this while testing something. The dev stack was still starting up while I ran apply.

```
✅ Parsing campaign spec
✅ Resolving namespace
✅ Preparing container images  █████████████████████████████████████████████████
✅ Resolved repositories
⠋  Executing steps in 2 repositories
│
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 1 [running]:
runtime.throw(0x16b53e4, 0x15)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc0000fecf8 sp=0xc0000fecc8 pc=0x10373d2
runtime.mapassign_faststr(0x16042a0, 0xc00015e120, 0xc000496360, 0x25, 0x1b1a080)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/map_faststr.go:291 +0x3d8 fp=0xc0000fed60 sp=0xc0000fecf8 pc=0x10164b8
main.(*campaignProgressPrinter).PrintStatuses(0xc0000a0540, 0xc0003d60c0, 0x2, 0x2)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaign_progress_printer.go:90 +0x3f6 fp=0xc0000ff0e0 sp=0xc0000fed60 pc=0x1554c36
main.(*campaignProgressPrinter).PrintStatuses-fm(0xc0003d60c0, 0x2, 0x2)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaign_progress_printer.go:71 +0x48 fp=0xc0000ff110 sp=0xc0000ff0e0 pc=0x1592c88
github.com/sourcegraph/src-cli/internal/campaigns.(*Service).ExecuteCampaignSpec(0xc00000efa0, 0x1779720, 0xc00037a900, 0xc0004e0620, 0x2, 0x2, 0x1779920, 0xc000530000, 0xc000020070, 0xc0003d60b0, ...)
	/Users/erik/Code/sourcegraph/src-cli/internal/campaigns/service.go:248 +0xd09 fp=0xc0000ff2a0 sp=0xc0000ff110 pc=0x148b589
main.campaignsExecute(0x1779720, 0xc00037a900, 0xc00037a8c0, 0xc00000efa0, 0xc0001f6880, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaigns_common.go:238 +0x146f fp=0xc0000ffa08 sp=0xc0000ff2a0 pc=0x15592cf
main.init.2.func1(0x1779720, 0xc00037a900, 0xc00037a8c0, 0xc00000efa0, 0xc0001f6880, 0x0, 0x0)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaigns_apply.go:34 +0x92 fp=0xc0000ffc08 sp=0xc0000ffa08 pc=0x15751b2
main.init.2.func2(0xc0001b2030, 0x4, 0x4, 0x0, 0x0)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaigns_apply.go:79 +0x3d3 fp=0xc0000ffd48 sp=0xc0000ffc08 pc=0x1575bd3
main.commander.run(0xc000374280, 0x5, 0x8, 0xc0001aee40, 0x16b00f4, 0xd, 0x16d4bc1, 0x251, 0xc0001b2020, 0x5, ...)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/cmd.go:94 +0x3aa fp=0xc0000ffe00 sp=0xc0000ffd48 pc=0x155c86a
main.init.1.func1(0xc0001b2020, 0x5, 0x5, 0x5, 0x0)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaigns.go:32 +0x97 fp=0xc0000ffe68 sp=0xc0000ffe00 pc=0x1575037
main.commander.run(0xc00010a100, 0x11, 0x20, 0xc0001ae120, 0x16a8324, 0x3, 0x16d76a3, 0x46e, 0xc0001b2010, 0x6, ...)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/cmd.go:94 +0x3aa fp=0xc0000fff20 sp=0xc0000ffe68 pc=0x155c86a
main.main()
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/main.go:68 +0xf7 fp=0xc0000fff88 sp=0xc0000fff20 pc=0x1567277
runtime.main()
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/proc.go:204 +0x209 fp=0xc0000fffe0 sp=0xc0000fff88 pc=0x1039b89
runtime.goexit()
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000fffe8 sp=0xc0000fffe0 pc=0x106ca81

goroutine 34 [syscall]:
os/signal.signal_recv(0x1773b60)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/sigqueue.go:144 +0x9d
os/signal.loop()
	/usr/local/Cellar/go/1.15.4/libexec/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/Cellar/go/1.15.4/libexec/src/os/signal/signal.go:150 +0x45

goroutine 6 [select]:
main.contextCancelOnInterrupt.func1(0xc00037e240, 0xc0002d35e0, 0x1779720, 0xc00037a900)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaigns_common.go:431 +0xbd
created by main.contextCancelOnInterrupt
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaigns_common.go:430 +0xff

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x1fbaeb8, 0x72, 0x176e7a0)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000034318, 0x72, 0x176e700, 0x1a8d9f0, 0x0)
	/usr/local/Cellar/go/1.15.4/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.15.4/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000034300, 0xc0001d0900, 0x86c, 0x86c, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.4/libexec/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000034300, 0xc0001d0900, 0x86c, 0x86c, 0x203000, 0x12454fb, 0xc00030af60)
	/usr/local/Cellar/go/1.15.4/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0001ac398, 0xc0001d0900, 0x86c, 0x86c, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.4/libexec/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000416320, 0xc0001d0900, 0x86c, 0x86c, 0x2a9, 0x81f, 0xc000205730)
	/usr/local/Cellar/go/1.15.4/libexec/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc00030b080, 0x176c680, 0xc000416320, 0x100d3e5, 0x1610540, 0x1688f00)
	/usr/local/Cellar/go/1.15.4/libexec/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00030ae00, 0x1e89a98, 0xc0001ac398, 0x5, 0xc0001ac398, 0x298)
	/usr/local/Cellar/go/1.15.4/libexec/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00030ae00, 0x0, 0x0, 0xc000205d38)
	/usr/local/Cellar/go/1.15.4/libexec/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/Cellar/go/1.15.4/libexec/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc00030ae00, 0xc000252000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.4/libexec/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0000a18c0, 0xc000501998, 0x9, 0x9, 0xc000205d38, 0x16e6400, 0x130296b)
	/usr/local/Cellar/go/1.15.4/libexec/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x176c500, 0xc0000a18c0, 0xc000501998, 0x9, 0x9, 0x9, 0xc0001900e0, 0x0, 0x176c7a0)
	/usr/local/Cellar/go/1.15.4/libexec/src/io/io.go:314 +0x87
io.ReadFull(...)
	/usr/local/Cellar/go/1.15.4/libexec/src/io/io.go:333
net/http.http2readFrameHeader(0xc000501998, 0x9, 0x9, 0x176c500, 0xc0000a18c0, 0x0, 0x0, 0xc00056e6c0, 0x0)
	/usr/local/Cellar/go/1.15.4/libexec/src/net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc000501960, 0xc00056e6c0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.4/libexec/src/net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc000205fa8, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.4/libexec/src/net/http/h2_bundle.go:8251 +0x8d
net/http.(*http2ClientConn).readLoop(0xc000092a80)
	/usr/local/Cellar/go/1.15.4/libexec/src/net/http/h2_bundle.go:8179 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/Cellar/go/1.15.4/libexec/src/net/http/h2_bundle.go:7175 +0x685

goroutine 76 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/sourcegraph/src-cli/internal/campaigns.(*Service).ExecuteCampaignSpec
	/Users/erik/Code/sourcegraph/src-cli/internal/campaigns/service.go:227 +0xd8c

goroutine 43 [select]:
github.com/sourcegraph/src-cli/internal/output.newSpinner.func1(0x5f5e100, 0xc0004baff0, 0xc0000a42a0)
	/Users/erik/Code/sourcegraph/src-cli/internal/output/spinner.go:28 +0x159
created by github.com/sourcegraph/src-cli/internal/output.newSpinner
	/Users/erik/Code/sourcegraph/src-cli/internal/output/spinner.go:21 +0xc7

goroutine 44 [chan receive]:
github.com/sourcegraph/src-cli/internal/output.newProgressWithStatusBarsTTY.func1(0xc0000dc870)
	/Users/erik/Code/sourcegraph/src-cli/internal/output/progress_with_status_bars_tty.go:38 +0x8e
created by github.com/sourcegraph/src-cli/internal/output.newProgressWithStatusBarsTTY
	/Users/erik/Code/sourcegraph/src-cli/internal/output/progress_with_status_bars_tty.go:37 +0x208

goroutine 76 [running]:
runtime.throw(0x16b53e4, 0x15)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/panic.go:1116 +0x72 fp=0
xc0005c5af0 sp=0xc0005c5ac0 pc=0x10373d2
runtime.mapassign_faststr(0x16042a0, 0xc00015e120, 0xc000496360, 0x25, 0x1b1a080)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/map_faststr.go:291 +0x3d8 fp=0xc0005c5b58 sp=0xc0005c5af0 pc=0x10164b8
main.(*campaignProgressPrinter).PrintStatuses(0xc0000a0540, 0xc0003d60c0, 0x2, 0x2)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaign_progress_printer.go:90 +0x3f6 fp=0xc0005c5ed8 sp=0xc0005c5b58 pc=0x1554c36
main.(*campaignProgressPrinter).PrintStatuses-fm(0xc0003d60c0, 0x2, 0x2)
	/Users/erik/Code/sourcegraph/src-cli/cmd/src/campaign_progress_printer.go:71 +0x48 fp=0xc0005c5f08 sp=0xc0005c5ed8 pc=0x1592c88
github.com/sourcegraph/src-cli/internal/campaigns.(*Service).ExecuteCampaignSpec.func1(0xc0003d60b0, 0xc0003d60c0, 0x2, 0x2, 0xc000030180)
	/Users/erik/Code/sourcegraph/src-cli/internal/campaigns/service.go:228 +0x72 fp=0xc0005c5fb8 sp=0xc0005c5f08 pc=0x148f872
runtime.goexit()
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0005c5fc0 sp=0xc0005c5fb8 pc=0x106ca81
created by github.com/sourcegraph/src-cli/internal/campaigns.(*Service).ExecuteCampaignSpec
	/Users/erik/Code/sourcegraph/src-cli/internal/campaigns/service.go:227 +0xd8c
```

**Comment by mrnugget** [comment]
This is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/16195
