### ISSUE TITLE
Panic during db migration

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#16159]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Attempt this [migration](https://github.com/sourcegraph/sourcegraph/blob/c44a28b6976d680f1cc003bd5b541cfdceb9dd7e/migrations/frontend/1528395752_extend_worker_state_enums_with_failed.up.sql) on a large instance
2. Possibly observe logs such as this https://cloudlogging.app.goo.gl/SxRBAdGsULfyKa8D6 

<details>
<summary>Details</summary>

```
panic: (bug) frontend configuration server failed to start after 5m0s, this may indicate the DB is inaccessible

goroutine 113 [running]:
github.com/sourcegraph/sourcegraph/internal/conf.(*store).checkDeadlock(0xc000358fa0)
	github.com/sourcegraph/sourcegraph/internal/conf/store.go:162 +0x3f6
github.com/sourcegraph/sourcegraph/internal/conf.(*store).WaitUntilInitialized(0xc000358fa0)
	github.com/sourcegraph/sourcegraph/internal/conf/store.go:124 +0x5f
github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch(0xc000208f80, 0x2d128f0)
	github.com/sourcegraph/sourcegraph/internal/conf/client.go:130 +0xbb
github.com/sourcegraph/sourcegraph/internal/conf.Watch(0x2d128f0)
	github.com/sourcegraph/sourcegraph/internal/conf/client.go:105 +0x31
github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab.init.0.func1()
	github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab/client.go:37 +0x2d
created by github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab.init.0
	github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab/client.go:36 +0x35

goroutine 1 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f48be6bbf90, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0020d0218, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0020d0200, 0xc0006e6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0020d0200, 0xc0006e6000, 0x1000, 0x1000, 0x4d4752, 0xc0020d0200, 0x0)
	net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0003f4060, 0xc0006e6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	net/net.go:184 +0x8e
bufio.(*Reader).Read(0xc000b4f740, 0xc0027e8860, 0x5, 0x200, 0xc0020d0200, 0xc00169bc00, 0xa8a)
	bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x32831c0, 0xc000b4f740, 0xc0027e8860, 0x5, 0x200, 0x5, 0xa8a, 0xc00, 0xa8a)
	io/io.go:310 +0x87
io.ReadFull(...)
	io/io.go:329
github.com/lib/pq.(*conn).recvMessage(0xc0027e8840, 0xc0008fb150, 0xa8a, 0xc00, 0xa8a)
	github.com/lib/pq@v1.8.0/conn.go:941 +0x103
github.com/lib/pq.(*conn).recv1Buf(0xc0027e8840, 0xc0008fb150, 0xa84)
	github.com/lib/pq@v1.8.0/conn.go:996 +0x39
github.com/lib/pq.(*conn).recv1(...)
	github.com/lib/pq@v1.8.0/conn.go:1023
github.com/lib/pq.(*conn).simpleExec(0xc0027e8840, 0xc00169b000, 0xa84, 0xc001fc3080, 0x0, 0xc001fab208, 0xa90795, 0xc001fc30b0, 0x0)
	github.com/lib/pq@v1.8.0/conn.go:615 +0x1bc
github.com/lib/pq.(*conn).Exec(0xc0027e8840, 0xc00169b000, 0xa84, 0x46f1768, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/lib/pq@v1.8.0/conn.go:869 +0x292
github.com/lib/pq.(*conn).ExecContext(0xc0027e8840, 0x32c3d80, 0xc001fc30b0, 0xc00169b000, 0xa84, 0x46f1768, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/lib/pq@v1.8.0/conn_go18.go:42 +0x1c0
github.com/gchaincl/sqlhooks.(*ExecerContext).execContext(0xc0003f4068, 0x32c3d80, 0xc001fc30b0, 0xc00169b000, 0xa84, 0x46f1768, 0x0, 0x0, 0x32c3d80, 0xc001fc30b0, ...)
	github.com/gchaincl/sqlhooks@v1.3.0/sqlhooks.go:120 +0x257
github.com/gchaincl/sqlhooks.(*ExecerContext).ExecContext(0xc0003f4068, 0x32c3d80, 0xc001fc30b0, 0xc00169b000, 0xa84, 0x46f1768, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/gchaincl/sqlhooks@v1.3.0/sqlhooks.go:143 +0x166
database/sql.ctxDriverExec(0x32c3d00, 0xc0001aa000, 0x7f48be67c700, 0xc00147ece0, 0x0, 0x0, 0xc00169b000, 0xa84, 0x46f1768, 0x0, ...)
	database/sql/ctxutil.go:31 +0x227
database/sql.(*DB).execDC.func2()
	database/sql/sql.go:1519 +0x1db
database/sql.withLock(0x32a0b80, 0xc0020d0280, 0xc001fab700)
	database/sql/sql.go:3184 +0x69
database/sql.(*DB).execDC(0xc0014580c0, 0x32c3d00, 0xc0001aa000, 0xc0020d0280, 0xc001fca440, 0xc00169b000, 0xa84, 0x0, 0x0, 0x0, ...)
	database/sql/sql.go:1514 +0x4b7
database/sql.(*Conn).ExecContext(0xc001450ea0, 0x32c3d00, 0xc0001aa000, 0xc00169b000, 0xa84, 0x0, 0x0, 0x0, 0x4e7ea1, 0x469d520, ...)
	database/sql/sql.go:1821 +0xef
github.com/golang-migrate/migrate/v4/database/postgres.(*Postgres).Run(0xc00147ef40, 0x32875e0, 0xc0001ce000, 0x0, 0x0)
	github.com/golang-migrate/migrate/v4@v4.11.0/database/postgres/postgres.go:209 +0x169
github.com/golang-migrate/migrate/v4.(*Migrate).runMigrations(0xc0020d0480, 0xc001f332c0, 0xc0020d0480, 0x5b1977e7)
	github.com/golang-migrate/migrate/v4@v4.11.0/migrate.go:746 +0x685
github.com/golang-migrate/migrate/v4.(*Migrate).Up(0xc0020d0480, 0xc001fabab0, 0x32d4080)
	github.com/golang-migrate/migrate/v4@v4.11.0/migrate.go:284 +0x148
github.com/sourcegraph/sourcegraph/internal/db/dbutil.DoMigrate(0xc0020d0480, 0x1fdd062, 0x8)
	github.com/sourcegraph/sourcegraph/internal/db/dbutil/dbutil.go:193 +0x2f
github.com/sourcegraph/sourcegraph/internal/db/dbconn.MigrateDB(0xc0014580c0, 0x1fdd062, 0x8, 0x8, 0x3282fd0)
	github.com/sourcegraph/sourcegraph/internal/db/dbconn/dbconn.go:81 +0x60
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.InitDB(0xc00020e000, 0x0)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/serve_cmd.go:109 +0x188
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.Main(0x2d14078, 0x0, 0x0)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/serve_cmd.go:122 +0x88
github.com/sourcegraph/sourcegraph/cmd/frontend/shared.Main(0x2d14078)
	github.com/sourcegraph/sourcegraph/cmd/frontend/shared/frontend.go:22 +0x34
main.main()
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/main.go:31 +0x2d

goroutine 259 [select, 4 minutes]:
database/sql.(*DB).connectionResetter(0xc0007b43c0, 0x32c3cc0, 0xc000b69540)
	database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
	database/sql/sql.go:723 +0x193
```

</details>

Additional details can be found in our [Ops-Log](https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit?usp=sharing)

#### Expected behavior:

Migration succeeds

#### Actual behavior:

Database table schema_migratins stays dirty and prevents db access

**Comment by ggilmore** [comment]
https://github.com/sourcegraph/sourcegraph/blob/7c3779e7bbf078920df003f020857031dea5dad1/internal/db/dbutil/dbutil.go#L212-L226

Note that this log line didn't print during the incident. We would have known there was a database migration issue much earlier had it done so. This should be fixed.

**Comment by unknwon** [comment]
What's the desired outcome? Should we change to print the log then exit the program? 🤔

**Comment by daxmc99** [comment]
I think there are some deadlock concerns here as well but it’s very
important that the code does not exit if a migration is in progress
(schema_migrations dirty = true).

If the frontend dies or exits without setting dirty back to false, manual
intervention will be needed

**Comment by unknwon** [comment]
I'm not fully understand what we are aiming for here. Should we tell frontend to halt and roll back migration with an error if it takes too long to run? That seems manual intervention is required anyway, to fix the takes-too-long-migration.

**Comment by tsenart** [comment]
@unknwon: I think we should just not panic in the `conf` package, and keep trying.

**Comment by tsenart** [comment]
@efritz: I'm not sure if this is still relevant or not, but I'm triaging issues assigned to me and you've been working in this area recently so feel free to close or take into consideration.

**Comment by efritz** [comment]
What we want to do when we can't reach the frontend for configuration does not really affect what we do when migrations are progress. In the next two releases we will transfer to a scheme that will pre-run migrations so that there should be no length startup process to run in the frontends before it's accessible.
