### ISSUE TITLE
e2e: Repository component - external code host links

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#16243]
Build: https://buildkite.com/sourcegraph/e2e/builds/11566#636413e2-834c-491d-88c5-a43fb546ef51/59-1204

```
sourcegraph-e2e:   48 passing (3m)
--
  | sourcegraph-e2e:   9 pending
  | sourcegraph-e2e:   1 failing
  | sourcegraph-e2e:   1) e2e test suite
  | sourcegraph-e2e:        Repository component
  | sourcegraph-e2e:          external code host links
  | sourcegraph-e2e:            on repo navbar ("View on GitHub"):
  | sourcegraph-e2e:      Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/sourcegraph/client/web/src/end-to-end/end-to-end.test.ts)
  | sourcegraph-e2e:       at listOnTimeout (internal/timers.js:551:17)
  | sourcegraph-e2e:       at processTimers (internal/timers.js:494:7)
```

**Comment by felixfbecker** [comment]
Isn't this a duplicate of https://github.com/sourcegraph/sourcegraph/issues/16135#event-4052944742?

**Comment by pecigonzalo** [comment]
@felixfbecker you are right! I compared to the wrong list of issues and did not find it.
