### ISSUE TITLE
panic querying externalURLs endpoint on GQL (nil db handle via phabricator code?)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#19949]
Discovered by @muratsu. The following GQL query causes a panic in the backend for any search query that has results:

```
query SearchResults($query: String!) {
                    search(query: $query) {
                        results {
                            results {
                                __typename
                                ... on FileMatch {
                                    repository {
                                        name
                                        externalURLs {
                                            url
                                        }
                                    }
                                }
                            }
                        }
                    }
}
```

```
{
  "query": "a"
}
```

You can reproduce this locally by running the GQL against the query console--DO THIS LOCALLY. [link to local GQL query](https://sourcegraph.test:3443/api/console#%7B%22query%22%3A%22query%20SearchResults(%24query%3A%20String!)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20search(query%3A%20%24query)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20externalURLs%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%7D%22%2C%22operationName%22%3A%22SearchResults%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22a%5C%22%5Cn%7D%22%7D).

This issue has probably been here for a couple months. I haven't looked too deeply, but the panic happens [on this line](https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/internal/database/basestore/store.go#L98) where `s.handle.db` is nil. The caller for this panic is via:

- [external_services l1153](https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/internal/database/external_services.go#L1153)
- [external_services l1113](https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/internal/database/external_services.go#L1113:11)
- [phabricator l165](https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/internal/database/phabricator.go#L165)
- ...

Full stack trace:

```
12:49:40                  frontend | ERROR Errors during search, error: 1 error occurred:
12:49:40                  frontend | 	* error during decoding: context canceled
12:49:40                  frontend | graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
12:49:40                  frontend | goroutine 13097 [running]:
12:49:40                  frontend | github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0x53d28f0, 0x3db76a8, 0xc00421d3e0, 0x31ede60, 0x53634a0)
12:49:40                  frontend | 	/Users/rvt/go/pkg/mod/github.com/graph-gophers/graphql-go@v0.0.0-20201113091052-beb923fada29/log/log.go:21 +0x6f
12:49:40                  frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1(0xc001a4ed90, 0x3db76a8, 0xc00421d3e0, 0xc003ad9e90, 0xc003b3a300)
12:49:40                  frontend | 	/Users/rvt/go/pkg/mod/github.com/graph-gophers/graphql-go@v0.0.0-20201113091052-beb923fada29/internal/exec/exec.go:181 +0x8e
12:49:40                  frontend | panic(0x31ede60, 0x53634a0)
12:49:40                  frontend | 	/usr/local/Cellar/go/1.16/libexec/src/runtime/panic.go:965 +0x1b9
12:49:40                  frontend | github.com/sourcegraph/sourcegraph/internal/database/basestore.(*Store).Query(0xc002250068, 0x3db76a8, 0xc003b36810, 0xc003b36990, 0x2, 0xc003b36990, 0x5)
12:49:40                  frontend | 	/Users/rvt/sourcegraph/internal/database/basestore/store.go:98 +0x59
12:49:40                  frontend | github.com/sourcegraph/sourcegraph/internal/database.(*ExternalServiceStore).list(0xc003d0c000, 0x3db76a8, 0xc003b36810, 0x0, 0x0, 0x0, 0x0, 0xc0022fc6a0, 0x1, 0x1, ...)
12:49:40                  frontend | 	/Users/rvt/sourcegraph/internal/database/external_services.go:1153 +0x2c5
12:49:40                  frontend | github.com/sourcegraph/sourcegraph/internal/database.(*ExternalServiceStore).List(0xc003d0c000, 0x3db76a8, 0xc003b36810, 0x0, 0x0, 0x0, 0x0, 0xc0022fc6a0, 0x1, 0x1, ...)
12:49:40                  frontend | 	/Users/rvt/sourcegraph/internal/database/external_services.go:1113 +0x118
12:49:40                  frontend | github.com/sourcegraph/sourcegraph/internal/database.(*PhabricatorStore).GetByName(0xc0015e7b18, 0x3db76a8, 0xc003b36810, 0xc004883d60, 0x1c, 0x3ddb9a0, 0x53d28f0, 0x0)
12:49:40                  frontend | 	/Users/rvt/sourcegraph/internal/database/phabricator.go:165 +0x53a
12:49:40                  frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/externallink.linksForRepository(0x3db76a8, 0xc00421d3e0, 0x0, 0x0, 0xc00347e000, 0x0, 0x0, 0x0, 0x0)
12:49:40                  frontend | 	/Users/rvt/sourcegraph/cmd/frontend/graphqlbackend/externallink/repository.go:112 +0x2d4
12:49:40                  frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/externallink.Repository(0x3db76a8, 0xc00421d3e0, 0x0, 0x0, 0xc00347e000, 0x32eba00, 0xc00421d3e0, 0x40, 0x5aafa68, 0x40)
12:49:40                  frontend | 	/Users/rvt/sourcegraph/cmd/frontend/graphqlbackend/externallink/repository.go:32 +0x74
12:49:40                  frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*RepositoryResolver).ExternalURLs(0xc003297200, 0x3db76a8, 0xc00421d3e0, 0x0, 0x0, 0x0, 0x0, 0x0)
12:49:40                  frontend | 	/Users/rvt/sourcegraph/cmd/frontend/graphqlbackend/repository.go:286 +0xbf
12:49:40                  frontend | reflect.Value.call(0x3578460, 0xc004118b78, 0x4293, 0x35bb287, 0x4, 0xc003b3a318, 0x1, 0x1, 0x30, 0xc00009ecf0, ...)
12:49:40                  frontend | 	/usr/local/Cellar/go/1.16/libexec/src/reflect/value.go:476 +0x8e7
12:49:40                  frontend | reflect.Value.Call(0x3578460, 0xc004118b78, 0x4293, 0xc003b3a318, 0x1, 0x1, 0x4293, 0x1, 0xc001311d70)
12:49:40                  frontend | 	/usr/local/Cellar/go/1.16/libexec/src/reflect/value.go:337 +0xb9
12:49:40                  frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2(0xc001a4ed90, 0x3db76a8, 0xc00421d3e0, 0xc003b3a300, 0xc0039b58c0, 0xc003ad9ee0, 0x3db76a8, 0xc00421d3e0, 0x0)
12:49:40                  frontend | 	/Users/rvt/go/pkg/mod/github.com/graph-gophers/graphql-go@v0.0.0-20201113091052-beb923fada29/internal/exec/exec.go:205 +0x508
12:49:40                  frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x3db76a8, 0xc00421d3e0, 0xc001a4ed90, 0xc00157c000, 0xc0039b58c0, 0xc003b3a300, 0xc001311f01)
12:49:40                  frontend | 	/Users/rvt/go/pkg/mod/github.com/graph-gophers/graphql-go@v0.0.0-20201113091052-beb923fada29/internal/exec/exec.go:225 +0x1b5
12:49:40                  frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections.func1(0xc0025df5d0, 0xc001a4ed90, 0x3db76a8, 0xc00421d3e0, 0xc00157c000, 0xc003b3a2d0, 0xc0039b58c0)
12:49:40                  frontend | 	/Users/rvt/go/pkg/mod/github.com/graph-gophers/graphql-go@v0.0.0-20201113091052-beb923fada29/internal/exec/exec.go:85 +0x18d
12:49:40                  frontend | created by github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections
12:49:40                  frontend | 	/Users/rvt/go/pkg/mod/github.com/graph-gophers/graphql-go@v0.0.0-20201113091052-beb923fada29/internal/exec/exec.go:81 +0x625
12:49:40                  frontend | context: context.Background.WithValue(type *http.contextKey, val <not Stringer>).WithValue(type *http.contextKey, val 127.0.0.1:3082).WithCancel.WithCancel.WithValue(type ot.key, val <not Stringer>).WithValue(type opentracing.contextKey, val <not Stringer>).WithValue(type opentracing.contextKey, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val unknown).WithValue(type sessions.contextKey, val <not Stringer>).WithValue(type actor.key, val Actor UID 1, internal false).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type trace.key, val unknown).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val query SearchResults($query: String!) {
12:49:40                  frontend |                     search(query: $query) {
12:49:40                  frontend |                         results {
12:49:40                  frontend |                             results {
12:49:40                  frontend |                                 __typename
12:49:40                  frontend |                                 ... on FileMatch {
12:49:40                  frontend |                                     repository {
12:49:40                  frontend |                                         name
12:49:40                  frontend |                                         externalURLs {
12:49:40                  frontend |                                             url
12:49:40                  frontend |                                         }
12:49:40                  frontend |                                     }
12:49:40                  frontend |                                 }
12:49:40                  frontend |                             }
12:49:40                  frontend |                         }
12:49:40                  frontend |                     }
12:49:40                  frontend | })
```

**Comment by rvantonder** [comment]
Tagging @unknwon and @asdine based on commit history, please reassign as appropriate. This is a blocker for extension issues (CC @muratsu).

**Comment by unknwon** [comment]
Thanks for filing, I'll take a look.

**Comment by unknwon** [comment]
PR sent: https://github.com/sourcegraph/sourcegraph/pull/20034
