### ISSUE TITLE
panic: unknown changeset event kind for <nil>

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#20566]
Saw panics in the logs on dogfood 

https://console.cloud.google.com/errors/CKbPopaht97EsgE?time=PT6H&project=sourcegraph-dogfood&organizationId=1006954638239

<details>

```

g=codeintel.dbstore.RepoName error="unknown repository" count=1.000 elapsed=0.001
t=2021-04-30T16:54:11+0000 lvl=eror msg=codeintel.gitserver.Head error="dbstore.RepoName: unknown repository" count=1.000 elapsed=0.001
t=2021-04-30T16:54:11+0000 lvl=eror msg=codeintel.indexing.QueueRepository error="gitserver.Head: dbstore.RepoName: unknown repository" count=1.000 elapsed=0.050
t=2021-04-30T16:54:11+0000 lvl=eror msg=codeintel.indexing.HandleIndexabilityUpdate error="gitserver.Head: dbstore.RepoName: unknown repository" count=1.000 elapsed=4.813
t=2021-04-30T16:54:11+0000 lvl=eror msg="Failed to update index queue" err="gitserver.Head: dbstore.RepoName: unknown repository"
panic: unknown changeset event kind for <nil>

goroutine 30928898 [running]:
github.com/sourcegraph/sourcegraph/enterprise/internal/batches/types.ChangesetEventKindFor(0x0, 0x0, 0x0, 0x0)
  github.com/sourcegraph/sourcegraph/enterprise/internal/batches/types/changeset.go:902 +0x989
github.com/sourcegraph/sourcegraph/enterprise/internal/batches/webhooks.Webhook.upsertChangesetEvent(0xc0013c2970, 0x29d7a15, 0x6, 0x5d73468, 0xc0035b8540, 0xc009424c18, 0x13, 0x34d9, 0xc011c253a0, 0x20, ...)
  github.com/sourcegraph/sourcegraph/enterprise/internal/batches/webhooks/webhooks.go:127 +0x476
github.com/sourcegraph/sourcegraph/enterprise/internal/batches/webhooks.(*GitHubWebhook).handleGitHubWebhook(0xc001aaa0a8, 0x5d73468, 0xc0035b8540, 0xc00f6fd680, 0x284d7e0, 0xc012ba9860, 0x2, 0xc002132720)
  github.com/sourcegraph/sourcegraph/enterprise/internal/batches/webhooks/github.go:70 +0x21d
github.com/sourcegraph/sourcegraph/cmd/frontend/webhooks.(*GitHubWebhook).Dispatch.func1(0x442501, 0x0)
  github.com/sourcegraph/sourcegraph/cmd/frontend/webhooks/github_webhooks.go:85 +0x53
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc010071f20, 0xc009494a40)
  golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
  golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66

 ```

</details>

Version: 94687_2021-04-30_7b98b88
Container: us.gcr.io/sourcegraph-dev/frontend:7b98b88794d3ddd9507793ae99e2d3d124c6b9f3@sha256:5f5af2d5550218e156bf8f176a37ade526362d5ef29ee7d540af62d62b50d2bb

Regression was likely introduced before or at: 
7b98b88794d3ddd9507793ae99e2d3d124c6b9f3

**Comment by LawnGnome** [comment]
Fixed by #20571.
