### ISSUE TITLE
Flake: Go TestSearch

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#21382]
- **Name of test:** TestSearch (`cmd/searcher/search/search_test.go:28`)
- **Example failure:** https://buildkite.com/sourcegraph/sourcegraph/builds/97144#53b937be-010e-44f9-963c-c51341e4ce2f
- **PR**: https://github.com/sourcegraph/sourcegraph/pull/21383

#### Additional details

Example failure reported:
```
search_test.go:244: {foo false false false false false  [] false false 0 true false []  } failed: non-200 response: code=503 body=failed to get archive: context deadline exceeded
```

**Comment by keegancsmith** [comment]
@courier-new thanks for reporting and sending a PR to disable. The test should not be flakey though, so @stefanhengl and I added some extra debugging to try and catch the failure on CI. We suspect something strange is happening. https://github.com/sourcegraph/sourcegraph/pull/21389

**Comment by keegancsmith** [comment]
Failed on main! https://buildkite.com/sourcegraph/sourcegraph/builds/97276#f3a9faf5-ce5e-47f8-8552-e9f19eddf495

Based on the trace data, it is indeed just slowness in the test. My best guess is we do an `fsync` on the data written. And on a busy CI system this can be unreliable?

Seems like the best fix here is to just up the FetchTimeout.

<details>

```
goroutine 197 [running]:
runtime/pprof.writeGoroutineStacks(0x2ecf3e0, 0xc0001a2008, 0x30, 0xc001285d40)
	/root/.asdf/installs/golang/1.16/go/src/runtime/pprof/pprof.go:693 +0xab
runtime/pprof.writeGoroutine(0x2ecf3e0, 0xc0001a2008, 0x2, 0x3de9d01, 0xef0adab443c92e02)
	/root/.asdf/installs/golang/1.16/go/src/runtime/pprof/pprof.go:682 +0x52
runtime/pprof.(*Profile).WriteTo(0x3dd46a0, 0x2ecf3e0, 0xc0001a2008, 0x2, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/runtime/pprof/pprof.go:331 +0x504
github.com/sourcegraph/sourcegraph/cmd/searcher/search_test.TestSearch.func2.1(0x1dcd6500, 0xc000050960)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/cmd/searcher/search/search_test.go:251 +0x1f4
created by github.com/sourcegraph/sourcegraph/cmd/searcher/search_test.TestSearch.func2
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/cmd/searcher/search/search_test.go:242 +0x912

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000001500, 0x23f07c2, 0xa, 0x25793c0, 0x1)
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1240 +0x610
testing.runTests.func1(0xc000001500)
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1512 +0xa7
testing.tRunner(0xc000001500, 0xc00031fc78)
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1194 +0x203
testing.runTests(0xc0002f60a8, 0x3ddba60, 0x14, 0x14, 0xc023bbe8c3878194, 0x45e64bf2d9, 0x3df28c0, 0xc00031fd38)
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1510 +0x613
testing.(*M).Run(0xc000260000, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1418 +0x3b4
main.main()
	_testmain.go:167 +0x357

goroutine 52 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x3df2e60)
	/root/.asdf/installs/golang/1.16/packages/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0xb1
created by k8s.io/klog.init.0
	/root/.asdf/installs/golang/1.16/packages/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0x190

goroutine 85 [chan receive]:
github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch.func1(0xc0000502a0, 0x2579410)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/conf/client.go:137 +0x45
created by github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/conf/client.go:134 +0x1a5

goroutine 148 [select]:
github.com/sourcegraph/sourcegraph/internal/store.(*Store).PrepareZip(0xc0003e1b00, 0x2f00930, 0xc000113da0, 0xc0013a608a, 0x3, 0xc0013a6012, 0x28, 0x0, 0x0, 0x0, ...)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/store/store.go:167 +0x758
github.com/sourcegraph/sourcegraph/cmd/searcher/search.(*Service).search.func2(0x207ad36, 0x5ad6de, 0x2f00968, 0xc001081170, 0xc023bb9ef8d1ef59)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/cmd/searcher/search/search.go:222 +0x14a
github.com/sourcegraph/sourcegraph/internal/store.GetZipFileWithRetry(0xc0012af588, 0xc000000001, 0x1, 0x2f00930, 0xc000113da0, 0xc00002cc80)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/store/retry.go:14 +0x58
github.com/sourcegraph/sourcegraph/cmd/searcher/search.(*Service).search(0xc00000f080, 0x2f008c0, 0xc00003c380, 0xc0003caea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/cmd/searcher/search/search.go:230 +0x1036
github.com/sourcegraph/sourcegraph/cmd/searcher/search.(*Service).ServeHTTP(0xc00000f080, 0x2efda48, 0xc0013a4000, 0xc001d72c00)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/cmd/searcher/search/search.go:104 +0x3c8
net/http.serverHandler.ServeHTTP(0xc00133e1c0, 0x2efda48, 0xc0013a4000, 0xc001d72c00)
	/root/.asdf/installs/golang/1.16/go/src/net/http/server.go:2887 +0xcb
net/http.(*conn).serve(0xc0010c15e0, 0x2f00968, 0xc0002a3d40)
	/root/.asdf/installs/golang/1.16/go/src/net/http/server.go:1952 +0x87e
created by net/http.(*Server).Serve
	/root/.asdf/installs/golang/1.16/go/src/net/http/server.go:3013 +0x645

goroutine 194 [chan receive]:
testing.(*T).Run(0xc00031f080, 0x24e3fc4, 0x1, 0xc0001d89a0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1240 +0x610
github.com/sourcegraph/sourcegraph/cmd/searcher/search_test.TestSearch(0xc00031f080)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/cmd/searcher/search/search_test.go:231 +0xd3a
testing.tRunner(0xc00031f080, 0x25793c0)
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1194 +0x203
created by testing.(*T).Run
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1239 +0x5d8

goroutine 141 [select]:
github.com/sourcegraph/sourcegraph/internal/diskcache.(*Store).OpenWithPath(0xc001081440, 0x2f00968, 0xc001350150, 0xc00084c2c0, 0x40, 0xc000291050, 0x0, 0x2eceda0, 0xc0013501b0)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/diskcache/cache.go:131 +0x6ad
github.com/sourcegraph/sourcegraph/internal/diskcache.(*Store).Open(0xc001081440, 0x2f00968, 0xc001350150, 0xc00084c2c0, 0x40, 0xc00005a280, 0x0, 0x0, 0x0)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/diskcache/cache.go:60 +0xe5
github.com/sourcegraph/sourcegraph/internal/store.(*Store).PrepareZip.func2(0x2f00968, 0xc0010813b0, 0xc0003e1b00, 0xc00084c2c0, 0x40, 0xc0013a608a, 0x3, 0xc0013a6012, 0x28, 0x0, ...)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/store/store.go:151 +0x28f
created by github.com/sourcegraph/sourcegraph/internal/store.(*Store).PrepareZip
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/store/store.go:146 +0x685

goroutine 140 [sleep]:
time.Sleep(0x2540be400)
	/root/.asdf/installs/golang/1.16/go/src/runtime/time.go:193 +0xd2
github.com/sourcegraph/sourcegraph/internal/store.(*Store).watchConfig(0xc0003e1b00)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/store/store.go:376 +0xf8
created by github.com/sourcegraph/sourcegraph/internal/store.(*Store).Start.func1
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/store/store.go:106 +0x2e9

goroutine 195 [IO wait]:
internal/poll.runtime_pollWait(0x7f1eb6153e88, 0x72, 0x72)
	/root/.asdf/installs/golang/1.16/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000b6418, 0x72, 0x0, 0x0, 0x23b8bb0)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000b6400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_unix.go:401 +0x32f
net.(*netFD).accept(0xc0000b6400, 0x47e300, 0xc00031ea80, 0x8)
	/root/.asdf/installs/golang/1.16/go/src/net/fd_unix.go:172 +0x58
net.(*TCPListener).accept(0xc00000f098, 0xc00041c3f0, 0x0, 0x1ae88a38)
	/root/.asdf/installs/golang/1.16/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).Accept(0xc00000f098, 0xc000535d30, 0x4777ce, 0xc000535d00, 0x49fe60)
	/root/.asdf/installs/golang/1.16/go/src/net/tcpsock.go:261 +0x8e
net/http.(*Server).Serve(0xc00133e1c0, 0x2efd838, 0xc00000f098, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/server.go:2981 +0x470
net/http/httptest.(*Server).goServe.func1(0xc00041c3f0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/httptest/server.go:308 +0xd9
created by net/http/httptest.(*Server).goServe
	/root/.asdf/installs/golang/1.16/go/src/net/http/httptest/server.go:306 +0x6a

goroutine 196 [select]:
net/http.(*persistConn).roundTrip(0xc0000c4fc0, 0xc000686680, 0x0, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/transport.go:2610 +0x906
net/http.(*Transport).roundTrip(0x3ddab60, 0xc000328900, 0xc0005e30d0, 0x44cb73, 0x7f1eb61b5548)
	/root/.asdf/installs/golang/1.16/go/src/net/http/transport.go:592 +0xece
net/http.(*Transport).RoundTrip(0x3ddab60, 0xc000328900, 0x3ddab60, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/roundtrip.go:17 +0x47
net/http.send(0xc000328900, 0x2ecf0c0, 0x3ddab60, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001225f8, 0xc0005e3410)
	/root/.asdf/installs/golang/1.16/go/src/net/http/client.go:251 +0x6db
net/http.(*Client).send(0x3df1e40, 0xc000328900, 0x0, 0x0, 0x0, 0xc0001225f8, 0x0, 0x1, 0x4)
	/root/.asdf/installs/golang/1.16/go/src/net/http/client.go:175 +0x1d6
net/http.(*Client).do(0x3df1e40, 0xc000328900, 0x0, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/client.go:717 +0x2cc
net/http.(*Client).Do(...)
	/root/.asdf/installs/golang/1.16/go/src/net/http/client.go:585
net/http.(*Client).Post(0x3df1e40, 0xc000043350, 0x16, 0x24dbb9d, 0x21, 0x2ecf540, 0xc0001d89e0, 0x0, 0x0, 0xee0000c000290ea0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/client.go:845 +0x215
net/http.(*Client).PostForm(0x3df1e40, 0xc000043350, 0x16, 0xc000091aa0, 0xc00017c8e0, 0xc002d36180, 0xb)
	/root/.asdf/installs/golang/1.16/go/src/net/http/client.go:877 +0x135
net/http.PostForm(...)
	/root/.asdf/installs/golang/1.16/go/src/net/http/client.go:862
github.com/sourcegraph/sourcegraph/cmd/searcher/search_test.doSearch(0xc000043350, 0x16, 0xc000091db0, 0xc000050960, 0x3d7a620, 0x5bdf91, 0x5bdf00, 0x361a6ba)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/cmd/searcher/search/search_test.go:462 +0xa26
github.com/sourcegraph/sourcegraph/cmd/searcher/search_test.TestSearch.func2(0xc00031f200)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/cmd/searcher/search/search_test.go:266 +0x1af
testing.tRunner(0xc00031f200, 0xc0001d89a0)
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1194 +0x203
created by testing.(*T).Run
	/root/.asdf/installs/golang/1.16/go/src/testing/testing.go:1239 +0x5d8

goroutine 132 [IO wait]:
internal/poll.runtime_pollWait(0x7f1eb6154058, 0x72, 0x3d5f9c0)
	/root/.asdf/installs/golang/1.16/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000b6598, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000b6580, 0xc00084b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_unix.go:166 +0x28f
net.(*netFD).Read(0xc0000b6580, 0xc00084b000, 0x1000, 0x1000, 0x0, 0x0, 0xee0000c000290ea0)
	/root/.asdf/installs/golang/1.16/go/src/net/fd_posix.go:55 +0x69
net.(*conn).Read(0xc001c7e020, 0xc00084b000, 0x1000, 0x1000, 0xc0000919f0, 0x57d547, 0xc001287ad0)
	/root/.asdf/installs/golang/1.16/go/src/net/net.go:183 +0xec
net/http.(*persistConn).Read(0xc0000c4fc0, 0xc00084b000, 0x1000, 0x1000, 0xc000091bb8, 0xc000290e40, 0xc000091ba0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/transport.go:1922 +0x106
bufio.(*Reader).fill(0xc000112cc0)
	/root/.asdf/installs/golang/1.16/go/src/bufio/bufio.go:101 +0x1af
bufio.(*Reader).Peek(0xc000112cc0, 0x1, 0xc000050c00, 0xc00081bb84, 0x48b587, 0x361a6ba, 0x946)
	/root/.asdf/installs/golang/1.16/go/src/bufio/bufio.go:139 +0xa5
net/http.(*persistConn).readLoop(0xc0000c4fc0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/transport.go:2083 +0x2b3
created by net/http.(*Transport).dialConn
	/root/.asdf/installs/golang/1.16/go/src/net/http/transport.go:1743 +0xc2c

goroutine 133 [select]:
net/http.(*persistConn).writeLoop(0xc0000c4fc0)
	/root/.asdf/installs/golang/1.16/go/src/net/http/transport.go:2382 +0x1b7
created by net/http.(*Transport).dialConn
	/root/.asdf/installs/golang/1.16/go/src/net/http/transport.go:1744 +0xc51

goroutine 200 [syscall]:
syscall.Syscall(0x4a, 0xf, 0x0, 0x0, 0x4fdef5, 0xc001b55860, 0x46a07b)
	/root/.asdf/installs/golang/1.16/go/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.Fsync(0xf, 0xc001b55801, 0x217bb20)
	/root/.asdf/installs/golang/1.16/go/src/syscall/zsyscall_linux_amd64.go:413 +0x4e
internal/poll.(*FD).Fsync.func1(...)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_fsync_posix.go:18
internal/poll.ignoringEINTR(...)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_posix.go:74
internal/poll.(*FD).Fsync(0xc001b55860, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_fsync_posix.go:17 +0xdf
os.(*File).Sync(0xc000122628, 0x63, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/os/file_posix.go:168 +0x8a
github.com/sourcegraph/sourcegraph/internal/diskcache.fsync(0xc0004101c0, 0x63, 0xc0004101c0, 0x63)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/diskcache/cache.go:311 +0x88
github.com/sourcegraph/sourcegraph/internal/diskcache.doFetch(0x2f00930, 0xc001b555c0, 0xc000050e40, 0x5e, 0xc000291050, 0x0, 0x0, 0x0)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/diskcache/cache.go:195 +0x36b
github.com/sourcegraph/sourcegraph/internal/diskcache.(*Store).OpenWithPath.func2(0xc001081440, 0xc000050e40, 0x5e, 0xc000291050, 0xc001b55500, 0x2f00930, 0xc001b555c0)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/diskcache/cache.go:127 +0xbd
created by github.com/sourcegraph/sourcegraph/internal/diskcache.(*Store).OpenWithPath
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/diskcache/cache.go:121 +0x5de

goroutine 136 [select]:
github.com/sourcegraph/sourcegraph/internal/mutablelimiter.(*Limiter).do(0xc0008461c8, 0xf)
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/mutablelimiter/limiter.go:97 +0x359
created by github.com/sourcegraph/sourcegraph/internal/mutablelimiter.New
	/buildkite/builds/buildkite-agent-65c8b757c8-xdt2r-1/sourcegraph/sourcegraph/internal/mutablelimiter/limiter.go:41 +0x152

goroutine 134 [IO wait]:
internal/poll.runtime_pollWait(0x7f1eb6153da0, 0x72, 0x3d5f9c0)
	/root/.asdf/installs/golang/1.16/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000260598, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000260580, 0xc0030d7e41, 0x1, 0x1, 0x0, 0x0, 0x0)
	/root/.asdf/installs/golang/1.16/go/src/internal/poll/fd_unix.go:166 +0x28f
net.(*netFD).Read(0xc000260580, 0xc0030d7e41, 0x1, 0x1, 0x1, 0x7f1eb61cc518, 0xc00032a718)
	/root/.asdf/installs/golang/1.16/go/src/net/fd_posix.go:55 +0x69
net.(*conn).Read(0xc000010288, 0xc0030d7e41, 0x1, 0x1, 0xc00032a790, 0xd8a21b, 0x2eccfa0)
	/root/.asdf/installs/golang/1.16/go/src/net/net.go:183 +0xec
net/http.(*connReader).backgroundRead(0xc0030d7e30)
	/root/.asdf/installs/golang/1.16/go/src/net/http/server.go:692 +0x9f
created by net/http.(*connReader).startBackgroundRead
	/root/.asdf/installs/golang/1.16/go/src/net/http/server.go:688 +0x18d
total time taken: 503.573002ms
t=2021-05-26T16:27:41+0000 lvl=info msg="structural search" repo=foo
t=2021-05-26T16:27:41+0000 lvl=info msg="running comby" args="filename contains regex metachars  -json-lines -f (1 file patterns) -match-only -jobs 4 -matcher .generic -zip /tmp/search_test107049928/6e096716a739af77e0e95eaaad1b0cbba430e517d33bc42e0e8aa6812c96775d.zip"
t=2021-05-26T16:27:41+0000 lvl=info msg="comby invocation" num_matches=1
--- FAIL: TestSearch (1.77s)
    --- FAIL: TestSearch/0 (0.50s)
        search_test.go:268: PatternInfo{"foo",nopath} failed: non-200 response: code=503 body=failed to get archive: context deadline exceeded
    --- FAIL: TestSearch/1 (0.50s)
        search_test.go:268: PatternInfo{"World",case,nopath} failed: non-200 response: code=503 body=failed to get archive: context deadline exceeded
    --- FAIL: TestSearch/2 (0.50s)
        search_test.go:268: PatternInfo{"world",case,nopath} failed: non-200 response: code=503 body=failed to get archive: context deadline exceeded
FAIL
coverage: 64.6% of statements
FAIL	github.com/sourcegraph/sourcegraph/cmd/searcher/search	6.962s
```

</details>
