### ISSUE TITLE
Worker panics if DB initialization fails

### ISSUE THREAD

**Issue by slewiskelly** [sourcegraph/sourcegraph#22286]
- **Sourcegraph version:** 3.29.0

#### Steps to reproduce:

1. Deploy a worker that is unable to connect to an SQL backend

#### Expected behavior:

I expect the worker to still fail but display the error returned from `dbconn.SetupGlobalConnection`, rather than panic because type assertion fails.

#### Actual behavior:

If `dbconn.SetupGlobalConnection` fails it returns `nil`. An unsafe type assertion is then performed in `shared.InitDatabase`, causing a panic:

```
panic: interface conversion: interface {} is nil, not *sql.DB

goroutine 83 [running]:
github.com/sourcegraph/sourcegraph/cmd/worker/shared.InitDatabase(...)
        github.com/sourcegraph/sourcegraph/cmd/worker/shared/db.go:14
github.com/sourcegraph/sourcegraph/enterprise/cmd/worker/internal/codeintel.glob..func2(0x7f9892691290, 0xc00021a4f0, 0x10, 0x10)
        github.com/sourcegraph/sourcegraph/enterprise/cmd/worker/internal/codeintel/dbstore.go:27 +0x20d
github.com/sourcegraph/sourcegraph/cmd/worker/shared.(*MemoizedConstructor).Init.func1()
        github.com/sourcegraph/sourcegraph/cmd/worker/shared/memo.go:24 +0x32
sync.(*Once).doSlow(0xc0001430e8, 0xc0002285c8)
        sync/once.go:68 +0xec
sync.(*Once).Do(...)
        sync/once.go:59
github.com/sourcegraph/sourcegraph/cmd/worker/shared.(*MemoizedConstructor).Init(0xc0001430c0, 0xc00021a4f0, 0xc00014e160, 0x7f98922d7400, 0xc00014e160)
        github.com/sourcegraph/sourcegraph/cmd/worker/shared/memo.go:24 +0x8d
github.com/sourcegraph/sourcegraph/enterprise/cmd/worker/internal/codeintel.InitDBStore(...)
        github.com/sourcegraph/sourcegraph/enterprise/cmd/worker/internal/codeintel/dbstore.go:16
github.com/sourcegraph/sourcegraph/enterprise/cmd/worker/internal/codeintel.(*janitorJob).Routines(0x33d1dc0, 0x2314f70, 0xc000143700, 0x11, 0xc000388998, 0x0, 0x0, 0x0)
        github.com/sourcegraph/sourcegraph/enterprise/cmd/worker/internal/codeintel/janitor_job.go:36 +0x12c
github.com/sourcegraph/sourcegraph/cmd/worker/shared.runRoutinesConcurrently.func1(0xc001081500, 0xc000a77920, 0x2314f70, 0xc000143700, 0xc00108aa80, 0x23255e8, 0xc0005bb4e0, 0xc00021a450, 0x1e6d979, 0x11)
        github.com/sourcegraph/sourcegraph/cmd/worker/shared/main.go:215 +0xca
created by github.com/sourcegraph/sourcegraph/cmd/worker/shared.runRoutinesConcurrently
        github.com/sourcegraph/sourcegraph/cmd/worker/shared/main.go:212 +0x33e
```

```go
// github.com/sourcegraph/sourcegraph/cmd/worker/shared/db.go

func InitDatabase() (*sql.DB, error) {
	conn, err := initDatabaseMemo.Init()
	return conn.(*sql.DB), err // Unsafe type assertion causes a panic instead of returning an error.
}


var initDatabaseMemo = NewMemoizedConstructor(func() (interface{}, error) {
	postgresDSN := WatchServiceConnectionValue(func(serviceConnections conftypes.ServiceConnections) string {
		return serviceConnections.PostgresDSN
	})

	if err := dbconn.SetupGlobalConnection(postgresDSN); err != nil {
		return nil, fmt.Errorf("failed to connect to frontend database: %s", err)
	}

	return dbconn.Global, nil
})
```

Propose that `shared.InitDatabase` be changed like so:

```go
func InitDatabase() (*sql.DB, error) {
	conn, err := initDatabaseMemo.Init()
	if err != nil {
		return nil, err
	}

	return conn.(*sql.DB), nil
}
```

An unsafe type assertion is still performed but there is confidence that an `*sql.DB` is always returned if an error is not encountered.

**Comment by camdencheek** [comment]
Closing since it looks like this was fixed by #22335 -- thanks!
