### ISSUE TITLE
[release-blocker] repo updater panics

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#23086]
- **Sourcegraph version:** 28e524cf3a2b3bed94611f8f158fc26c42e21df0
- **Platform information:** k8s.sgdev.org : repo-updater
#### Steps to reproduce:

1. Repo-updater is currently in a crash-loopbackoff 
2. Error logs:
```
t=2021-07-21T16:39:28+0000 lvl=eror msg="Syncing changeset" err="ERROR: duplicate key value violates unique constraint \"changeset_events_changeset_id_kind_key_unique\" (SQLSTATE 23505)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x116a0a9]

goroutine 975 [running]:
github.com/sourcegraph/sourcegraph/internal/repos.(*Syncer).sync(0xc00030ddc0, 0x27e3128, 0xc005348c40, 0xc0013cd110, 0xc001c01a40, 0xc0022df860, 0x0, 0x0, 0x0, 0x0, ...)
  github.com/sourcegraph/sourcegraph/internal/repos/syncer.go:1108 +0x4c9
github.com/sourcegraph/sourcegraph/internal/repos.(*Syncer).StreamingSyncExternalService(0xc00030ddc0, 0x27e31d0, 0xc005348c40, 0xc0017a5110, 0x1, 0xdf8475800, 0x0, 0x0)
  github.com/sourcegraph/sourcegraph/internal/repos/syncer.go:1024 +0xdc5
github.com/sourcegraph/sourcegraph/internal/repos.(*Syncer).SyncExternalService(0xc00030ddc0, 0x27e31d0, 0xc0052f3cb0, 0xc0017a5110, 0x1, 0xdf8475800, 0x27e31d0, 0xc0052f3cb0)
  github.com/sourcegraph/sourcegraph/internal/repos/syncer.go:165 +0x26cc
github.com/sourcegraph/sourcegraph/internal/repos.(*syncHandler).Handle(0xc0034f5ef0, 0x27e31d0, 0xc0052f3cb0, 0x27993a0, 0xc0052e1c70, 0x0, 0x0)
  github.com/sourcegraph/sourcegraph/internal/repos/syncer.go:137 +0xfe
github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).handle(0xc003504840, 0x27993a0, 0xc0052e1c70, 0x2, 0xc002bf94a0)
  github.com/sourcegraph/sourcegraph/internal/workerutil/worker.go:202 +0x196
github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).dequeueAndHandle.func2(0xc003504840, 0x27993a0, 0xc0052e1c70, 0xc00244e310)
  github.com/sourcegraph/sourcegraph/internal/workerutil/worker.go:188 +0xb6
created by github.com/sourcegraph/sourcegraph/internal/workerutil.(*Worker).dequeueAndHandle
  github.com/sourcegraph/sourcegraph/internal/workerutil/worker.go:176 +0x437
```

GKE error tracing: https://console.cloud.google.com/errors/COfl5b2SrLCXOQ?time=PT6H&project=sourcegraph-dogfood&folder&organizationId

#### Expected behavior:
repo-updater continues to work fine

#### Actual behavior:
Continual panics

**Comment by daxmc99** [comment]
This is not a release blocker, this is due to data corruption in our Postgres deployment due to continual releases. 
Filing a secondary issue to convert all our database deployments to Statefulset to avoid this issue in the future
