### ISSUE TITLE
e2e: siteadmin init test failing

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#25135]
The siteadmin init test is failing and blocking the release of 3.32.0:

```
    sourcegraph-e2e: Visited routes:
    sourcegraph-e2e: /sign-in
    sourcegraph-e2e: /site-admin/init
    sourcegraph-e2e:   0 passing (31s)
    sourcegraph-e2e:   1 failing
    sourcegraph-e2e:   1) e2e test suite
    sourcegraph-e2e:        "before all" hook in "e2e test suite":
    sourcegraph-e2e:      TimeoutError: waiting for selector `.test-signin-form` failed: timeout 30000ms exceeded
    sourcegraph-e2e:       at new WaitTask (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
    sourcegraph-e2e:       at DOMWorld.waitForSelectorInPage (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
    sourcegraph-e2e:       at Object.internalHandler.waitFor (node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    sourcegraph-e2e:       at DOMWorld.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
    sourcegraph-e2e:       at Frame.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
    sourcegraph-e2e:       at Page.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
    sourcegraph-e2e:       at Driver.ensureLoggedIn (client/shared/src/testing/driver.ts:133:29)
    sourcegraph-e2e:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
    sourcegraph-e2e:       at Context.<anonymous> (client/web/src/end-to-end/end-to-end.test.ts:46:9)
    
```
Full log [here](https://buildkite.com/sourcegraph/e2e/builds/16312#460bee85-6472-4ac4-894a-4985c2e7e948)

and a link to the video [here](https://buildkite.com/organizations/sourcegraph/pipelines/e2e/builds/16312/jobs/460bee85-6472-4ac4-894a-4985c2e7e948/artifacts/661803a6-eb19-4a69-ae86-52d40833ab99)

**Comment by davejrt** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/commit/ce1bb5d0a7102eeb6b57e6238d85900b03eea529
