### ISSUE TITLE
Problem with zoekt-server caused Sourcegraph server container to crash but not die

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2771]
I am running Sourcegraph `insiders` locally with the Go language server.

I clicked on **Find references** and the request timed out. I refreshed the page and Sourcegraph was unable to respond. It's worth noting that I couldn't kill the Sourcegraph server container and had to restart Docker in order to re-launch Sourcegraph server.

Below is the relevant output from the logs:

```sourcegraph_1     | 18:49:14           searcher | t=2019-03-15T18:49:14+0000 lvl=dbug msg="search request" repo=github.com/sourcegraph-demo/buildkit commit=c592b7c3561b20541c4e2fae116b6a853643835a pattern=github\\.com/sourcegraph-demo/buildkit/api/services/control isRegExp=true isWordMatch=false isCaseSensitive=false patternMatchesContent=true patternMatchesPath=true matches=0 code=200 duration=4.4889832s err=nil
sourcegraph_1     | 18:49:33       repo-updater | t=2019-03-15T18:49:32+0000 lvl=dbug msg="github sync: GetRepository" repo=sourcegraph/sourcegraph
sourcegraph_1     | 18:49:57  zoekt-indexserver | 2019/03/15 18:49:53 [DEBUG] POST http://127.0.0.1:3090/.internal/repos/list
sourcegraph_1     | 18:50:10       repo-updater | t=2019-03-15T18:49:55+0000 lvl=dbug msg="syncing all OTHER external services"
sourcegraph_1     | 18:50:41    zoekt-webserver | 2019/03/15 18:50:32 watchdog: Get http://127.0.0.1:3070: context deadline exceeded
sourcegraph_1     | 18:50:56       repo-updater | t=2019-03-15T18:49:54+0000 lvl=dbug msg=RunGitoliteRepositorySyncWorker:GitoliteUpdateRepos
sourcegraph_1     | 18:51:16    zoekt-webserver | panic: watchdog: Get http://127.0.0.1:3070: context deadline exceeded
sourcegraph_1     | 18:51:32       github-proxy | 2019/03/15 18:51:18 Get https://api.github.com/user/repos?page=1&per_page=100&sort=pushed: dial tcp: i/o timeout
sourcegraph_1     | 18:51:35       repo-updater | t=2019-03-15T18:50:22+0000 lvl=dbug msg="updating configured repos" source=gitlab: count=0
sourcegraph_1     | 18:51:42    zoekt-webserver | goroutine 38 [running]:
sourcegraph_1     | 18:51:43    zoekt-webserver | zoekt-webserver died. Shutting down...
sourcegraph_1     | log.Panicf(0x8b912a, 0xc, 0xc00007ff90, 0x1, 0x1)
sourcegraph_1     | 18:51:43       repo-updater | t=2019-03-15T18:51:41+0000 lvl=eror msg="error syncing other external services repos" error="context deadline exceeded"
sourcegraph_1     | 18:51:44       repo-updater | t=2019-03-15T18:51:43+0000 lvl=dbug msg="syncing all OTHER external services"
sourcegraph_1     | 18:51:44    zoekt-webserver |       /usr/local/go/src/log/log.go:340 +0xc0
sourcegraph_1     | 18:51:44    zoekt-webserver | main.watchdog(0x6fc23ac00, 0xc0000fa160, 0x15)
sourcegraph_1     | 18:51:44    zoekt-webserver |       /buildkite/builds/buildkite-agent-7f87bdbbd5-bqtm2-2/sourcegraph/.golang/sourcegraph/pkg/mod/github.com/sourcegraph/zoekt@v0.0.0-20190116094554-8aa57bd35909/cmd/zoekt-webserver/main.go:259 +0x1b3
sourcegraph_1     | 18:51:44    zoekt-webserver | created by main.main
sourcegraph_1     | 18:51:44    zoekt-webserver |       /buildkite/builds/buildkite-agent-7f87bdbbd5-bqtm2-2/sourcegraph/.golang/sourcegraph/pkg/mod/github.com/sourcegraph/zoekt@v0.0.0-20190116094554-8aa57bd35909/cmd/zoekt-webserver/main.go:207 +0x92d
sourcegraph_1     | 18:51:44    zoekt-webserver | Terminating zoekt-webserver
go-lang-server_1  | jsonrpc2: protocol error: websocket: close 1001 (going away)
go-lang-server_1  | langserver-go: connection #14 closed
sourcegraph_1     | 18:51:45 management-console | Terminating management-console
sourcegraph_1     | 18:51:45  zoekt-indexserver | Terminating zoekt-indexserver
sourcegraph_1     | 18:51:45       query-runner | Terminating query-runner
sourcegraph_1     | 18:51:45          gitserver | Terminating gitserver
sourcegraph_1     | 18:51:46            symbols | Terminating symbols
sourcegraph_1     | 18:51:46           searcher | Terminating searcher
sourcegraph_1     | 18:51:46       github-proxy | Terminating github-proxy
sourcegraph_1     | 18:51:46           frontend | Terminating frontend
sourcegraph_1     | 18:51:46       repo-updater | Terminating repo-updater
sourcegraph_1     | 18:51:46     syntect_server | Terminating syntect_server
sourcegraph_1     | 18:51:47              nginx | Terminating nginx
sourcegraph_1     | 18:51:48              redis | Terminating redis
sourcegraph_1     | 18:51:50           postgres | Terminating postgres
dev_sourcegraph_1 exited with code 0
```

**Comment by slimsag** [comment]
Can you upload the full logs to gist.github.com?

**Comment by keegancsmith** [comment]
we tweaked our watchdog timeouts. This should be resolved.
