### ISSUE TITLE
Batch change fails for Release Process

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#30588]
```
Title: release: sourcegraph@3.36.3
Body: This pull request is part of the Sourcegraph 3.36.3 release.


* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)

### :warning: Additional changes required

These steps must be completed before this PR can be merged, unless otherwise stated. Push any required changes directly to this PR branch.

- [ ] Update the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) to include all the changes included in this patch. Learn more about [how to update CHANGELOG.md](departments/product-engineering/engineering/process/releases#changelogmd).
- [ ] If any specific upgrade steps are required, update the upgrade guides in `doc/admin/updates`
- [ ] Ensure all other pull requests in the batch change have been merged
- [ ] Run `yarn run release release:finalize` to generate the tags required. CI will not pass until this command is run.
- [ ] Re-run the build on this branch (using either `sg ci build --wait` or the Buildkite UI) and merge when the build passes.

cc @michaellzc

sourcegraph/about: Preparing pull request for change from 'main' to 'publish-3.36.3':

Title: release: sourcegraph@3.36.3
Body: This pull request is part of the Sourcegraph 3.36.3 release.


* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)
sourcegraph/deploy-sourcegraph: Preparing pull request for change from '3.36' to 'publish-3.36.3':

Title: release: sourcegraph@3.36.3
Body: This pull request is part of the Sourcegraph 3.36.3 release.


* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)
sourcegraph/deploy-sourcegraph-docker: Preparing pull request for change from '3.36' to 'publish-3.36.3':

Title: release: sourcegraph@3.36.3
Body: This pull request is part of the Sourcegraph 3.36.3 release.


* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)

### :warning: Additional changes required

These steps must be completed before this PR can be merged, unless otherwise stated. Push any required changes directly to this PR branch.

- [ ] Follow the [release guide](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/RELEASING.md) to complete this PR (note: `pure-docker` release is optional for patch releases)

cc @michaellzc

sourcegraph/deploy-sourcegraph-aws: Preparing pull request for change from 'master' to 'publish-3.36.3':

Title: release: sourcegraph@3.36.3
Body: This pull request is part of the Sourcegraph 3.36.3 release.


* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)
sourcegraph/deploy-sourcegraph-digitalocean: Preparing pull request for change from 'master' to 'publish-3.36.3':

Title: release: sourcegraph@3.36.3
Body: This pull request is part of the Sourcegraph 3.36.3 release.


* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)
sourcegraph/sourcegraph (main): created pull request https://github.com/sourcegraph/sourcegraph/pull/30587
sourcegraph/about (main): created pull request https://github.com/sourcegraph/about/pull/5111
sourcegraph/deploy-sourcegraph (3.36): created pull request https://github.com/sourcegraph/deploy-sourcegraph/pull/4075
sourcegraph/deploy-sourcegraph-docker (3.36): created pull request https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/744
sourcegraph/deploy-sourcegraph-aws (master): created pull request https://github.com/sourcegraph/deploy-sourcegraph-aws/pull/128
sourcegraph/deploy-sourcegraph-digitalocean (master): created pull request https://github.com/sourcegraph/deploy-sourcegraph-digitalocean/pull/118
Creating batch change in https://k8s.sgdev.org
Rendered batch change spec:

name: release-sourcegraph-3.36.3
description: "Track publishing of sourcegraph v3.36.3:
  https://github.com/sourcegraph/sourcegraph/issues/30562"
importChangesets:
  - repository: github.com/sourcegraph/sourcegraph
    externalIDs:
      - 30587
  - repository: github.com/sourcegraph/about
    externalIDs:
      - 5111
  - repository: github.com/sourcegraph/deploy-sourcegraph
    externalIDs:
      - 4075
  - repository: github.com/sourcegraph/deploy-sourcegraph-docker
    externalIDs:
      - 744
  - repository: github.com/sourcegraph/deploy-sourcegraph-aws
    externalIDs:
      - 128
  - repository: github.com/sourcegraph/deploy-sourcegraph-digitalocean
    externalIDs:
      - 118

Error: Command failed with exit code 1: src batch apply -namespace sourcegraph -f -

❌ Error:
   failed to check version returned by Sourcegraph: Invalid Semantic Version
   

💡 The troubleshooting documentation can help to narrow down the cause of the errors:
   https://docs.sourcegraph.com/batch_changes/references/troubleshooting
   

    at makeError (/Users/kwojkovich/Documents/sourcegraph/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/kwojkovich/Documents/sourcegraph/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at applyBatchChange (/Users/kwojkovich/Documents/sourcegraph/dev/release/src/batchChanges.ts:146:5)
    at Object.createBatchChange (/Users/kwojkovich/Documents/sourcegraph/dev/release/src/batchChanges.ts:74:12)
    at Object.run (/Users/kwojkovich/Documents/sourcegraph/dev/release/src/release.ts:509:21)
    at /Users/kwojkovich/Documents/sourcegraph/dev/release/src/release.ts:65:21
    at async Promise.all (index 0)
    at runStep (/Users/kwojkovich/Documents/sourcegraph/dev/release/src/release.ts:60:5)
    at main (/Users/kwojkovich/Documents/sourcegraph/dev/release/src/main.ts:18:5) {
  shortMessage: 'Command failed with exit code 1: src batch apply -namespace sourcegraph -f -',
  command: 'src batch apply -namespace sourcegraph -f -',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: '\x1B[?25l\n' +
    '\x1B[?25h\x1B[?25l❌ \x1B[38;5;124mError:\x1B[0m\n' +
    '\x1B[?25h\x1B[?25l   \x1B[?25l\x1B[1mfailed to check version returned by Sourcegraph: Invalid Semantic Version\n' +
    '   \x1B[?25h\n' +
    '\x1B[?25h\x1B[?25l\n' +
    '\x1B[?25h\x1B[?25l💡 \x1B[38;5;244mThe troubleshooting documentation can help to narrow down the cause of the errors:\x1B[0m\n' +
    '\x1B[?25h\x1B[?25l   \x1B[?25l\x1B[38;5;244mhttps://docs.sourcegraph.com/batch_changes/references/troubleshooting\x1B[0m\n' +
    '   \x1B[?25h\n' +
    '\x1B[?25h',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Failed to create batch change for this release, continuing with announcement
✨  Done in 160.60s.
```

**Comment by eseliger** [comment]
What version of src-cli are you using? We've fixed a bug recently that was something along these lines.

**Comment by kevinwojo** [comment]
```
% src version
Current version: 3.35.0
Recommended version: 3.36.2 or later
```

**Comment by eseliger** [comment]
Seems like 3.35.3 has the fix, can you try upgrading to latest?
