### ISSUE TITLE
search panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3579]
Reported by https://app.hubspot.com/contacts/2762526/company/561806411 

```go
22:53:26           frontend | panic: runtime error: invalid memory address or nil pointer dereference
22:53:26           frontend | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf8008d]
22:53:26           frontend | goroutine 2353373 [running]:
22:53:26           frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.zoektSearchHEAD(0x2116900, 0xc005de1b00, 0xc00099dda0, 0xc00f5f5800, 0x7a7, 0x900, 0x4e2c00, 0x2116bc0, 0xc0022be740, 0x0, ...)
22:53:26           frontend |     /buildkite/builds/buildkite-agent-59b9b57b47-w4jzx-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:471 +0x63d
22:53:26           frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.searchFilesInRepos.func4(0xc00f32a894, 0xc005de1920, 0xc00f5f5800, 0x7a7, 0x900, 0xc00b16f110, 0xc00f32a8a0, 0xc00948f300, 0xc005de1a10, 0xc00b16f120, ...)
22:53:26           frontend |     /buildkite/builds/buildkite-agent-59b9b57b47-w4jzx-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:857 +0x2a7
22:53:26           frontend | created by github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.searchFilesInRepos
22:53:26           frontend |     /buildkite/builds/buildkite-agent-59b9b57b47-w4jzx-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:851 +0x960
22:53:26            symbols | received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: EOF
22:53:26           frontend | Terminating frontend
frontend died. Shutting down...
22:53:26              nginx | Terminating nginx
```

**Comment by ijsnow** [comment]
There was a commit that changed the line where the panic is being thrown that was introduced in 3.3 https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/90de6710963f7918bd7d6543e083a9acf125d97d

**Comment by ijt** [comment]
How do you reproduce this?

**Comment by nicksnyder** [comment]
I would start by looking at the stack trace and asking yourself how that value could be nil

**Comment by slimsag** [comment]
This regression was introduced by https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/90de6710963f7918bd7d6543e083a9acf125d97d#diff-83802ba2eb1d04e70858db65e54338d8R474 in specific.

When `searcher.Search` returns an error, it returns a nil response. We are then trying to access `resp.FileCount` and `resp.MatchCount` which panics because `resp` is `nil`.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.3.0/-/blob/cmd/frontend/graphqlbackend/textsearch.go#L471

**Comment by ijt** [comment]
I broke this. Fixing it.
