### ISSUE TITLE
Panic in zoekt.PartitionRepos

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#38105]
- Commit 28b5531c59dcb6eb6fece289de4783fadab0e1c6 (on a branch)
- Nearest main commit 2ed5bfc6a3ebccda0699270acdd6f04e833b1861

cc @sourcegraph/search-core in case you'd like to look into this.

```
[       frontend] panic: runtime error: invalid memory address or nil pointer dereference
[       frontend] [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x106cedb00]
[       frontend] goroutine 3653 [running]:
[       frontend] github.com/sourcegraph/sourcegraph/internal/search/zoekt.PartitionRepos({0x1087ef1b0, 0x14003346b00}, {0x1087fc418, 0x140037079c0}, {0x14000298e88, 0x1, 0x1}, {0x1087f2b50, 0x140036a1770}, {0x107670d25, ...}, ...)
[       frontend] 	/Users/chrismwendt/github.com/sourcegraph/sourcegraph/internal/search/zoekt/indexed_search.go:218 +0x640
[       frontend] github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.(*repoPagerJob).Run.func2(0x140037107d0)
[       frontend] 	/Users/chrismwendt/github.com/sourcegraph/sourcegraph/internal/search/job/jobutil/repo_pager_job.go:74 +0x114
[       frontend] github.com/sourcegraph/sourcegraph/internal/search/repos.(*Resolver).Paginate(0x1400238c8c0, {0x1087ef258, 0x14002301980}, 0x14003893d78)
[       frontend] 	/Users/chrismwendt/github.com/sourcegraph/sourcegraph/internal/search/repos/repos.go:83 +0x470
[       frontend] github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.(*repoPagerJob).Run(0x140036ad500, {0x1087ef258, 0x14002301770}, {{0x10882ded0, 0x14001d901f8}, {0x1087f2b50, 0x140036a1770}, 0x140024abec0, {0x10882c968, 0x140015beba0}}, ...)
[       frontend] 	/Users/chrismwendt/github.com/sourcegraph/sourcegraph/internal/search/job/jobutil/repo_pager_job.go:93 +0x368
[       frontend] github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.(*ParallelJob).Run.func2()
[       frontend] 	/Users/chrismwendt/github.com/sourcegraph/sourcegraph/internal/search/job/jobutil/combinators.go:129 +0xa4
[       frontend] github.com/sourcegraph/sourcegraph/lib/errors.(*Group).Go.func1()
[       frontend] 	/Users/chrismwendt/github.com/sourcegraph/sourcegraph/lib/errors/group.go:25 +0x90
[       frontend] created by github.com/sourcegraph/sourcegraph/lib/errors.(*Group).Go
[       frontend] 	/Users/chrismwendt/github.com/sourcegraph/sourcegraph/lib/errors/group.go:22 +0xc0
```

**Comment by keegancsmith** [comment]
cc @camdencheek

**Comment by camdencheek** [comment]
Looks like another missing logger. I can push a fix 👍

**Comment by camdencheek** [comment]
Seems to have been introduced by https://github.com/sourcegraph/sourcegraph/pull/36457

**Comment by camdencheek** [comment]
I don't see an obvious place that a logger is missed. cc @sourcegraph/dev-experience
