### ISSUE TITLE
package.json scripts don't run on Windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#400]
Windows requires `set ENV_VAR_NAME=value`. *Nix allows `ENV_VAR_NAME=value`. In package.json:

```jsonc
// ...
"test": "TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\"}' mocha --require ts-node/register --require src/util/long-stack-traces.ts --timeout 10000 'src/**/*.test.ts?(x)'",
"cover": "TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\"}' nyc --require ts-node/register mocha --timeout 10000 './src/**/*.test.ts?(x)'",
// ...
```

**Comment by felixfbecker** [comment]
This should be fixed in https://github.com/sourcegraph/sourcegraph/commit/2f1338cc6b7291f11729bcf654d5d02a2ef4d52d. @JoshuaKGoldberg could you check if the scripts work now on Windows?

**Comment by JoshuaKGoldberg** [comment]
Almost:

```
> @sourcegraph/webapp@1.10.1 build C:\Code\sourcegraph
> cross-env NODE_OPTIONS="--max_old_space_size=4096" gulp build

[07:13:12] Requiring external module ts-node/register
[07:13:15] Using gulpfile C:\Code\sourcegraph\gulpfile.ts
[07:13:15] Starting 'build'...
[07:13:15] Starting 'sass'...
[07:13:15] Starting 'schema'...
[07:13:15] Starting 'graphQLTypes'...
[07:13:18] Finished 'graphQLTypes' after 3.26 s
[07:13:18] Finished 'sass' after 3.53 s
[07:13:25] Finished 'schema' after 11 s
[07:13:25] Starting 'webpack'...
[07:13:25] Starting 'typescript'...
[07:13:25] 'typescript' errored after 160 ms
[07:13:25] Error: spawn C:\Code\sourcegraph/node_modules/.bin/tsc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[07:13:25] 'build' errored after 11 s
[07:13:25] The following tasks did not complete: webpack
[07:13:25] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sourcegraph/webapp@1.10.1 build: `cross-env NODE_OPTIONS="--max_old_space_size=4096" gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sourcegraph/webapp@1.10.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dioge\AppData\Roaming\npm-cache\_logs\2018-10-16T11_13_25_975Z-debug.log

C:\Code\sourcegraph (master -> origin) (@sourcegraph/webapp@1.10.1)
```

**Comment by felixfbecker** [comment]
Does it work after https://github.com/sourcegraph/sourcegraph/commit/91a8bf04fc09ea03f923498745a2fc84cfe3d9cd ?
