### ISSUE TITLE
frontend panics when trying to start a fresh local instance in enterprise mode

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4123]
- **Sourcegraph version:** `master`

#### Steps to reproduce:

1. Clean local caches:
```
$ yarn cache clean; rm -rf node_modules web/node_modules;
$ psql --dbname thorstenball -c 'DROP DATABASE sourcegraph;'
$ rm -rf ~/.sourcegraph
$ createdb --owner=sourcegraph --encoding=UTF8 --template=template0 sourcegraph
```
2. Start up `./enterprise/dev/start.sh`

#### Expected behavior:

Sourcegraph boots up

#### Actual behavior:

```
$ ./enterprise/dev/start.sh
Installing enterprise web dependencies...
[... yarn/gulp/go output ...]

Starting all binaries...

10:47:46                  watch | Running enterprise/changewatch.sh
10:47:46                symbols | Building the /Users/thorstenball/work/sourcegraph/.bin/symbols executable...
10:47:46                docsite | # Doc site is available at http://localhost:5080
10:47:47                  watch | Using chokidar.
10:47:48         syntect_server | Configured for production.
10:47:48         syntect_server |     => address: 0.0.0.0
10:47:48         syntect_server |     => port: 9238
10:47:48         syntect_server |     => log: critical
10:47:48         syntect_server |     => workers: 8
10:47:48         syntect_server |     => secret key: provided
10:47:48         syntect_server |     => limits: forms = 32KiB, json* = 10MiB
10:47:48         syntect_server |     => keep-alive: disabled
10:47:48         syntect_server |     => tls: disabled
10:47:48         syntect_server | Rocket has launched from http://0.0.0.0:9238
10:47:48                    web | [10:47:48] Requiring external module ts-node/register
10:47:48               keycloak | Waiting for Keycloak server to be ready...
10:47:54                symbols | Building the /Users/thorstenball/work/sourcegraph/.bin/symbols executable... done
10:47:54                symbols | Building the ctags Docker image...
10:47:54                symbols | sha256:1bf76a5c53d0d57955e487756b0c6e4ed28d695f9d2e5593afa112bc6719bcf6
10:47:54                symbols | Building the ctags Docker image... done
10:47:55                    web | Using mode development
10:47:55     management-console | t=2019-05-20T10:47:55+0200 lvl=info msg="management-console: listening" addr=127.0.0.1:2633
10:47:55     management-console | 2019/05/20 10:47:55 Generating and using self-signed TLS cert/key
10:47:55                    web | [10:47:55] Using gulpfile ~/work/sourcegraph/gulpfile.ts
10:47:55                    web | [10:47:55] Starting 'watch'...
10:47:55                    web | [10:47:55] Starting 'schema'...
10:47:55                    web | [10:47:55] Starting 'graphQLTypes'...
10:47:56                    web | [10:47:56] Finished 'schema' after 803 ms
10:47:57                    web | [10:47:57] Finished 'graphQLTypes' after 2.36 s
10:47:57                    web | [10:47:57] Starting 'watchSchema'...
10:47:57                    web | [10:47:57] Starting 'watchGraphQLTypes'...
10:47:57                    web | [10:47:57] Starting 'webpackDevServer'...
10:47:58                    web | [10:47:58] Starting 'phabricator'...
10:47:58                    web | [10:47:58] Finished 'webpackDevServer' after 492 ms
10:47:58                    web | [10:47:58] Finished 'phabricator' after 46 ms
10:47:58                    web | [10:47:58] Starting 'watchPhabricator'...
10:48:02                    web | WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
10:48:02                    web | You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
10:48:02                    web |   npm install --save core-js@2    npm install --save core-js@3
10:48:02                    web |   yarn add core-js@2              yarn add core-js@3
10:48:03               searcher | received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:03           query-runner | 2019/05/20 10:48:03 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:03           github-proxy | 2019/05/20 10:48:03 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:03           repo-updater | 2019/05/20 10:48:03 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:05              gitserver | 2019/05/20 10:48:05 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:05               searcher | received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:05           query-runner | 2019/05/20 10:48:05 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:05           github-proxy | 2019/05/20 10:48:05 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:05           repo-updater | 2019/05/20 10:48:05 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:06      zoekt-indexserver | 2019/05/20 10:48:06 POST http://localhost:3090/.internal/repos/list giving up after 5 attempts
10:48:07              gitserver | 2019/05/20 10:48:07 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:08              gitserver | 2019/05/20 10:48:08 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:08               searcher | received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:08           query-runner | 2019/05/20 10:48:08 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:08           github-proxy | 2019/05/20 10:48:08 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:08           repo-updater | 2019/05/20 10:48:08 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:10              gitserver | 2019/05/20 10:48:10 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:10              gitserver | 2019/05/20 10:48:10 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:11                symbols | received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:11              gitserver | 2019/05/20 10:48:11 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:12               searcher | received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:12           query-runner | 2019/05/20 10:48:12 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:12           github-proxy | 2019/05/20 10:48:12 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:12           repo-updater | 2019/05/20 10:48:12 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:12               searcher | received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:12           query-runner | 2019/05/20 10:48:12 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:12           github-proxy | 2019/05/20 10:48:12 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:12           repo-updater | 2019/05/20 10:48:12 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:13               searcher | received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:13           query-runner | 2019/05/20 10:48:13 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:13           github-proxy | 2019/05/20 10:48:13 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:13              gitserver | 2019/05/20 10:48:13 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:13           repo-updater | 2019/05/20 10:48:13 received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:14                symbols | received error during background config update, err: unable to fetch new configuration: Post http://localhost:3090/.internal/configuration: dial tcp [::1]:3090: connect: connection refused
10:48:16               frontend | panic: deadlock detected: you have called conf.Get or conf.Watch before the frontend has been initialized (you may need to use a goroutine)
10:48:16               frontend | goroutine 38 [running]:
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000ef720)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:141 +0x2b8
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Watch(0xc00005f140, 0x237ab18)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:111 +0xb8
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Watch(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:94
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/trace.init.0.func1()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/trace/httptrace.go:59 +0x3a
10:48:16               frontend | created by github.com/sourcegraph/sourcegraph/pkg/trace.init.0
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/trace/httptrace.go:58 +0x117
10:48:16               frontend | goroutine 1 [select]:
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000ef720)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:131 +0x159
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).LastValid(0xc0000ef720, 0x0)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:37 +0x38
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Get(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:69
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Get(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:47
10:48:16               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/db.(*ExternalServicesStore).Create(0xc0008c8180, 0x2548560, 0xc000052108, 0xc0004de070, 0xc00021e580, 0x149)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/cmd/frontend/db/external_services.go:189 +0x47
10:48:16               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.handleConfigOverrides()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/cmd/frontend/internal/cli/config.go:117 +0x8ae
10:48:16               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.Main(0x0, 0x0)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/cmd/frontend/internal/cli/serve_cmd.go:100 +0xd4
10:48:16               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/shared.Main()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/cmd/frontend/shared/frontend.go:19 +0x2e
10:48:16               frontend | main.main()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/main.go:56 +0x96
10:48:16               frontend | goroutine 61 [select]:
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000ef720)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:131 +0x159
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Watch(0xc00005f140, 0x237a058)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:111 +0xb8
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Watch(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:94
10:48:16               frontend | github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/githuboauth.init.0.func1()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/githuboauth/config.go:13 +0x3e
10:48:16               frontend | created by github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/githuboauth.init.0
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/githuboauth/config.go:12 +0x35
10:48:16               frontend | goroutine 62 [select]:
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000ef720)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:131 +0x159
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Watch(0xc00005f140, 0x237a088)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:111 +0xb8
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Watch(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:94
10:48:16               frontend | github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/gitlaboauth.init.0.func1()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/gitlaboauth/config.go:16 +0x3e
10:48:16               frontend | created by github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/gitlaboauth.init.0
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/gitlaboauth/config.go:15 +0x35
10:48:16               frontend | goroutine 48 [select]:
10:48:16               frontend | go.opencensus.io/stats/view.(*worker).start(0xc0005b52c0)
10:48:16               frontend |       /Users/thorstenball/code/go/pkg/mod/go.opencensus.io@v0.19.0/stats/view/worker.go:147 +0xdd
10:48:16               frontend | created by go.opencensus.io/stats/view.init.0
10:48:16               frontend |       /Users/thorstenball/code/go/pkg/mod/go.opencensus.io@v0.19.0/stats/view/worker.go:29 +0x57
10:48:16               frontend | goroutine 67 [select]:
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000ef720)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:131 +0x159
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Watch(0xc00005f140, 0x2379d90)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:111 +0xb8
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Watch(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:94
10:48:16               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/internal/auth/userpasswd.init.1.func1()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/cmd/frontend/internal/auth/userpasswd/config_watch.go:11 +0x3a
10:48:16               frontend | created by github.com/sourcegraph/sourcegraph/cmd/frontend/internal/auth/userpasswd.init.1
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/cmd/frontend/internal/auth/userpasswd/config_watch.go:10 +0x35
10:48:16               frontend | goroutine 63 [select]:
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000ef720)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:131 +0x159
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Watch(0xc00005f140, 0x237a0a8)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:111 +0xb8
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Watch(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:94
10:48:16               frontend | github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/httpheader.init.1.func1()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/httpheader/config_watch.go:11 +0x3a
10:48:16               frontend | created by github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/httpheader.init.1
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/httpheader/config_watch.go:10 +0x35
10:48:16               frontend | goroutine 64 [select]:
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000ef720)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:131 +0x159
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Watch(0xc00005f140, 0x237a0e8)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:111 +0xb8
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Watch(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:94
10:48:16               frontend | github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/openidconnect.init.1.func1()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/openidconnect/config_watch.go:30 +0x3a
10:48:16               frontend | created by github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/openidconnect.init.1
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/openidconnect/config_watch.go:29 +0x35
10:48:16               frontend | goroutine 65 [select]:
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000ef720)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/store.go:131 +0x159
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Watch(0xc00005f140, 0x237a118)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:111 +0xb8
10:48:16               frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Watch(...)
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/pkg/conf/client.go:94
10:48:16               frontend | github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/saml.init.1.func1()
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/saml/config_watch.go:31 +0x3a
10:48:16               frontend | created by github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/auth/saml.init.1
10:48:16               frontend |       /Users/thorstenball/work/sourcegraph/enterprise/cmd/frontend/auth/saml/config_watch.go:30 +0x35
10:48:16               frontend | goroutine 100 [select]:
10:48:16               frontend | database/sql.(*DB).connectionOpener(0xc000166000, 0x2548520, 0xc0005b4080)
10:48:16               frontend |       /Users/thorstenball/.asdf/installs/golang/1.12.4/go/src/database/sql/sql.go:1000 +0xe8
10:48:16               frontend | created by database/sql.OpenDB
10:48:16               frontend |       /Users/thorstenball/.asdf/installs/golang/1.12.4/go/src/database/sql/sql.go:670 +0x15e
10:48:16               frontend | goroutine 101 [select]:
10:48:16               frontend | database/sql.(*DB).connectionResetter(0xc000166000, 0x2548520, 0xc0005b4080)
10:48:16               frontend |       /Users/thorstenball/.asdf/installs/golang/1.12.4/go/src/database/sql/sql.go:1013 +0xfb
10:48:16               frontend | created by database/sql.OpenDB
10:48:16               frontend |       /Users/thorstenball/.asdf/installs/golang/1.12.4/go/src/database/sql/sql.go:671 +0x194
10:48:16               frontend | Terminating frontend
10:48:16              gitserver | Terminating gitserver
10:48:16           query-runner | Terminating query-runner
10:48:16           repo-updater | Terminating repo-updater
10:48:16                symbols | Terminating symbols
10:48:16                docsite | Terminating docsite
10:48:16               searcher | Terminating searcher
10:48:16                  nginx | Terminating nginx
10:48:16           github-proxy | Terminating github-proxy
10:48:16                  watch | Terminating watch
10:48:16                    web | Terminating web
10:48:16      zoekt-indexserver | Terminating zoekt-indexserver
10:48:16     management-console | Terminating management-console
10:48:16 management-console-web | Terminating management-console-web
10:48:17               keycloak | keycloak
10:48:17               keycloak | Terminating keycloak
10:48:19         syntect_server | Terminating syntect_server
10:48:19        zoekt-webserver | Terminating zoekt-webserver
goreman: exit status 2
~
```

**Comment by mrnugget** [comment]
I dug into this a little bit and it looks like a proper deadlock: every service is waiting for frontend to boot up and frontend itself is waiting in this call https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/cli/config.go#L117:16

A little bit of git blame/log lead me to this commit: https://github.com/sourcegraph/sourcegraph/commit/507371f2eadc24cecaccb8a129dd80c5a45631ef

If I revert that commit, everything boots up without any problems. So I dug into the commit and it turns out that if I move this call to `handleConfigOverrides` back to its original place, `frontend` boots up again: https://github.com/sourcegraph/sourcegraph/commit/507371f2eadc24cecaccb8a129dd80c5a45631ef#diff-6cc202581c2d5909ef0338c42176f3bcR100

I'm not too good with the details here (the bootup process is rather complicated to dissect at first glance) -- maybe something rings a bell here for you @slimsag?

**Comment by mrnugget** [comment]
@slimsag I gave it a shot in https://github.com/sourcegraph/sourcegraph/pull/4126 -- this fixes the deadlock (and the panic) but I'm not sure whether I completely understand the intention behind the original change that moved the call to `handleConfigOverrides`

**Comment by sqs** [comment]
I am also experiencing this problem on a fresh install. Thanks for looking into the fix, @mrnugget.

**Comment by slimsag** [comment]
Apologies for this, will fix. It only affects our dev environments and users who specify the new `*_CONFIG_FILE` override environment variables.

#4126 was a good attempt but unfortunately not correct (this code is a little too complex).
