### ISSUE TITLE
JetBrains: "Open Revision Diff" feature doesn't work

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#43183]
When you right-click a commit in your VCS Log, and choose "Open Revision Diff in Sourcegraph Web", it doesn't open the external browser and throws this error message:

```
java.lang.RuntimeException: Missing remote URL for commit uri.
	at com.sourcegraph.git.CommitViewUriBuilder.build(CommitViewUriBuilder.java:19)
	at com.sourcegraph.website.OpenRevisionAction.actionPerformed(OpenRevisionAction.java:81)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
```

Also [1-min Loom demo](https://www.loom.com/share/5601ce834a1e4be6b2715bc5ffba7866)

Expectation: an external browser tab should open with a Sourcegraph page that shows the selected commit as a diff.

/cc @muratsu @jjinnii @ryankscott

**Comment by vdavid** [comment]
Also, a bit related: currently, this feature doesn't open the right file (and probably just errors) if you have a project open that has **multiple repos** if the project root is not a repo (example: my own setup for Sourcegraph).
