### ISSUE TITLE
e2e tests failing due to `TypeError: Converting circular structure to JSON`

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4326]
- **Sourcegraph version:** `master`
- **Platform information:** macOS, Google Chrome

#### Steps to reproduce:

1. Startup `./enterprise/dev/start.sh
2. Run `cd web && yarn run test-e2e`

#### Expected behavior:

Tests running/passing

#### Actual behavior:

Everything fails and the output is spammed with the following message:

```
  console.error ../node_modules/jest-jasmine2/build/jasmine/Env.js:290
    TypeError: Converting circular structure to JSON
        at JSON.stringify (<anonymous>)
        at Page.page.on.message (/Users/thorstenball/work/sourcegraph/web/src/e2e/index.e2e.test.tsx:82:88)
        at Page.emit (events.js:189:13)
        at Page._addConsoleMessage (/Users/thorstenball/work/sourcegraph/node_modules/puppeteer/lib/Page.js:583:10)
        at Page._onConsoleAPI (/Users/thorstenball/work/sourcegraph/node_modules/puppeteer/lib/Page.js:505:10)
        at CDPSession.Page.client.on.event (/Users/thorstenball/work/sourcegraph/node_modules/puppeteer/lib/Page.js:121:57)
        at CDPSession.emit (events.js:189:13)
        at CDPSession._onMessage (/Users/thorstenball/work/sourcegraph/node_modules/puppeteer/lib/Connection.js:200:12)
        at Connection._onMessage (/Users/thorstenball/work/sourcegraph/node_modules/puppeteer/lib/Connection.js:112:17)
        at WebSocketTransport._ws.addEventListener.event (/Users/thorstenball/work/sourcegraph/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
        at WebSocket.onMessage (/Users/thorstenball/work/sourcegraph/node_modules/ws/lib/event-target.js:120:16)
        at WebSocket.emit (events.js:189:13)
        at Receiver.receiverOnMessage (/Users/thorstenball/work/sourcegraph/node_modules/ws/lib/websocket.js:741:20)
        at Receiver.emit (events.js:189:13)
        at Receiver.dataMessage (/Users/thorstenball/work/sourcegraph/node_modules/ws/lib/receiver.js:417:14)
        at Receiver.getData (/Users/thorstenball/work/sourcegraph/node_modules/ws/lib/receiver.js:347:17)
        at Receiver.startLoop (/Users/thorstenball/work/sourcegraph/node_modules/ws/lib/receiver.js:133:22)
        at Receiver._write (/Users/thorstenball/work/sourcegraph/node_modules/ws/lib/receiver.js:69:10)
        at doWrite (_stream_writable.js:410:12)
        at writeOrBuffer (_stream_writable.js:394:5)
        at Receiver.Writable.write (_stream_writable.js:294:11)
        at Socket.socketOnData (/Users/thorstenball/work/sourcegraph/node_modules/ws/lib/websocket.js:816:35)
        at Socket.emit (events.js:189:13)
        at addChunk (_stream_readable.js:284:12)
        at readableAddChunk (_stream_readable.js:265:11)
        at Socket.Readable.push (_stream_readable.js:220:10)
        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I can fix it, if I change this:

https://github.com/sourcegraph/sourcegraph/blob/914bc402ead3d4d1d273e53fff28bd333c720b1f/web/src/e2e/index.e2e.test.tsx#L82

Into this:

```javascript
            page.on('console', message => console.log('Browser console message:', message))
```

Then I see what was being logged:

```
  console.log src/e2e/index.e2e.test.tsx:83
    Browser console message: ConsoleMessage {
      _type: 'info',
      _text:
       '%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold',
      _args:
       [ JSHandle {
           _context: [ExecutionContext],
           _client: [CDPSession],
           _remoteObject: [Object],
           _disposed: false },
         JSHandle {
           _context: [ExecutionContext],
           _client: [CDPSession],
           _remoteObject: [Object],
           _disposed: false } ],
      _location:
       { url:
          'webpack-internal:///../node_modules/react-dom/cjs/react-dom.development.js',
         lineNumber: 3879,
         columnNumber: 46 } }
```

The thing is, though:
1. I _do_ have the React Devtools installed
2. Why do I need to have them to run the e2e tests?

**Comment by felixfbecker** [comment]
That fix sounds good to me, although it is quite a few lines per log message which could bloat the log output. A solution would be to use `util.inspect()` with options for the `depth` and putting it on a single line maybe.
Wanna do a PR?

> I do have the React Devtools installed

But not in e2e tests, which runs Chromium without a user profile (i.e. no extensions).

> Why do I need to have them to run the e2e tests?

You don't need to, it's just a warning :)

**Comment by mrnugget** [comment]
> You don't need to, it's just a warning :)

Hehe, then how do you run the e2e tests locally? I thought you're using some way to enable the devtools in Chromium so it works.

**Comment by felixfbecker** [comment]
We're using Puppeteer, which launches a headless Chromium in remote debugging mode and controls it through IPC. It's not coupled to React in any way :)

https://github.com/GoogleChrome/puppeteer

**Comment by mrnugget** [comment]
I know. I mean: how do _you_ personally run the tests locally? Are e2e tests broken for everybody due to that warning? If not, why are they broken for me?

**Comment by felixfbecker** [comment]
I run them the same as you. This is probably a recent regression, maybe caused by a dependency upgrade that included a circular reference in a log that wasn't there before.

**Comment by mrnugget** [comment]
> I run them the same as you. This is probably a recent regression, maybe caused by a dependency upgrade that included a circular reference in a log that wasn't there before.

Okay, now I get it, thanks for the explanation :)



> That fix sounds good to me, although it is quite a few lines per log message which could bloat the log output. A solution would be to use `util.inspect()` with options for the `depth` and putting it on a single line maybe.
> Wanna do a PR?

I'll give it a shot, yep
