### ISSUE TITLE
FE scale audit: Code graph uploads crash on large repos

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#43448]
As part of the [FE scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0), we noticed that code graph uploads inside the repo page are crashing and becoming unable to use on larger repos:

```
react_devtools_backend.js:4026 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Yi (react-dom.production.min.js:264:247)
    at Qu (react-dom.production.min.js:179:340)
    at Object.queryConnection (CodeIntelUploadsPage.tsx:259:29)
    at c.project (FilteredConnection.tsx:270:30)
    at c._next (switchMap.ts:28:27)
    at c.next (Subscriber.ts:49:18)
    at s._tryNext (scan.ts:55:26)
```

This can be reproduced on dotcom, e.g. on the VS Code repo: https://sourcegraph.com/github.com/microsoft/vscode/-/code-graph/uploads

Here is a screenshot of the issue: https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=135%3A3

**Note: The error seems similar to #43335, so maybe a it's the same fix?**

**Comment by philipp-spiess** [comment]
It seems like the React error is unrelated to the fact that no entries show. We do not get any uploads from the gql backend so maybe the empty screen is expected here?

<img width="1152" alt="Screenshot 2022-11-02 at 14 27 33" src="https://user-images.githubusercontent.com/458591/199501632-4fa4694a-5cd7-4baa-a189-d8546a758a47.png">
