### ISSUE TITLE
Bug Report: Panic occurred when getting repository languages from the GraphQL Api 

### ISSUE THREAD

**Issue by javigomez** [sourcegraph/sourcegraph#44033]
- **Sourcegraph version:** 4.1.2 latest
- **Platform information:** AWS

#### Steps to reproduce:

1. Go to Api Explorer
2. Perform this query
<img width="493" alt="Screenshot 2022-11-07 at 16 55 39" src="https://user-images.githubusercontent.com/1375475/200355866-3732fa9c-b7c6-4dde-b8e2-69b334501f17.png">

#### Expected behavior:
Returns a list of programming languages used in the repository

#### Actual behavior:
you get a Golang Panic
<img width="816" alt="Screenshot 2022-11-07 at 16 55 31" src="https://user-images.githubusercontent.com/1375475/200356020-3df40536-71f4-471b-a400-ea0df10821c5.png">

sometimes you get just an empty list of languages:
<img width="747" alt="Screenshot 2022-11-07 at 17 01 56" src="https://user-images.githubusercontent.com/1375475/200356912-dc514f23-409b-4c79-9359-85f7000b2242.png">

This was working for sure in [versions](https://github.com/sourcegraph/sourcegraph/releases/tag/v3.43.2) because I have seen the error once I moved to version 4.x

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @jplahn @ryphil/search-core

**Comment by amberfurbush0317** [comment]
I was able to replicate this issue as well: 

Appears the error is coming from here: 

https://sourcegraph.com/github.com/sourcegraphtest/golang-go2/-/blob/src/runtime/panic.go?L59:38&subtree=true

`var memoryError = error(errorString("invalid memory address or nil pointer dereference"))`

**Comment by gl-srgr** [comment]
This looks like a frontend issue, not search-core. I have a PR with a fix but will request reviews from frontend. Here's the stack trace:

```
[       frontend] graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
[       frontend] goroutine 3543 [running]:
[       frontend] github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0x10ab5fb18, {0x10903e358, 0x1400243b0b0}, {0x108a9da20, 0x10aad3020})
[       frontend] 	/Users/gary/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/log/log.go:21 +0x60
[       frontend] github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1()
[       frontend] 	/Users/gary/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:187 +0x94
[       frontend] panic({0x108a9da20, 0x10aad3020})
[       frontend] 	/usr/local/go/src/runtime/panic.go:890 +0x26c
[       frontend] github.com/sourcegraph/sourcegraph/cmd/frontend/backend.NewRepos({0x0, 0x0}, {0x109082698, 0x140011e2270}, {0x109086af0, 0x140001a1680})
[       frontend] 	/Users/gary/Documents/Work/sourcegraph/cmd/frontend/backend/repos.go:52 +0x54
[       frontend] github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*GitCommitResolver).Languages(0x140037101b0, {0x10903e358, 0x1400243b0b0})
[       frontend] 	/Users/gary/Documents/Work/sourcegraph/cmd/frontend/graphqlbackend/git_commit.go:286 +0x118
[       frontend] reflect.Value.call({0x108f596a0, 0x140037101b0, 0x3e13}, {0x107c9b2f1, 0x4}, {0x140037007b0, 0x1, 0x1})
[       frontend] 	/usr/local/go/src/reflect/value.go:584 +0x890
[       frontend] reflect.Value.Call({0x108f596a0, 0x140037101b0, 0x3e13}, {0x140037007b0, 0x1, 0x1})
[       frontend] 	/usr/local/go/src/reflect/value.go:368 +0x74
[       frontend] github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2(0x140036b5080, {0x10903e358, 0x1400243b0b0}, 0x14003700798, 0x14003707040, 0x1400388dd78, {0x10903e358, 0x1400243b0b0})
[       frontend] 	/Users/gary/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:211 +0x55c
[       frontend] github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection({0x10903e358, 0x1400243b0b0}, 0x140036b5080, 0x14002138000, 0x14003707040, 0x14003700798, 0x1)
[       frontend] 	/Users/gary/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:231 +0x1e8
[       frontend] github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections.func1(0x14003707040)
[       frontend] 	/Users/gary/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:81 +0x21c
[       frontend] created by github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections
[       frontend] 	/Users/gary/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.3.0/internal/exec/exec.go:77 +0x6b8
[       frontend] context: context.Background.WithValue(type *http.contextKey, val <not Stringer>).WithValue(type *http.contextKey, val 127.0.0.1:3082).WithCancel.WithCancel.WithValue(type policy.key, val <not Stringer>).WithValue(type opentracing.contextKey, val <not Stringer>).WithValue(type opentracing.contextKey, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val <not Stringer>).WithValue(type requestclient.clientKey, val <not Stringer>).WithValue(type trace.traceContextKeyType, val <not Stringer>).WithValue(type trace.traceContextKeyType, val <not Stringer>).WithValue(type trace.traceContextKey, val <not Stringer>).WithValue(type actor.contextKey, val Actor UID 1, internal false).WithValue(type featureflag.flagContextKey, val <not Stringer>).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type mux.contextKey, val <not Stringer>).WithValue(type trace.key, val unknown).WithValue(type trace.key, val <not Stringer>).WithValue(type trace.key, val # Type queries here, with completion, validation, and hovers.
```

**Comment by gl-srgr** [comment]
Posted to repo-management for a code review

**Comment by stefanhengl** [comment]
@gl-srgr Is this solved?

**Comment by gl-srgr** [comment]
@stefanhengl Yes
