### ISSUE TITLE
Panic on sourcegraph.com: repo field is an invalid regex

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#46761]
Panic happening to due an invariant being broken. This was recently introduced code:

https://github.com/sourcegraph/sourcegraph/blob/c6c289a75e99a1f0aef7dc91b28f8bdea88c0bb4/internal/search/query/types.go#L150-L155

Introduced in https://github.com/sourcegraph/sourcegraph/pull/46260

https://console.cloud.google.com/errors/CO-w5_yv9LbeOw?project=sourcegraph-dev&time=P30D

```
goroutine 386250078 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/sourcegraph/sourcegraph/internal/trace.loggingRecoverer.func1.1()
	github.com/sourcegraph/sourcegraph/internal/trace/httptrace.go:282 +0x1c6
panic({0x2d37d00, 0xc0267e7160})
	runtime/panic.go:884 +0x212
github.com/sourcegraph/sourcegraph/internal/search/query.Q.Repositories.func1({0xc07bc08a68, 0x10}, 0xc8?, {0x0, {{0x0, 0xf}, {0x0, 0x24}}})
	github.com/sourcegraph/sourcegraph/internal/search/query/types.go:153 +0x2f4
github.com/sourcegraph/sourcegraph/internal/search/query.VisitField.func1({0xc02489fed8?, 0x13efea0?}, {0xc07bc08a68, 0x10}, 0xd?, {0x0, {{0x0, 0xf}, {0x0, 0x24}}})
	github.com/sourcegraph/sourcegraph/internal/search/query/visitor.go:70 +0xa5
github.com/sourcegraph/sourcegraph/internal/search/query.(*Visitor).Visit(0x0?, {0x95aa150?, 0xc06d10f860?})
	github.com/sourcegraph/sourcegraph/internal/search/query/visitor.go:24 +0x1bd
github.com/sourcegraph/sourcegraph/internal/search/query.VisitParameter(...)
	github.com/sourcegraph/sourcegraph/internal/search/query/visitor.go:51
github.com/sourcegraph/sourcegraph/internal/search/query.VisitField({0xc01abced80?, 0x4?, 0x5?}, {0x3475256?, 0x2?}, 0x0?)
	github.com/sourcegraph/sourcegraph/internal/search/query/visitor.go:68 +0xc5
github.com/sourcegraph/sourcegraph/internal/search/query.Q.Repositories({0xc01abced80?, 0x3?, 0xc06d10f900?})
	github.com/sourcegraph/sourcegraph/internal/search/query/types.go:142 +0x85
github.com/sourcegraph/sourcegraph/internal/search/query.ContainsRefGlobs({0xc01abced80?, 0xc01abced80?, 0x4?})
	github.com/sourcegraph/sourcegraph/internal/search/query/validate.go:529 +0x33
github.com/sourcegraph/sourcegraph/internal/search/query.validateRefGlobs({0xc01abced80, 0x4, 0x4})
	github.com/sourcegraph/sourcegraph/internal/search/query/validate.go:380 +0x2c
github.com/sourcegraph/sourcegraph/internal/search/query.validate.func1(...)
	github.com/sourcegraph/sourcegraph/internal/search/query/validate.go:482
github.com/sourcegraph/sourcegraph/internal/search/query.validate({0xc01abced80, 0x4, 0x4})
	github.com/sourcegraph/sourcegraph/internal/search/query/validate.go:489 +0xc6
github.com/sourcegraph/sourcegraph/internal/search/query.ValidatePlan({0xc00ccc1b30?, 0x1, 0x2?})
	github.com/sourcegraph/sourcegraph/internal/search/query/query.go:139 +0x95
github.com/sourcegraph/sourcegraph/internal/search/query.Pipeline({0xc0267e6d80?, 0x38?, 0x4?})
	github.com/sourcegraph/sourcegraph/internal/search/query/query.go:168 +0x7a
github.com/sourcegraph/sourcegraph/internal/search/client.(*searchClient).Plan(0xc00310f340, {0x95bf0f8?, 0xc054356e40?}, {0xc0c70d3248, 0x2}, 0x0?, {0xc0551b3a40, 0x38}, 0x0, 0x0, ...)
	github.com/sourcegraph/sourcegraph/internal/search/client/client.go:106 +0x2fe
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/search.(*streamHandler).serveHTTP(0xc00310f380, 0xc002105600, 0x3570d2e?, 0x7ff038e6f288?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/search/search.go:108 +0x6f8
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/search.(*streamHandler).ServeHTTP(0xc002105400?, {0x95be400, 0xc07e014f00}, 0xc002105500)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/search/search.go:79 +0x29b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000744d80, {0x95be400, 0xc07e014f00}, 0xc002105300)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006b4780, {0x95be400, 0xc07e014f00}, 0xc002105100)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.(*ServeMux).ServeHTTP(0x95bf088?, {0x95be400, 0xc07e014f00}, 0xc002105100)
	net/http/server.go:2487 +0x149
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/authz.Init.func5.1({0x95be400, 0xc07e014f00}, 0xc002105100)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/authz/init.go:157 +0x422
net/http.HandlerFunc.ServeHTTP(0x95bf0f8?, {0x95be400?, 0xc07e014f00?}, 0xb540740?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/featureflag.Middleware.func1({0x95be400, 0xc07e014f00}, 0xc002105000)
	github.com/sourcegraph/sourcegraph/internal/featureflag/middleware.go:33 +0x33a
net/http.HandlerFunc.ServeHTTP(0x95bf0f8?, {0x95be400?, 0xc07e014f00?}, 0x50?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/actor.AnonymousUIDMiddleware.func1({0x95be400, 0xc07e014f00}, 0xc002104f00)
	github.com/sourcegraph/sourcegraph/internal/actor/http.go:176 +0x1ef
net/http.HandlerFunc.ServeHTTP(0x95bf0f8?, {0x95be400?, 0xc07e014f00?}, 0x7ff038e6f288?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/auth.glob..func2.1({0x95be400, 0xc07e014f00}, 0xc002104f00)
	github.com/sourcegraph/sourcegraph/cmd/frontend/auth/non_public.go:53 +0xcc
net/http.HandlerFunc.ServeHTTP(0x95bf0f8?, {0x95be400?, 0xc07e014f00?}, 0xc002700400?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect.handleOpenIDConnectAuth({0x96182c0?, 0xc002e6dce0?}, {0x95be400, 0xc07e014f00}, 0xc002104f00, {0x95972c0, 0xc001b76540}, 0x0)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go:112 +0x4a3
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect.Middleware.func2.1({0x95be400?, 0xc07e014f00?}, 0x6000103?)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go:64 +0x45
net/http.HandlerFunc.ServeHTTP(0x0?, {0x95be400?, 0xc07e014f00?}, 0xc001bfc570?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/sourcegraphoperator.Middleware.func2.1({0x95be400?, 0xc07e014f00?}, 0xc0079e4500?)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/sourcegraphoperator/middleware.go:45 +0xa8
net/http.HandlerFunc.ServeHTTP(0x95bf0f8?, {0x95be400?, 0xc07e014f00?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml.authHandler({0x96182c0?, 0xc002e6dce0?}, {0x95be400, 0xc07e014f00}, 0xc002104f00, {0x95972c0, 0xc0037a9cb0}, 0x0)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml/middleware.go:74 +0x350
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml.Middleware.func2.1({0x95be400?, 0xc07e014f00?}, 0xc0079e4668?)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml/middleware.go:37 +0x45
net/http.HandlerFunc.ServeHTTP(0x34f3c4e?, {0x95be400?, 0xc07e014f00?}, 0x4afe51?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/httpheader.middleware.func1.1({0x95be400, 0xc07e014f00}, 0xc002104f00)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/httpheader/middleware.go:48 +0xa69
net/http.HandlerFunc.ServeHTTP(0xc0543569c0?, {0x95be400?, 0xc07e014f00?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0x95be400, 0xc07e014f00}, 0xc002104f00)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth/middleware.go:82 +0x482
net/http.HandlerFunc.ServeHTTP(0xc054356870?, {0x95be400?, 0xc07e014f00?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0x95be400, 0xc07e014f00}, 0xc002104f00)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth/middleware.go:82 +0x482
net/http.HandlerFunc.ServeHTTP(0xc054356720?, {0x95be400?, 0xc07e014f00?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0x95be400, 0xc07e014f00}, 0xc002104f00)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth/middleware.go:82 +0x482
net/http.HandlerFunc.ServeHTTP(0xc002104f00?, {0x95be400?, 0xc07e014f00?}, 0x7ff00ac9a558?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.OpenGraphMetadataMiddleware.func1({0x95be400?, 0xc07e014f00}, 0xc0079e5101?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware/opengraph.go:120 +0x10f
net/http.HandlerFunc.ServeHTTP(0x95d1030?, {0x95be400?, 0xc07e014f00?}, 0xc002e6dce0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/session.CookieMiddleware.func1({0x95be400, 0xc07e014f00}, 0xc002104d00)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/session/session.go:315 +0x254
net/http.HandlerFunc.ServeHTTP(0xc0543562a0?, {0x95be400?, 0xc07e014f00?}, 0x5?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi.AccessTokenAuthMiddleware.func1({0x95be400, 0xc07e014f00}, 0xc002104d00)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi/auth.go:273 +0x2bee
net/http.HandlerFunc.ServeHTTP(0x95bf0f8?, {0x95be400?, 0xc07e014f00?}, 0xb540740?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/requestclient.HTTPMiddleware.func1({0x95be400, 0xc07e014f00}, 0xc002104c00)
	github.com/sourcegraph/sourcegraph/internal/requestclient/http.go:47 +0x253
net/http.HandlerFunc.ServeHTTP(0xc002104b00?, {0x95be400?, 0xc07e014f00?}, 0x4?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/deviceid.Middleware.func1({0x95be400, 0xc07e014f00?}, 0xc002104b00)
	github.com/sourcegraph/sourcegraph/internal/deviceid/middleware.go:29 +0x417
net/http.HandlerFunc.ServeHTTP(0x95be400?, {0x95be400?, 0xc07e014f00?}, 0x348061e?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.secureHeadersMiddleware.func1({0x95be400, 0xc07e014f00}, 0x6544206574616572?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/http.go:227 +0x389
net/http.HandlerFunc.ServeHTTP(0x148?, {0x95be400?, 0xc07e014f00?}, 0xc002102dc8?)
	net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0x20?, {0x95be400, 0xc07e014f00}, 0xc002104b00)
	net/http/server.go:2487 +0x149
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.Trace.func1({0x95be400?, 0xc07e014f00?}, 0xc001de0e40?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware/trace.go:27 +0x18e
net/http.HandlerFunc.ServeHTTP(0xc0079e6938?, {0x95be400?, 0xc07e014f00?}, 0xc?)
	net/http/server.go:2109 +0x2f
github.com/gorilla/context.ClearHandler.func1({0x95be400?, 0xc07e014f00?}, 0x0?)
	github.com/gorilla/context@v1.1.1/context.go:141 +0x73
net/http.HandlerFunc.ServeHTTP(0x31a5be0?, {0x95be400?, 0xc07e014f00?}, 0xc?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.healthCheckMiddleware.func1({0x95be400, 0xc07e014f00}, 0x0?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/http.go:128 +0xb4
net/http.HandlerFunc.ServeHTTP(0x412fc2?, {0x95be400?, 0xc07e014f00?}, 0xc054356420?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.BlackHole.func1({0x95be400, 0xc07e014f00}, 0xc054356420?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware/blackhole.go:17 +0x9d
net/http.HandlerFunc.ServeHTTP(0x31ef8c0?, {0x95be400?, 0xc07e014f00?}, 0x6?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.SourcegraphComGoGetHandler.func1({0x95be400?, 0xc07e014f00}, 0xc002104b00)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware/goimportpath.go:48 +0xd7
net/http.HandlerFunc.ServeHTTP(0x40d97f?, {0x95be400?, 0xc07e014f00?}, 0x2?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/auth.ForbidAllRequestsMiddleware.func1({0x95be400, 0xc07e014f00}, 0x0?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/auth/forbid_all.go:19 +0x8e
net/http.HandlerFunc.ServeHTTP(0x40dcc7?, {0x95be400?, 0xc07e014f00?}, 0x4cc701?)
	net/http/server.go:2109 +0x2f
github.com/felixge/httpsnoop.CaptureMetrics.func1({0x95be400?, 0xc07e014f00?})
	github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:29 +0x39
github.com/felixge/httpsnoop.(*Metrics).CaptureMetrics(0xc00ba90af8, {0x95bc9f0, 0xc05c6c69a0}, 0xc0079e6d18)
	github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:84 +0x1ff
github.com/felixge/httpsnoop.CaptureMetricsFn(...)
	github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:39
github.com/felixge/httpsnoop.CaptureMetrics({0x95972c0?, 0xc001b76768?}, {0x95bc9f0, 0xc05c6c69a0}, 0x2c36a20?)
	github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:28 +0x90
github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1({0x95bc9f0, 0xc05c6c69a0}, 0xc002104a00)
	github.com/sourcegraph/sourcegraph/internal/trace/httptrace.go:154 +0x90d
net/http.HandlerFunc.ServeHTTP(0x756f42206c616e6f?, {0x95bc9f0?, 0xc05c6c69a0?}, 0x226b636f4c206c61?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/trace.loggingRecoverer.func1({0x95bc9f0?, 0xc05c6c69a0?}, 0xc054356300?)
	github.com/sourcegraph/sourcegraph/internal/trace/httptrace.go:287 +0x96
net/http.HandlerFunc.ServeHTTP(0x6e6e67?, {0x95bc9f0?, 0xc05c6c69a0?}, 0x673ffc?)
	net/http/server.go:2109 +0x2f
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc002fd00b0, {0x95bc9f0?, 0xc05c6c69a0}, 0xc002104a00)
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.36.4/handler.go:125 +0x134
github.com/sourcegraph/sourcegraph/internal/instrumentation.HTTPMiddleware.func3({0x95bc9f0, 0xc05c6c69a0}, 0xc002104900)
	github.com/sourcegraph/sourcegraph/internal/instrumentation/http.go:53 +0x24e
net/http.HandlerFunc.ServeHTTP(0xc0c70d31f3?, {0x95bc9f0?, 0xc05c6c69a0?}, 0x46c8ce?)
	net/http/server.go:2109 +0x2f
net/http.serverHandler.ServeHTTP({0xc0577946c0?}, {0x95bc9f0, 0xc05c6c69a0}, 0xc002104900)
	net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0547cdb80, {0x95bf0f8, 0xc004521a10})
	net/http/server.go:1991 +0x607
 ```

**Comment by jtibshirani** [comment]
I'll keep an eye on the logs to double-check it's resolved. I think the original refactor (https://github.com/sourcegraph/sourcegraph/pull/46260) might also resolve [this regexp compilation error](https://console.cloud.google.com/errors/detail/CLitvf6e4IbT9gE;time=P30D?project=sourcegraph-dev).
