### ISSUE TITLE
squirrel's java symbol info implementation: slice out of bounds panic when hovering over package name

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#46992]
- **Sourcegraph version:** 5f70f9e75dafc444175bafc5b6a40863a14e82d3
- **Platform information:** local dev and cloud deployments

Reported from https://sourcegraph.slack.com/archives/CMBA8F926/p1674723622234209 and https://sourcegraph.slack.com/archives/C04HCK4K3DL/p1674753044537329.

#### Steps to reproduce:

1. Add the following repository to your Sourcegraph instance: https://github.com/lizhangqu/CoreLink
2. Once cloned, visit the following file: https://github.com/lizhangqu/CoreLink/blob/ad4754115408e86c87f6712a34e3bebf8126114e/packageinfo.java
3. Click on the "corelink" symbol on this line: https://github.com/lizhangqu/CoreLink/blob/ad4754115408e86c87f6712a34e3bebf8126114e/packageinfo.java#L1

#### Expected behavior:

You see the appropriate hover information for that symbol.

#### Actual behavior:

- Your terminal is flooded with the following panic messages:

	```
	[        symbols] ERROR .symbols. shared/main.go:126 recovered from panic {"err": "runtime error: slice bounds out of range [:-3]"}
	[        symbols] ERROR .symbols..http trace/httptrace.go:254 unexpected status code 500 {"route_name": "unknown", "method": "POST", "url": "/symbolInfo", "code": 500, "duration": "12.770875ms", "shouldTrace": false, "x_forwarded_for": "127.0.0.1, 127.0.0.1"}
	```

- When the `grpc` feature flag is enabled, you see the following stack trace:

	```
		panic: runtime error: slice bounds out of range [:-3]
	
		goroutine 688 [running]:
		github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel.getProjectRoot({{{0x140020f8c20, 0x1d}, {0x14001efc6c0, 0x28}, {0x14001667d00, 0x10}}, 0x14001f71d70, {0x14001902000, 0x26, 0x200}, ...})
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel/lang_java.go:680 +0x208
		github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel.(*SquirrelService).getDefInImportsOrCurrentPackageJava(0x140022547e0?, {0x1069f2228, 0x140014b0330}, {{{0x140020f8c20, 0x1d}, {0x14001efc6c0, 0x28}, {0x14001667d00, 0x10}}, 0x14001f71d70, ...}, ...)
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel/lang_java.go:587 +0x1e8
		github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel.(*SquirrelService).getDefJava(0x140022547e0?, {0x1069f2228, 0x140014b0330}, {{{0x140020f8c20, 0x1d}, {0x14001efc6c0, 0x28}, {0x14001667d00, 0x10}}, 0x14001f71da0, ...})
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel/lang_java.go:36 +0x2904
		github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel.(*SquirrelService).getDef(0x1?, {0x1069f2228?, 0x140014b0330?}, {{{0x140020f8c20, 0x1d}, {0x14001efc6c0, 0x28}, {0x14001667d00, 0x10}}, 0x14001f71da0, ...})
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel/service.go:146 +0x6c
		github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel.(*SquirrelService).SymbolInfo(0x1068e0e00?, {0x1069f2228, 0x140014b0330}, {{{0x140020f8c20, 0x1d}, {0x14001efc6c0, 0x28}, {0x14001667d00, 0x10}}, {0x0, ...}})
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/cmd/symbols/squirrel/service.go:73 +0x174
		github.com/sourcegraph/sourcegraph/cmd/symbols/internal/api.(*grpcService).SymbolInfo(0x10d28ce38a815?, {0x1069f2228, 0x140014b0330}, 0x140023af880)
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/cmd/symbols/internal/api/handler_cgo.go:53 +0x218
		github.com/sourcegraph/sourcegraph/cmd/symbols/proto._Symbols_SymbolInfo_Handler.func1({0x1069f2228, 0x140014b0330}, {0x106828d00?, 0x140023af880})
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/cmd/symbols/proto/symbols_grpc.pb.go:197 +0x74
		go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x1069f2228, 0x140014b01e0}, {0x106828d00, 0x140023af880}, 0x140003bb9a0, 0x140018ebf08)
			/Users/ggilmore/dev/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.37.0/interceptor.go:349 +0x3d8
		google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x1069f2228?, 0x140014b01e0?}, {0x106828d00?, 0x140023af880?})
			/Users/ggilmore/dev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1162 +0x60
		github.com/sourcegraph/sourcegraph/internal/grpc.UnaryServerPropagator.func1({0x1069f2228, 0x140014b0180}, {0x106828d00, 0x140023af880}, 0x0?, 0x140023af900)
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/internal/grpc/propagator.go:103 +0x80
		google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x1069f2228?, 0x140014b0180?}, {0x106828d00?, 0x140023af880?})
			/Users/ggilmore/dev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1165 +0x8c
		github.com/sourcegraph/sourcegraph/internal/grpc.UnaryServerPropagator.func1({0x1069f2228, 0x1400194fad0}, {0x106828d00, 0x140023af880}, 0x108b7c101?, 0x140023af900)
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/internal/grpc/propagator.go:103 +0x80
		google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x1069f2228?, 0x1400194fad0?}, {0x106828d00?, 0x140023af880?})
			/Users/ggilmore/dev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1165 +0x8c
		google.golang.org/grpc.chainUnaryInterceptors.func1({0x1069f2228, 0x1400194fad0}, {0x106828d00, 0x140023af880}, 0x140003bb9a0, 0x140018ebf08)
			/Users/ggilmore/dev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1167 +0x120
		github.com/sourcegraph/sourcegraph/cmd/symbols/proto._Symbols_SymbolInfo_Handler({0x1067e2940?, 0x140020d8d20}, {0x1069f2228, 0x1400194fad0}, 0x14000138e00, 0x140005e6da0)
			/Users/ggilmore/dev/go/src/github.com/sourcegraph/sourcegraph/cmd/symbols/proto/symbols_grpc.pb.go:199 +0x138
		google.golang.org/grpc.(*Server).processUnaryRPC(0x140020fa000, {0x1069fa0b8, 0x140005d90e0}, 0x14001f045a0, 0x140020d8db0, 0x107c66f68, 0x0)
			/Users/ggilmore/dev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xb7c
		google.golang.org/grpc.(*Server).handleStream(0x140020fa000, {0x1069fa0b8, 0x140005d90e0}, 0x14001f045a0, 0x0)
			/Users/ggilmore/dev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
		google.golang.org/grpc.(*Server).serveStreams.func1.2()
			/Users/ggilmore/dev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x84
		created by google.golang.org/grpc.(*Server).serveStreams.func1
			/Users/ggilmore/dev/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x290
	```

The panic comes from line `680` in from `squirrel`'s lang_java.go's `getProjectRoot` function:

https://github.com/sourcegraph/sourcegraph/blob/5e931ba35768278285112c9d01c037999963d439/cmd/symbols/squirrel/lang_java.go#L670-L683

I am not familiar with this logic, but it seems like there is an invalid assumption that the package name is always shorter than the file's folder path.

I believe this has been happening for a while, but prior to gRPC the panic was essentially silently caught (only logged to stderr and hidden from the UI).

**Comment by ggilmore** [comment]
cc @camdencheek  - this is the writeup
