### ISSUE TITLE
Code intel not working on Rust files

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/sourcegraph#47241]
I'm getting the following console error below when loading _Go To Def/Find refs_ on any Rust file. `Go` works fine.

Example: https://sourcegraph.com/github.com/sourcegraph/scip/-/blob/bindings/rust/src/mod.rs

I tried Chrome, Firefox, Logged out/in, and incognito. @sqs said he isn't having the problem, so I wonder if it is a CDN cache issue?

```
Unhandled Promise rejection: command is already registered: "goToDefinition" ; Zone: <root> ; Task: Promise.then ; Value: Error: command is already registered: "goToDefinition"
    at Object._ [as registerCommand] (mainthread-api.ts:93:19)
    at createNoopLoadedController.ts:60:67
    at u.invoke (zone.js:372:26)
    at a.run (zone.js:134:43)
    at zone.js:1275:36
    at u.invokeTask (zone.js:406:31)
    at a.runTask (zone.js:178:47)
    at y (zone.js:585:35) Error: command is already registered: "goToDefinition"
    at Object._ [as registerCommand] (https://sourcegraph.com/.assets/scripts/app.109a8cd055e92ec70d9a.bundle.js:2:70748)
    at https://sourcegraph.com/.assets/scripts/app.109a8cd055e92ec70d9a.bundle.js:863:4998
    at u.invoke (https://sourcegraph.com/.assets/scripts/app.109a8cd055e92ec70d9a.bundle.js:1306:763024)
    at a.run (https://sourcegraph.com/.assets/scripts/app.109a8cd055e92ec70d9a.bundle.js:1306:758432)
    at https://sourcegraph.com/.assets/scripts/app.109a8cd055e92ec70d9a.bundle.js:1306:773347
    at u.invokeTask (https://sourcegraph.com/.assets/scripts/app.109a8cd055e92ec70d9a.bundle.js:1306:763642)
    at a.runTask (https://sourcegraph.com/.assets/scripts/app.109a8cd055e92ec70d9a.bundle.js:1306:759047)
    at y (https://sourcegraph.com/.assets/scripts/app.109a8cd055e92ec70d9a.bundle.js:1306:765679)
```

Video: https://share.getcloudapp.com/E0uRB0rr

/cc @felixfbecker

**Comment by philipp-spiess** [comment]
The frontend issue seems unrelated to the fact that code-intel doesn’t work here. All of the graphql APIs return an empty result set? (`lsif` data is `null` and one query responds with `"rpc error: code = Unknown desc = unsupported language"`)

**Comment by philipp-spiess** [comment]
Here's a fix for the frontend bug though: https://github.com/sourcegraph/sourcegraph/pull/47321 😅

**Comment by Strum355** [comment]
I think this can be closed? Dont think we get the exception anymore
