### ISSUE TITLE
panic in streaming blame on sourcegraph.com

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#47591]
This only started happening two days ago, but the code itself hasn't changed. The error report seems to be missing the panic message, so it is hard to tell exactly what the issue is. But from reading the line blamed either gitserver client is nil or http.Request is nil. Either seem unlikely, but that is the hint for what has changed.

https://console.cloud.google.com/errors/detail/CNWRiJr2952ZhwE;time=P30D?authuser=0&project=sourcegraph-dev&supportedpurview=project

<details>

```
goroutine 178542997 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/sourcegraph/sourcegraph/internal/trace.loggingRecoverer.func1.1()
	github.com/sourcegraph/sourcegraph/internal/trace/httptrace.go:282 +0x1c6
panic({0x317d980, 0xbe09f50})
	runtime/panic.go:884 +0x212
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi.handleStreamBlame.func1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808c00)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi/stream_blame.go:91 +0x62e
net/http.HandlerFunc.ServeHTTP(0x9c93501?, {0x9cd45b0?, 0xc07bff11f0?}, 0x9cd7018?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/trace.Route.func1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808c00)
	github.com/sourcegraph/sourcegraph/internal/trace/httptrace.go:305 +0xe4
net/http.HandlerFunc.ServeHTTP(0xc07b808b00?, {0x9cd45b0?, 0xc07bff11f0?}, 0xc06881ce60?)
	net/http/server.go:2109 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001ce63c0, {0x9cd45b0, 0xc07bff11f0}, 0xc07b808a00)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/authz.Init.func5.1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808a00)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/authz/init.go:164 +0x422
net/http.HandlerFunc.ServeHTTP(0x9cd7018?, {0x9cd45b0?, 0xc07bff11f0?}, 0xbea3b80?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/featureflag.Middleware.func1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808900)
	github.com/sourcegraph/sourcegraph/internal/featureflag/middleware.go:33 +0x33a
net/http.HandlerFunc.ServeHTTP(0x9cd7018?, {0x9cd45b0?, 0xc07bff11f0?}, 0x7fb441432d58?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/actor.AnonymousUIDMiddleware.func1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808900)
	github.com/sourcegraph/sourcegraph/internal/actor/http.go:180 +0x21e
net/http.HandlerFunc.ServeHTTP(0x9cd7018?, {0x9cd45b0?, 0xc07bff11f0?}, 0xc0023fa400?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/auth.glob..func1.1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808900)
	github.com/sourcegraph/sourcegraph/cmd/frontend/auth/non_public.go:36 +0x9d
net/http.HandlerFunc.ServeHTTP(0x9cd7018?, {0x9cd45b0?, 0xc07bff11f0?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect.handleOpenIDConnectAuth({0x9d386c0?, 0xc001792d08?}, {0x9cd45b0, 0xc07bff11f0}, 0xc07b808900, {0x9cadb60, 0xc001e392f0}, 0x1)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go:91 +0x1f8
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect.Middleware.func1.1({0x9cd45b0?, 0xc07bff11f0?}, 0x9c93530?)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go:59 +0x48
net/http.HandlerFunc.ServeHTTP(0x9cd7018?, {0x9cd45b0?, 0xc07bff11f0?}, 0x9c93530?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml.authHandler({0x9d386c0?, 0xc001792d08?}, {0x9cd45b0, 0xc07bff11f0}, 0xc07b808900, {0x9cadb60, 0xc004433fb0}, 0x1)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml/middleware.go:56 +0x158
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml.Middleware.func1.1({0x9cd45b0?, 0xc07bff11f0?}, 0xc0023fa5f8?)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml/middleware.go:32 +0x48
net/http.HandlerFunc.ServeHTTP(0x37c7437?, {0x9cd45b0?, 0xc07bff11f0?}, 0x30?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/httpheader.middleware.func1.1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808900)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/httpheader/middleware.go:48 +0xa69
net/http.HandlerFunc.ServeHTTP(0xc04b5eee70?, {0x9cd45b0?, 0xc07bff11f0?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808900)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth/middleware.go:60 +0x365
net/http.HandlerFunc.ServeHTTP(0xc04b5eec60?, {0x9cd45b0?, 0xc07bff11f0?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808900)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth/middleware.go:60 +0x365
net/http.HandlerFunc.ServeHTTP(0xc04b5eeb40?, {0x9cd45b0?, 0xc07bff11f0?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0x9cd45b0, 0xc07bff11f0}, 0xc07b808900)
	github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth/middleware.go:60 +0x365
net/http.HandlerFunc.ServeHTTP(0x9cea5f0?, {0x9cd45b0?, 0xc07bff11f0?}, 0xc001792d08?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/session.CookieMiddlewareWithCSRFSafety.func1({0x9cd45b0, 0xc07bff11f0}, 0xc0786a1500)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/session/session.go:351 +0x303
net/http.HandlerFunc.ServeHTTP(0xc03e779a70?, {0x9cd45b0?, 0xc07bff11f0?}, 0x5?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi.AccessTokenAuthMiddleware.func1({0x9cd45b0, 0xc07bff11f0}, 0xc0786a1500)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi/auth.go:274 +0x2bce
net/http.HandlerFunc.ServeHTTP(0x9cd7018?, {0x9cd45b0?, 0xc07bff11f0?}, 0xbea3b80?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/requestclient.HTTPMiddleware.func1({0x9cd45b0, 0xc07bff11f0}, 0xc0786a1400)
	github.com/sourcegraph/sourcegraph/internal/requestclient/http.go:47 +0x253
net/http.HandlerFunc.ServeHTTP(0x2fb3c00?, {0x9cd45b0?, 0xc07bff11f0?}, 0x4?)
	net/http/server.go:2109 +0x2f
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x9cd5ed0, 0xc03efd2f00}, 0xc03e779b01?)
	github.com/NYTimes/gziphandler@v1.1.1/gzip.go:336 +0x249
net/http.HandlerFunc.ServeHTTP(0xc0786a1300?, {0x9cd5ed0?, 0xc03efd2f00?}, 0x4?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/deviceid.Middleware.func1({0x9cd5ed0, 0xc03efd2f00?}, 0xc0786a1300)
	github.com/sourcegraph/sourcegraph/internal/deviceid/middleware.go:29 +0x417
net/http.HandlerFunc.ServeHTTP(0x9cd5ed0?, {0x9cd5ed0?, 0xc03efd2f00?}, 0x37354d2?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.secureHeadersMiddleware.func1({0x9cd5ed0, 0xc03efd2f00}, 0xc0023fc838?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/http.go:227 +0x389
net/http.HandlerFunc.ServeHTTP(0x8f24c9?, {0x9cd5ed0?, 0xc03efd2f00?}, 0x20301c?)
	net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0x4441e5?, {0x9cd5ed0, 0xc03efd2f00}, 0xc0786a1300)
	net/http/server.go:2487 +0x149
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.Trace.func1({0x9cd5ed0?, 0xc03efd2f00?}, 0xc0029b6150?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware/trace.go:27 +0x18e
net/http.HandlerFunc.ServeHTTP(0xc0023fc938?, {0x9cd5ed0?, 0xc03efd2f00?}, 0xc?)
	net/http/server.go:2109 +0x2f
github.com/gorilla/context.ClearHandler.func1({0x9cd5ed0?, 0xc03efd2f00?}, 0x0?)
	github.com/gorilla/context@v1.1.1/context.go:141 +0x73
net/http.HandlerFunc.ServeHTTP(0x3459040?, {0x9cd5ed0?, 0xc03efd2f00?}, 0xc?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.healthCheckMiddleware.func1({0x9cd5ed0, 0xc03efd2f00}, 0x30?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/http.go:128 +0xb4
net/http.HandlerFunc.ServeHTTP(0xc0023fc9c0?, {0x9cd5ed0?, 0xc03efd2f00?}, 0xc03e779bf0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.BlackHole.func1({0x9cd5ed0, 0xc03efd2f00}, 0xc03e779bf0?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware/blackhole.go:17 +0x9d
net/http.HandlerFunc.ServeHTTP(0xc0023fca48?, {0x9cd5ed0?, 0xc03efd2f00?}, 0x6?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.SourcegraphComGoGetHandler.func1({0x9cd5ed0?, 0xc03efd2f00}, 0xc0786a1300)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware/goimportpath.go:48 +0xd7
net/http.HandlerFunc.ServeHTTP(0x40d97f?, {0x9cd5ed0?, 0xc03efd2f00?}, 0xa?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/auth.ForbidAllRequestsMiddleware.func1({0x9cd5ed0, 0xc03efd2f00}, 0x0?)
	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/auth/forbid_all.go:19 +0x8e
net/http.HandlerFunc.ServeHTTP(0x40dcc7?, {0x9cd5ed0?, 0xc03efd2f00?}, 0x490401?)
	net/http/server.go:2109 +0x2f
github.com/felixge/httpsnoop.CaptureMetrics.func1({0x9cd5ed0?, 0xc03efd2f00?})
	github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:29 +0x39
github.com/felixge/httpsnoop.(*Metrics).CaptureMetrics(0xc074a069c0, {0x9cd43d0, 0xc080aea460}, 0xc0023fcd18)
	github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:84 +0x1ff
github.com/felixge/httpsnoop.CaptureMetricsFn(...)
	github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:39
github.com/felixge/httpsnoop.CaptureMetrics({0x9cadb60?, 0xc001f3fb30?}, {0x9cd43d0, 0xc080aea460}, 0x2ea6d40?)
	github.com/felixge/httpsnoop@v1.0.3/capture_metrics.go:28 +0x90
github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1({0x9cd43d0, 0xc080aea460}, 0xc0786a1200)
	github.com/sourcegraph/sourcegraph/internal/trace/httptrace.go:154 +0x90d
net/http.HandlerFunc.ServeHTTP(0xc0023fd538?, {0x9cd43d0?, 0xc080aea460?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/sourcegraph/sourcegraph/internal/trace.loggingRecoverer.func1({0x9cd43d0?, 0xc080aea460?}, 0xc03e779ad0?)
	github.com/sourcegraph/sourcegraph/internal/trace/httptrace.go:287 +0x96
net/http.HandlerFunc.ServeHTTP(0x6e76a7?, {0x9cd43d0?, 0xc080aea460?}, 0x67483c?)
	net/http/server.go:2109 +0x2f
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc003678160, {0x9cd43d0?, 0xc080aea460}, 0xc0786a1200)
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.36.4/handler.go:125 +0x134
github.com/sourcegraph/sourcegraph/internal/instrumentation.HTTPMiddleware.func3({0x9cd43d0, 0xc080aea460}, 0xc0786a1100)
	github.com/sourcegraph/sourcegraph/internal/instrumentation/http.go:53 +0x24e
net/http.HandlerFunc.ServeHTTP(0x0?, {0x9cd43d0?, 0xc080aea460?}, 0x46c8ce?)
	net/http/server.go:2109 +0x2f
net/http.serverHandler.ServeHTTP({0xc02f1bdb30?}, {0x9cd43d0, 0xc080aea460}, 0xc0786a1100)
	net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc02f20c500, {0x9cd7018, 0xc0044b6a20})
	net/http/server.go:1991 +0x607
```

</details>

**Comment by keegancsmith** [comment]
@jhchabran I don't know a good owner for this, but I remember you writing this feature so initially assigning you.

**Comment by jhchabran** [comment]
That's weird, I can't find any occurence since then and I don't see how https://github.com/sourcegraph/sourcegraph/pull/47729 might have affected this 🤔

**Comment by keegancsmith** [comment]
I just marked it as resolved given it only ever happened once. Lets just assume a cosmic ray caused a panic :P
