### ISSUE TITLE
Panic when searching among repositories that were added recently

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#4821]
On my local dev instance, the queries `repo:^github\.com/sd9/TypeScriptSamples$ file:ts` and `repo:^github\.com/sd9/TypeScriptSamples$ ts` cause panics.

The repo is indexed:

![image](https://user-images.githubusercontent.com/1976/60776055-f4653200-a0dd-11e9-90ac-b4be912af6fa.png)

The panic is:

```
17:35:49               frontend | len(revs)=17, len(set)=17
17:35:49               frontend | revs=[github.com/sd9/content-renderer@ github.com/sd9/hackathon-starter@ github.com/sd9/react-loading-spinner@ github.com/sd9org/golang-lib@ github.com/sd9org/java-maven-app@ github.com/sd9/about@ github.com/sd9/sourcegraph-lightstep@ github.com/sd9/go-diff@ github.com/sd9/codeintellify@ github.com/sd9/lint@ github.com/sd9/gomemcache@ github.com/sd9org/groupcache@ github.com/sd9org/makex@ github.com/sd9org/apiproxy@ github.com/sd9org/appmon@ github.com/sd9org/checkup@ github.com/sd9/TypeScriptSamples@]
17:35:49               frontend | set=map[github.com/sd9/about:0xc001065560 github.com/sd9/codeintellify:0xc0010659e0 github.com/sd9/content-renderer:0xc001140fc0 github.com/sd9/go-diff:0xc001140360 github.com/sd9/gomemcache:0xc001141c20 github.com/sd9/hackathon-starter:0xc0010657a0 github.com/sd9/lint:0xc001141e60 github.com/sd9/react-loading-spinner:0xc001141d40 github.com/sd9/sourcegraph-lightstep:0xc001064000 github.com/sd9/typescriptsamples:0xc001065680 github.com/sd9org/apiproxy:0xc0011418c0 github.com/sd9org/appmon:0xc001065200 github.com/sd9org/checkup:0xc0010658c0 github.com/sd9org/golang-lib:0xc0011419e0 github.com/sd9org/groupcache:0xc001065320 github.com/sd9org/java-maven-app:0xc001065c20 github.com/sd9org/makex:0xc001065b00]
17:37:11               frontend | len(revs)=1, len(set)=17
17:37:11               frontend | revs=[github.com/sd9/TypeScriptSamples@]
17:37:11               frontend | set=map[github.com/sd9/about:0xc00168aa20 github.com/sd9/codeintellify:0xc0019d06c0 github.com/sd9/content-renderer:0xc001625d40 github.com/sd9/go-diff:0xc001597320 github.com/sd9/gomemcache:0xc0017ea5a0 github.com/sd9/hackathon-starter:0xc0015a1d40 github.com/sd9/lint:0xc0015a19e0 github.com/sd9/react-loading-spinner:0xc0017eaa20 github.com/sd9/sourcegraph-lightstep:0xc0019d0ea0 github.com/sd9/typescriptsamples:0xc0016a2fc0 github.com/sd9org/apiproxy:0xc0019d19e0 github.com/sd9org/appmon:0xc0017eab40 github.com/sd9org/checkup:0xc0017eafc0 github.com/sd9org/golang-lib:0xc001201200 github.com/sd9org/groupcache:0xc00168b200 github.com/sd9org/java-maven-app:0xc0019d1440 github.com/sd9org/makex:0xc0012007e0]
17:37:11               frontend | goroutine panic: runtime error: makeslice: cap out of range
17:37:11               frontend | goroutine 6661 [running]:
17:37:11               frontend | runtime/debug.Stack(0xc001429938, 0x14ff140, 0x19982f0)
17:37:11               frontend | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
17:37:11               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine.Go.func1.1()
17:37:11               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine/goroutine.go:20 +0x57
17:37:11               frontend | panic(0x14ff140, 0x19982f0)
17:37:11               frontend | 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
17:37:11               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.zoektIndexedRepos(0x19e6380, 0xc0005d9ce0, 0xc001561e50, 0xc0008e01f8, 0x1, 0x1, 0xc000e3f440, 0x0, 0x11, 0x0, ...)
17:37:11               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:853 +0x36f
17:37:11               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.searchFilesInRepos(0x19e6300, 0xc001518a00, 0xc001169f80, 0x0, 0x0, 0x0, 0x180b3b8, 0xc000060a00, 0xc00124fe38)
17:37:11               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/textsearch.go:904 +0x172a
17:37:11               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend.(*searchResolver).doResults.func5()
17:37:11               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/search_results.go:928 +0xfd
17:37:11               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine.Go.func1(0xc0005fb260)
17:37:11               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine/goroutine.go:24 +0x43
17:37:11               frontend | created by github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine.Go
17:37:11               frontend | 	/home/sqs/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine/goroutine.go:17 +0x3f
```

(I added logging of `revs` and `set` at the top of the pasted text.)

I can repro this when I add a new repo (eg by adding `"repos": ["sqs/spans"]` to my GitHub external service config. (Then queries that include that repository also fail with a similar panic.)

**Comment by sqs** [comment]
Seems to be fixed after I rebased against latest master
