### ISSUE TITLE
k8s.sgdev.org: indexed-search pod is in CrashLoopBackoff 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#4890]
`kubectl describe pod indexed-search-6f7cb7db7f-ssbbx`

```
Name:           indexed-search-6f7cb7db7f-ssbbx
Namespace:      default
Priority:       0
Node:           gke-dogfood-full-k8s-moar-memory-2d710a23-r2l5/10.240.0.37
Start Time:     Wed, 10 Jul 2019 06:38:01 -0700
Labels:         app=indexed-search
                pod-template-hash=2937638639
Annotations:    <none>
Status:         Running
IP:             10.0.5.99
Controlled By:  ReplicaSet/indexed-search-6f7cb7db7f
Containers:
  zoekt-webserver:
    Container ID:  docker://096c86c0c1ef2315f10e1710bcb5d75c4d0872bbb7ebf22b705ea6ba032dd415
    Image:         index.docker.io/sourcegraph/zoekt-webserver:19-06-19_c84cd19@sha256:57a3eb4991540bf813fc62459719b2db3dbac540dd284088cd2e84081225531f
    Image ID:      docker-pullable://sourcegraph/zoekt-webserver@sha256:57a3eb4991540bf813fc62459719b2db3dbac540dd284088cd2e84081225531f
    Port:          6070/TCP
    Host Port:     0/TCP
    State:         Running
      Started:     Mon, 15 Jul 2019 15:37:38 -0700
    Last State:    Terminated
      Reason:      Error
      Message:     /watcher.go:114 +0x87a

goroutine 52977 [runnable]:
github.com/google/zoekt.(*reader).readIndexData(0xcc970f6ca0, 0xd07b5acf20, 0x0, 0x0, 0xcfddd9bd88)
  /go/src/github.com/google/zoekt/read.go:196 +0x642
github.com/google/zoekt.NewSearcher(0x95d600, 0xccd85a19b0, 0xccd85a19b0, 0x0, 0x0, 0x0)
  /go/src/github.com/google/zoekt/read.go:354 +0xac
github.com/google/zoekt/shards.loadShard(0xc0006415e0, 0x49, 0x0, 0x0, 0x0, 0x202030303030203)
  /go/src/github.com/google/zoekt/shards/shards.go:399 +0xb5
github.com/google/zoekt/shards.(*throttledLoader).load(0xc0000a1200, 0xc0006415e0, 0x49)
  /go/src/github.com/google/zoekt/shards/shards.go:83 +0x5e
github.com/google/zoekt/shards.(*shardWatcher).scan.func1(0xc0001e4bd0, 0xc00018a040, 0xc0006415e0, 0x49)
  /go/src/github.com/google/zoekt/shards/watcher.go:115 +0x48
created by github.com/google/zoekt/shards.(*shardWatcher).scan
  /go/src/github.com/google/zoekt/shards/watcher.go:114 +0x87a

goroutine 53402 [runnable]:
github.com/google/zoekt.(*reader).readIndexData(0xd35b622c00, 0xcfb570b8c0, 0x0, 0x0, 0xcbf42d4b78)
  /go/src/github.com/google/zoekt/read.go:196 +0x642
github.com/google/zoekt.NewSearcher(0x95d600, 0xc01aa54c30, 0xc01aa54c30, 0x0, 0x0, 0x0)
  /go/src/github.com/google/zoekt/read.go:354 +0xac
github.com/google/zoekt/shards.loadShard(0xc000d1d620, 0x59, 0x0, 0x0, 0x0, 0x0)
  /go/src/github.com/google/zoekt/shards/shards.go:399 +0xb5
github.com/google/zoekt/shards.(*throttledLoader).load(0xc0000a1200, 0xc000d1d620, 0x59)
  /go/src/github.com/google/zoekt/shards/shards.go:83 +0x5e
github.com/google/zoekt/shards.(*shardWatcher).scan.func1(0xc0001e4bd0, 0xc00018a040, 0xc000d1d620, 0x59)
  /go/src/github.com/google/zoekt/shards/watcher.go:115 +0x48
created by github.com/google/zoekt/shards.(*shardWatcher).scan
  /go/src/github.com/google/zoekt/shards/watcher.go:114 +0x87a

goroutine 53465 [running]:
  goroutine running on other thread; stack unavailable
created by github.com/google/zoekt/shards.(*shardWatcher).scan
  /go/src/github.com/google/zoekt/shards/watcher.go:114 +0x87a

      Exit Code:    2
      Started:      Mon, 15 Jul 2019 15:28:36 -0700
      Finished:     Mon, 15 Jul 2019 15:32:31 -0700
    Ready:          False
    Restart Count:  639
    Limits:
      cpu:     12
      memory:  120Gi
    Requests:
      cpu:      12
      memory:   120Gi
    Readiness:  http-get http://:http/healthz delay=0s timeout=1s period=1s #success=1 #failure=1
    Environment:
      GOGC:     50
      GODEBUG:  gctrace=1
    Mounts:
      /data from disk (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2vkvv (ro)
  zoekt-indexserver:
    Container ID:   docker://b0ff2909bcd2e33265e9f562327969582b4b86adfec83c723ff08796ca917530
    Image:          index.docker.io/sourcegraph/zoekt-indexserver:19-06-13_f4122ec@sha256:7f8feae2f9c5487387aff62767cb589a63498acb1412263894bdc9756fa03b1a
    Image ID:       docker-pullable://sourcegraph/zoekt-indexserver@sha256:7f8feae2f9c5487387aff62767cb589a63498acb1412263894bdc9756fa03b1a
    Port:           6072/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 10 Jul 2019 06:38:19 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     4
      memory:  4G
    Requests:
      cpu:        500m
      memory:     2Gi
    Environment:  <none>
    Mounts:
      /data from disk (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2vkvv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  disk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  indexed-search
    ReadOnly:   false
  default-token-2vkvv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2vkvv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                      From                                                     Message
  ----     ------     ----                     ----                                                     -------
  Warning  BackOff    6m8s (x14550 over 4d1h)  kubelet, gke-dogfood-full-k8s-moar-memory-2d710a23-r2l5  Back-off restarting failed container
  Warning  Unhealthy  68s (x154895 over 5d9h)  kubelet, gke-dogfood-full-k8s-moar-memory-2d710a23-r2l5  Readiness probe failed: Get http://10.0.5.99:6070/healthz: dial tcp 10.0.5.99:6070: connect: connection refused
```

cc @sourcegraph/core-services

**Comment by keegancsmith** [comment]
> fatal error: runtime: cannot allocate memory

malloc is failing, so it is OOMing, just the OOM killer isn't killing it.

It seems to be unable to start. My best guess is we just have too many repos for one replica to handle. I see k8s.sgdev now has 58004 repos. This is unlike any customer we have, so I am gonna reduce the number of repos.

**Comment by keegancsmith** [comment]
```sql
select jsonb_object_keys(sources) as svc, count(1) as c from repo group by svc order by c;
            svc            |   c   
---------------------------+-------
 extsvc:bitbucketserver:19 |     2
 extsvc:github:8           |     3
 extsvc:awscodecommit:3    |     3
 extsvc:gitlab:18          |    16
 extsvc:github:16          |    19
 extsvc:github:9           |    19
 extsvc:github:10          |    22
 extsvc:gitolite:7         | 11183
 extsvc:github:12          | 46757
(9 rows)

select display_name from external_services where id = 12;
   display_name    
-------------------
 GitHub Enterprise
```

I switched to just cloning the sourcegraph org repos from GHE. Otherwise too many repos for zoekt to index. Currently the sg org is 25979 repos, while the whole of our GHE instance is 46757 repos. The old repoquery was `"public", "affiliated"`

**Comment by keegancsmith** [comment]
indexed-search is working again.
