### ISSUE TITLE
Updating Phabricator external service leads to "EOF" warning and nil pointer panic in background

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4898]
- **Sourcegraph version:** k8s.sgdev.org

#### Steps to reproduce:

1. Create new Phabricator external service: https://k8s.sgdev.org/site-admin/external-services/new?kind=phabricator
2. Use a valid configuration, like this:
```json
{

  "url": "https://phabricator.sgdev.org",
  "token": "api-FOOBARTOKEN",
  "repos": [
    {
      "path": "gorilla/mux",
      "callsign": "rMUX"
    }
  ]
}
```
3. Create external service

#### Expected behavior:

External service is created without any warning or error.

#### Actual behavior:

I see a warning:

<img width="984" alt="Screen Shot 2019-07-16 at 13 14 40" src="https://user-images.githubusercontent.com/1185253/61290688-c0b89500-a7cc-11e9-915e-df211a10e1a2.png">

Further investigation reveals that the request killed the `frontend` process with a nil pointer dereference. Here is the panic:

```
 "panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa8b331]

goroutine 1290 [running]:
github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos.(*PhabricatorSource).client(0xc00302fef0, 0x101eb80, 0xc0010e3c40, 0x0, 0x0, 0x0)
	/buildkite/builds/buildkite-agent-6ffffdfcc4-qqx6n-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos/phabricator.go:172 +0x91
github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos.(*PhabricatorSource).ListRepos(0xc00302fef0, 0x101eb80, 0xc0010e3c40, 0xc00302fef0, 0x0, 0x0, 0x1008e01, 0xc0000cb9f0)
	/buildkite/builds/buildkite-agent-6ffffdfcc4-qqx6n-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos/phabricator.go:41 +0x5a
github.com/sourcegraph/sourcegraph/cmd/repo-updater/repoupdater.(*Server).handleExternalServiceSync.func1(0xc002eba850, 0xc002e94300, 0x101eb80, 0xc0010e3c40)
	/buildkite/builds/buildkite-agent-6ffffdfcc4-qqx6n-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/repo-updater/repoupdater/server.go:314 +0x105
created by github.com/sourcegraph/sourcegraph/cmd/repo-updater/repoupdater.(*Server).handleExternalServiceSync
	/buildkite/builds/buildkite-agent-6ffffdfcc4-qqx6n-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/repo-updater/repoupdater/server.go:302 +0x1db
```
([Link to exact log line on GKE](https://console.cloud.google.com/logs/viewer?project=sourcegraph-dev&authuser=1&minLogLevel=0&expandAll=false&timestamp=2019-07-16T11:17:06.334000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-07-16T10:19:30.436Z&interval=PT1H&resource=container%2Fcluster_name%2Fdogfood-full-k8s%2Fnamespace_id%2Fdefault&scrollTimestamp=2019-07-16T11:17:09.528906263Z&logName=projects%2Fsourcegraph-dev%2Flogs%2Ffrontend&logName=projects%2Fsourcegraph-dev%2Flogs%2Frepo-updater&dateRangeEnd=2019-07-16T11:19:30.436Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22dogfood-full-k8s%22%0Aresource.labels.namespace_id%3D%22default%22%0AlogName%3D(%22projects%2Fsourcegraph-dev%2Flogs%2Ffrontend%22%20OR%20%22projects%2Fsourcegraph-dev%2Flogs%2Frepo-updater%22)%0A(-%22StatusMessages%22%20AND%0A-%22SCHED%22%20AND%20-%22status-messages%22%20AND%20-%22github%20sync%22%20AND%20-%22ListOrgRepositories%22%20AND%20-%22TRACE%20github%22%20AND%20-%22MB%20goal%22)%0A))

**Comment by mrnugget** [comment]
I found it. When testing the syncing of the external service in the background no middleware is passed in:

https://github.com/sourcegraph/sourcegraph/blob/008661b03bd46bc9aac5032bd2e31e3ed1a031ea/cmd/repo-updater/repoupdater/server.go#L303-L308

That leads to this line blowing up:

https://github.com/sourcegraph/sourcegraph/blob/008661b03bd46bc9aac5032bd2e31e3ed1a031ea/cmd/repo-updater/repos/phabricator.go#L172
