### ISSUE TITLE
cody: failed to start due to corruption in secret storage

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#51573]
I don't know how this happened, but I was having trouble for a while where Cody would just not load for me (IE the side panel showed nothing). I finally decided to dive into this today and the root cause was the secret for the auth token was corrupt.

I only managed to finally track this down by starting up a development version of cody.

Tracked it down to our extension.activate function. It just console.logs if anything goes wrong. Probably should do something different? Either way I couldn't see these logs until I started up a development version.

Additionally when looking into how to clear out the secret, the problem is we only load the command to delete the cody secret if we successfully start the extension. So I am stuck right now and will do hacks to fix. This was the hack I had to do:

```diff
diff --git a/client/cody/src/main.ts b/client/cody/src/main.ts
index a5ec755980..19e3d6f202 100644
--- a/client/cody/src/main.ts
+++ b/client/cody/src/main.ts
@@ -24,6 +24,8 @@ export async function start(context: vscode.ExtensionContext): Promise<vscode.Di
     const localStorage = new LocalStorage(context.globalState)
     const rgPath = await getRgPath(context.extensionPath)

+    await secretStorage.delete(CODY_ACCESS_TOKEN_SECRET)
+
     const disposables: vscode.Disposable[] = []

     const { disposable, onConfigurationChange } = await register(
```

```
Error: Unable to parse decrypted password
    at C.$getPassword (vscode-file://vscode-app/nix/store/8gipj9j2kj96jp4r2ci8vj51603rpdim-vscode-1.77.3/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1586:49370) {name: 'Error', message: 'Unable to parse decrypted password', stack: 'Error: Unable to parse decrypted password
   …rkbench/workbench.desktop.main.js:1586:49370)'}
arg0: Error: Unable to parse decrypted password\n    at C.$getPassword (vscode-file://vscode-app/nix/store/8gipj9j2kj96jp4r2ci8vj51603rpdim-vscode-1.77.3/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1586:49370) {name: 'Error', message: 'Unable to parse decrypted password', stack: 'Error: Unable to parse decrypted password\n   …rkbench/workbench.desktop.main.js:1586:49370)'}
message: 'Unable to parse decrypted password'
name: 'Error'
stack: 'Error: Unable to parse decrypted password\n    at C.$getPassword (vscode-file://vscode-app/nix/store/8gipj9j2kj96jp4r2ci8vj51603rpdim-vscode-1.77.3/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1586:49370)'
[[Prototype]]: Object
f @ /nix/store/8gipj9j2kj96jp4r2ci8vj51603rpdim-vscode-1.77.3/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6
e @ /nix/store/8gipj9j2kj96jp4r2ci8vj51603rpdim-vscode-1.77.3/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:155932
<anonymous> @ /nix/store/8gipj9j2kj96jp4r2ci8vj51603rpdim-vscode-1.77.3/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:155800
<anonymous> @ /Users/keegan/src/github.com/sourcegraph/sourcegraph/client/cody/src/extension.ts:19:33
◀ Promise.catch ▶
activate @ /Users/keegan/src/github.com/sourcegraph/sourcegraph/client/cody/src/extension.ts:19:10
...snip
```

**Comment by abeatrix** [comment]
We haven't heard of anyone running into this issue again after the fix released in https://github.com/sourcegraph/sourcegraph/pull/51638 . I have some clean-ups included in https://github.com/sourcegraph/sourcegraph/pull/51883, but I believe this issue has been resolved. 

Please reopen this issue again if anyone is running into the same issue after upgrading to v0.1.2, thanks!
