### ISSUE TITLE
No Link component set. You must call setLinkComponent to set the Link component to use.

### ISSUE THREAD

**Issue by yeldarby** [sourcegraph/sourcegraph#51854]
- **Sourcegraph version:** Fresh repo clone
- **Platform information:** MacOS 13.2.1, M1 Max, 64GB Memory

#### Steps to reproduce:

1. Clone the repo
2. Run `sg setup`
3. Run `sg start oss`
4. Visit `sourcegraph.test:3443`

#### Expected behavior:
The site to load

#### Actual behavior:

The site redirects to `https://sourcegraph.test:3443/site-admin/init`
with an error:
```
Unexpected Application Error!
No Link component set. You must call setLinkComponent to set the Link component to use.
Error: No Link component set. You must call setLinkComponent to set the Link component to use.
    at eval (webpack-internal:///../wildcard/src/components/Link/Link/Link.tsx:37:11)
    at renderWithHooks (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:2691:157)
    at updateForwardRef (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:3359:200)
    at beginWork (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:3865:1563)
    at beginWork$1 (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:4680:93)
    at performUnitOfWork (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:4506:150)
    at workLoopSync (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:4492:30)
    at renderRootSync (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:4488:159)
    at recoverFromConcurrentError (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:4367:170)
    at performSyncWorkOnRoot (webpack-internal:///../../node_modules/.pnpm/react-dom@18.1.0_react@18.1.0/node_modules/react-dom/cjs/react-dom.development.js:4426:126)
```

**Comment by yeldarby** [comment]
I checked out a different commit (`e3f03f2e34e9118d7c82d2ae36caa5fa86b63209`) and it worked.
