### ISSUE TITLE
Cody embedding retrieval failed with "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by jiayao** [sourcegraph/sourcegraph#51909]
- **Sourcegraph version:** 0.1.2
- **Platform information:** Mac

#### Steps to reproduce:

Ask any questions about the codebase with Cody, e.g. "give me a list of Cody recipes" in sourcegraph repo

#### Expected behavior:
Cody should provide an answer based on the relevant parts of the codebase

#### Actual behavior:
It gave me a 100% hallucinated answer.

Running the extension in a debugger shows there is a problem with embedding retrieval:

Error retrieving embeddings: Error: panic occurred: runtime error: invalid memory address or nil pointer dereference
	at extractDataOrError (/Users/oss/gitrepo/sourcegraph/client/cody-shared/src/sourcegraph-api/graphql/client.ts:61:16)
	at /Users/oss/gitrepo/sourcegraph/client/cody-shared/src/sourcegraph-api/graphql/client.ts:154:29
	at process.processTicksAndRejections (/Users/oss/gitrepo/sourcegraph/lib/internal/process/task_queues.js:96:5)
	at async CodebaseContext.getEmbeddingSearchResults (/Users/oss/gitrepo/sourcegraph/client/cody-shared/src/codebase-context/index.ts:84:41)
	at async CodebaseContext.getEmbeddingsContextMessages (/Users/oss/gitrepo/sourcegraph/client/cody-shared/src/codebase-context/index.ts:69:33)
	at async ChatQuestion.getContextMessages (/Users/oss/gitrepo/sourcegraph/client/cody-shared/src/chat/recipes/chat-question.ts:52:45)
	at async Interaction.hasContext (/Users/oss/gitrepo/sourcegraph/client/cody-shared/src/chat/transcript/interaction.ts:47:33)
	at async Transcript.getLastInteractionWithContextIndex (/Users/oss/gitrepo/sourcegraph/client/cody-shared/src/chat/transcript/index.ts:101:32)
	at async Transcript.toPrompt (/Users/oss/gitrepo/sourcegraph/client/cody-shared/src/chat/transcript/index.ts:110:49)
	at async ChatViewProvider.executeRecipe (/Users/oss/gitrepo/sourcegraph/client/cody/src/chat/ChatViewProvider.ts:405:32)

**Comment by camdencheek** [comment]
Hi @jiayao! Is this coming from a public instance of Sourcegraph or a private instance? We make a request to the sourcegraph instance with the path `graphql?EmbeddingsSearch`. Would it be possible to send back the complete error from that API response? The one copied in does not contain the full stacktrace.

**Comment by camdencheek** [comment]
I think I managed to track down the panic and have deployed an update to sourcegraph.com to fix it. Please let me know if you continue to see the issue. Thanks for the bug report!

**Comment by jiayao** [comment]
It works now, thank you!
