### ISSUE TITLE
Error fetching commit author info from GraphQL API

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5335]
- **Sourcegraph version:** sgdev

(Not entirely sure who to assign this to, so I just grabbed the core team. Feel free to reassign.)

Reported by a customer:
* https://app.hubspot.com/contacts/2762526/company/814799425

Any ideas about potential workaround to get this data on search results until a fix is live?

#### Steps to reproduce:

1. Run the query at https://sourcegraph.sgdev.org/api/console#%7B%22query%22%3A%22query%20(%24query%3A%20String!)%20%7B%5Cn%20%20search(query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20file%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20commit%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20author%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20person%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20email%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22sourcegraph%2Fsourcegraph%5C%22%5Cn%7D%22%7D

2. See error:

![image](https://user-images.githubusercontent.com/5589410/63541983-1a029b00-c4d4-11e9-9397-8de30be1e897.png)

The same issue exists for all fields within the `person` object, but does not occur for other fields in the `author` object one level above that.

#### Expected behavior:

Author information should be available

#### Actual behavior:

`"json: error calling MarshalJSON for type json.RawMessage: invalid character '}' looking for beginning of value\n"`

Looks like an unexpected empty string/nil error. Like the search API isn't populating that field for some reason?

**Comment by mrnugget** [comment]
This is a `panic` happening because `author` is `nil`:
```
10:51:52               frontend | graphql: panic occurred: graphql: got nil for non-null "Person"
10:51:52               frontend | goroutine 580 [running]:
10:51:52               frontend | github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0x36fcbb0, 0x2a12200, 0xc0009b8150, 0x254dea0, 0xc000979260)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/log/log.go:21 +0x8d
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).handlePanic(0xc00090ab40, 0x2a12200, 0xc0009b8150)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:29 +0x86
10:51:52               frontend | panic(0x254dea0, 0xc000979260)
10:51:52               frontend |       /Users/thorstenball/.asdf/installs/golang/1.12.8/go/src/runtime/panic.go:522 +0x1e0
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelectionSet(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1c20, 0x1, 0x1, 0x29fbd40, 0xc00034d190, 0xc0002b1e40, 0x2618ba0, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:215 +0x12c1
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x2a12200, 0xc0009b8360, 0xc00090ab40, 0xc000bddc40, 0xc0002b1e40, 0x0)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:205 +0x4cd
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1bf0, 0x1, 0x1, 0xc0002b1de0, 0x257f6c0, 0xc0008f1c18, 0x96, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:94 +0x5d1
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelectionSet(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1bf0, 0x1, 0x1, 0x29fbd40, 0xc00031e4c0, 0xc0002b1de0, 0x257f6c0, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:221 +0x39a
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x2a12200, 0xc0009b8360, 0xc00090ab40, 0xc000bddc00, 0xc0002b1de0, 0x0)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:205 +0x4cd
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1b60, 0x1, 0x1, 0xc0002b1d20, 0x2704e00, 0xc0008f1be8, 0x96, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:94 +0x5d1
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelectionSet(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1b60, 0x1, 0x1, 0x29fbd40, 0xc0003d9730, 0xc0002b1d20, 0x2704e00, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:221 +0x39a
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x2a12200, 0xc0009b8360, 0xc00090ab40, 0xc000bddbc0, 0xc0002b1d20, 0x0)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:205 +0x4cd
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1b00, 0x1, 0x1, 0xc0002b1c20, 0x2719560, 0xc0008f1b38, 0x96, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:94 +0x5d1
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelectionSet(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1b00, 0x1, 0x1, 0x29fbd40, 0xc000339530, 0xc0002b1c20, 0x2719560, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:221 +0x39a
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x2a12200, 0xc0009b8360, 0xc00090ab40, 0xc000bddb80, 0xc0002b1c20, 0x0)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:205 +0x4cd
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1ae0, 0x1, 0x1, 0xc0002b1ba0, 0x25ed900, 0xc000947590, 0x194, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:94 +0x5d1
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelectionSet(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1ae0, 0x1, 0x1, 0x29fbd40, 0xc0002ae890, 0xc0002b1ba0, 0x25ed900, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:221 +0x39a
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelectionSet(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008f1ae0, 0x1, 0x1, 0x29fbd40, 0xc0002ae8b0, 0xc0002b1a60, 0x24c44e0, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:266 +0xc93
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x2a12200, 0xc0009b8360, 0xc00090ab40, 0xc000bddb40, 0xc0002b1a60, 0x0)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:205 +0x4cd
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008a99a0, 0x1, 0x1, 0xc0000d0020, 0x26f2f40, 0xc0009b83d8, 0x96, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:94 +0x5d1
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelectionSet(0xc00090ab40, 0x2a12200, 0xc0009b8360, 0xc0008a99a0, 0x1, 0x1, 0x29fbd40, 0xc0003385d0, 0xc0000d0020, 0x26f2f40, ...)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:221 +0x39a
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x2a12200, 0xc0009b8150, 0xc00090ab40, 0xc000e848c0, 0xc0000d0020, 0x1)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:205 +0x4cd
10:51:52               frontend | github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections.func1(0xc0002acd00, 0xc00090ab40, 0x2a12200, 0xc0009b8150, 0xc0002a1e60, 0xc000e848c0)
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:74 +0x1b3
10:51:52               frontend | created by github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections
10:51:52               frontend |       /Users/thorstenball/code/go/pkg/mod/github.com/sourcegraph/graphql-go@v0.0.0-20180929065141-c790ffc3c46a/internal/exec/exec.go:70 +0x2bf
```

The problem is that `author` is not nullable. [See definition here](https://github.com/sourcegraph/sourcegraph/blob/be84360d06b76dd49ab051ab759cff2ed27357aa/cmd/frontend/graphqlbackend/schema.graphql#L1772-L1773).

But in the codepath that sets up the `File` on the `FileMatch` we don't set the `author`. @sqs left a note that this is due to performance reasons: https://github.com/sourcegraph/sourcegraph/blob/be84360d06b76dd49ab051ab759cff2ed27357aa/cmd/frontend/graphqlbackend/textsearch.go#L80-L82

Sounds to me like we have two choices:

1. Make `author` optional
2. Load the `author`

Option 1 would be a breaking API change, I guess. And option 2 would be a performance penalty. I'd rather go with 1, but I'd leave the call regarding the API compatability up to someone with more experience in that area.

Here's how I would make `author` optional. This fixed the panic for me locally:

<details><summary>Click to see diff</summary>
<p>
```diff
diff --git a/cmd/frontend/graphqlbackend/git_commit.go b/cmd/frontend/graphqlbackend/git_commit.go
index c74e508e76..ef49af45fa 100644
--- a/cmd/frontend/graphqlbackend/git_commit.go
+++ b/cmd/frontend/graphqlbackend/git_commit.go
@@ -37,20 +37,19 @@ type GitCommitResolver struct {
 	// oid MUST be specified and a 40-character Git SHA.
 	oid GitObjectID
 
-	author    signatureResolver
+	author    *signatureResolver
 	committer *signatureResolver
 	message   string
 	parents   []api.CommitID
 }
 
 func toGitCommitResolver(repo *RepositoryResolver, commit *git.Commit) *GitCommitResolver {
-	authorResolver := toSignatureResolver(&commit.Author)
 	return &GitCommitResolver{
 		repo: repo,
 
 		oid: GitObjectID(commit.ID),
 
-		author:    *authorResolver,
+		author:    toSignatureResolver(commit.Author),
 		committer: toSignatureResolver(commit.Committer),
 		message:   commit.Message,
 		parents:   commit.Parents,
@@ -85,7 +84,7 @@ func (r *GitCommitResolver) OID() GitObjectID { return r.oid }
 func (r *GitCommitResolver) AbbreviatedOID() string {
 	return string(r.oid)[:7]
 }
-func (r *GitCommitResolver) Author() *signatureResolver    { return &r.author }
+func (r *GitCommitResolver) Author() *signatureResolver    { return r.author }
 func (r *GitCommitResolver) Committer() *signatureResolver { return r.committer }
 func (r *GitCommitResolver) Message() string               { return r.message }
 func (r *GitCommitResolver) Subject() string               { return gitCommitSubject(r.message) }
diff --git a/cmd/frontend/graphqlbackend/schema.go b/cmd/frontend/graphqlbackend/schema.go
index 6c0e643915..e931d8b199 100644
--- a/cmd/frontend/graphqlbackend/schema.go
+++ b/cmd/frontend/graphqlbackend/schema.go
@@ -1763,7 +1763,7 @@ type GitCommit implements Node {
     # The abbreviated form of this commit's OID.
     abbreviatedOID: String!
     # This commit's author.
-    author: Signature!
+    author: Signature
     # This commit's committer, if any.
     committer: Signature
     # The full commit message.
diff --git a/cmd/frontend/graphqlbackend/schema.graphql b/cmd/frontend/graphqlbackend/schema.graphql
index 5862e6cf99..2aca5881fc 100755
--- a/cmd/frontend/graphqlbackend/schema.graphql
+++ b/cmd/frontend/graphqlbackend/schema.graphql
@@ -1770,7 +1770,7 @@ type GitCommit implements Node {
     # The abbreviated form of this commit's OID.
     abbreviatedOID: String!
     # This commit's author.
-    author: Signature!
+    author: Signature
     # This commit's committer, if any.
     committer: Signature
     # The full commit message.
diff --git a/cmd/frontend/graphqlbackend/signature.go b/cmd/frontend/graphqlbackend/signature.go
index 34c7d5b50e..7f32355010 100644
--- a/cmd/frontend/graphqlbackend/signature.go
+++ b/cmd/frontend/graphqlbackend/signature.go
@@ -12,7 +12,10 @@ type signatureResolver struct {
 }
 
 func (r signatureResolver) Person() *personResolver {
-	return r.person
+	if r.person != nil {
+		return r.person
+	}
+	return nil
 }
 
 func (r signatureResolver) Date() string {
diff --git a/pkg/vcs/git/blame.go b/pkg/vcs/git/blame.go
index 50abb0d086..c097a36d62 100644
--- a/pkg/vcs/git/blame.go
+++ b/pkg/vcs/git/blame.go
@@ -111,7 +111,7 @@ func blameFileCmd(ctx context.Context, command cmdFunc, path string, opt *BlameO
 			commit := Commit{
 				ID:      api.CommitID(commitID),
 				Message: summary,
-				Author: Signature{
+				Author: &Signature{
 					Name:  author,
 					Email: email,
 					Date:  time.Unix(authorTime, 0).UTC(),
@@ -142,7 +142,7 @@ func blameFileCmd(ctx context.Context, command cmdFunc, path string, opt *BlameO
 			// panicking in case of a (somewhat likely) bug in our
 			// git-blame parser above.
 			hunk.CommitID = commit.ID
-			hunk.Author = commit.Author
+			hunk.Author = *commit.Author
 			hunk.Message = commit.Message
 		}
 
diff --git a/pkg/vcs/git/commits.go b/pkg/vcs/git/commits.go
index b6d85f1881..e43d79b335 100644
--- a/pkg/vcs/git/commits.go
+++ b/pkg/vcs/git/commits.go
@@ -17,7 +17,7 @@ import (
 
 type Commit struct {
 	ID        api.CommitID `json:"ID,omitempty"`
-	Author    Signature    `json:"Author"`
+	Author    *Signature   `json:"Author"`
 	Committer *Signature   `json:"Committer,omitempty"`
 	Message   string       `json:"Message,omitempty"`
 	// Parents are the commit IDs of this commit's parent commits.
@@ -314,7 +314,7 @@ func parseCommitFromLog(data []byte) (commit *Commit, refs []string, rest []byte
 
 	commit = &Commit{
 		ID:        commitID,
-		Author:    Signature{Name: string(parts[2]), Email: string(parts[3]), Date: time.Unix(authorTime, 0).UTC()},
+		Author:    &Signature{Name: string(parts[2]), Email: string(parts[3]), Date: time.Unix(authorTime, 0).UTC()},
 		Committer: &Signature{Name: string(parts[5]), Email: string(parts[6]), Date: time.Unix(committerTime, 0).UTC()},
 		Message:   string(bytes.TrimSuffix(parts[8], []byte{'\n'})),
 		Parents:   parents,
```
</p>
</details>

**Comment by unknwon** [comment]
@mrnugget FYI, I updated your comment with extra lines between code block and `<p>` tags, otherwise the syntax highlighting won't work (maybe a bug in GFM parser).

**Comment by tsenart** [comment]
@mrnugget: Could a third option be that we lazy load the author only when it is requested?

**Comment by keegancsmith** [comment]
We could lazy load, but we would want to do it in a way were we don't lazy load this constantly for one request. I think the easiest option is to make the field optional. We overuse the "required" attribute anyways, which makes it very hard for us to change our graphQL API.

**Comment by tsenart** [comment]
Let's go with option 1. Given that @mrnugget already propose a patch, I think this would be at most 1d of work.
