### ISSUE TITLE
JetBrains: Make the plugin work with 5.0.5

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#54472]
Multiple users have been getting this error:

```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.get(String)" because "data" is null
    at com.sourcegraph.cody.context.embeddings.EmbeddingsSearcher.getRepoIdIfEmbeddingExists(EmbeddingsSearcher.java:189)
    at com.sourcegraph.cody.context.embeddings.EmbeddingsSearcher.getContextMessages(EmbeddingsSearcher.java:41)
    at com.sourcegraph.cody.context.ContextGetter.getContextMessages(ContextGetter.java:30)
    at com.sourcegraph.cody.CodyToolWindowContent.getContextFromEmbeddings(CodyToolWindowContent.java:706)
    at com.sourcegraph.cody.CodyToolWindowContent.lambda$sendMessage$26(CodyToolWindowContent.java:647)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

It happens when the configured Sourcegraph server is 5.0.5 (an older version, current one is 5.1). Looks like it’s giving us a response that we can’t make sense of.

Make it more resilient.

**Comment by vdavid** [comment]
Notify @cconcannon and https://github.com/sourcegraph/accounts/issues/8494 once this is fixed
