### ISSUE TITLE
JetBrains: Recipe triggered from the context menu throws exception

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#54540]
Getting this:

<img width="1606" alt="CleanShot 2023-07-03 at 14 25 27@2x" src="https://github.com/sourcegraph/sourcegraph/assets/2552265/7a829132-7a2c-4c20-9cb6-e11f6e81cb11">

First lines of error message:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'chat' of com/sourcegraph/cody/recipes/RecipeRunner.<init> must not be null
	at com.sourcegraph.cody.recipes.RecipeRunner.$$$reportNull$$$0(RecipeRunner.java)
	at com.sourcegraph.cody.recipes.RecipeRunner.<init>(RecipeRunner.java)
	at com.sourcegraph.cody.recipes.BaseRecipeAction.executeRecipeWithPromptProvider(BaseRecipeAction.java:26)
	at com.sourcegraph.cody.recipes.BaseRecipeAction.actionPerformed(BaseRecipeAction.java:21)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
```

When this happened, my Cody App was not running, and that was the case also when I ran IntelliJ in the first place, so I guess the chat was just never loaded, hence the error.

Suggestion for the solution:
 - IF the chat is currently not displayed (because App is selected and there's no connection to it)
 - THEN disable all context menu items
 - AND display a context menu item labelled "No Cody connection: download Cody App" / "No Cody connection: run Cody App" that do the same thing as the buttons in place of the chat.

Not sure if this state would be possible to update automatically?

Also, the "Cody" and "Sourcegraph" menus have no icons. (see the screenshot above)

**Comment by alturic** [comment]
Getting the same error on a fresh plugin install.

**Comment by szymonprz** [comment]
Hi @alturic We fixed the issue, it should be available in the next release :)
