### ISSUE TITLE
v5.1.x multi-version upgrades failing - no v5.1.x tag in `stitchedMigrationPlan`

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#55048]
- **Sourcegraph version:** v5.1.2
- **Platform information:** 

The upgrade command appears to be broken in `v5.1.2`

Observe the following on a local docker-compose upgrade --
```yaml
  migrator:
    container_name: migrator
    image: 'index.docker.io/sourcegraph/migrator:5.1.2'
    cpus: 0.5
    mem_limit: '500m'
    command: ['upgrade', '--from=v5.0.3', '--to=v5.1.2', '--dry-run', '-ignore-migrator-update']
```

```
λ ~/deploy-sourcegraph-docker/docker-compose/ v5.0.3* docker-compose up migrator
Pulling migrator (index.docker.io/sourcegraph/migrator:5.1.2)...
5.1.2: Pulling from sourcegraph/migrator
Digest: sha256:b9789a7bb219ffcebf37f9e48ca3a8909bde031e064b4663353f73f0a661cd79
Status: Downloaded newer image for sourcegraph/migrator:5.1.2
codeintel-db is up-to-date
pgsql is up-to-date
codeinsights-db is up-to-date
Recreating migrator ... done
Attaching to migrator
migrator                         | ✱ Sourcegraph migrator 5.1.2
migrator                         | ❗️ A newer migrator version is available (v5.1.3), please consider using it instead or pass -ignore-migrator-update.
λ ~/deploy-sourcegraph-docker/docker-compose/ v5.0.3* docker-compose up migrator
codeinsights-db is up-to-date
codeintel-db is up-to-date
pgsql is up-to-date
Recreating migrator ... done
Attaching to migrator
migrator                         | ✱ Sourcegraph migrator 5.1.2
migrator                         | ⚠️ A newer migrator version is available (v5.1.3), please consider using it instead. Continuing...
migrator                         | ℹ️ Connection DSNs used: frontend => postgres://sg:sg@pgsql:5432/sg?sslmode=disable, codeintel => postgres://sg:sg@codeintel-db:5432/sg?sslmode=disable, codeinsights => postgres://postgres:password@codeinsights-db:5432/postgres?sslmode=disable
migrator                         | Attempting connection to postgres://sg:sg@pgsql:5432/sg?sslmode=disable...
migrator                         | ✅ Connection to postgres://sg:sg@pgsql:5432/sg?sslmode=disable succeeded
migrator                         | {"SeverityText":"FATAL","Timestamp":1689658123553975700,"InstrumentationScope":"migrator","Caller":"migrator/main.go:29","Function":"main.main","Body":"unknown tag \"v5.1.0\"","Resource":{"service.name":"migrator","service.version":"5.1.2","service.instance.id":"37452458-bb0c-4801-94ef-f32ef13b4801"},"Attributes":{}}
```

The error is originating from the [filterStitchedMigrationsForTags](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/migration/multiversion/plan.go?L131-151) command. It looks to be the case that the migrator image is struggling to find the `v5.1.x` tag. These images aren't being [generated](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/migration/shared/embed.go?L27-29) correctly it looks like. 

It seems likely this is related to changes in v5.1.0 with the introduction of the wolfi images, but I'm not sure yet.
https://github.com/sourcegraph/sourcegraph/pull/53841 

This doesn't effect standard upgrades and only effects migrator commands relying on a [migrationPlan](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a6dcdc60edede7c30a4e1054c780dcc40d54bfae/-/blob/internal/database/migration/cliutil/upgrade.go?L156-159)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by DaedalusG** [comment]
Running the upgrade command from `v4.5.1` to `v5.0.3` while running the migrator on `v5.1.2` executes alright

```
λ ~/deploy-sourcegraph-docker/docker-compose/ v4.5.1* docker-compose up migrator
codeintel-db is up-to-date
pgsql is up-to-date
codeinsights-db is up-to-date
Recreating migrator ... done
Attaching to migrator
migrator                         | ✱ Sourcegraph migrator 5.1.2
migrator                         | ⚠️ A newer migrator version is available (v5.1.3), please consider using it instead. Continuing...
migrator                         | ℹ️ Connection DSNs used: frontend => postgres://sg:sg@pgsql:5432/sg?sslmode=disable, codeintel => postgres://sg:sg@codeintel-db:5432/sg?sslmode=disable, codeinsights => postgres://postgres:password@codeinsights-db:5432/postgres?sslmode=disable
migrator                         | Attempting connection to postgres://sg:sg@pgsql:5432/sg?sslmode=disable...
migrator                         | ✅ Connection to postgres://sg:sg@pgsql:5432/sg?sslmode=disable succeeded
migrator                         | ℹ️ Connection DSNs used: frontend => postgres://sg:sg@pgsql:5432/sg?sslmode=disable&timezone=UTC, codeintel => postgres://sg:sg@codeintel-db:5432/sg?sslmode=disable, codeinsights => postgres://postgres:password@codeinsights-db:5432/postgres?sslmode=disable
migrator                         | Attempting connection to postgres://sg:sg@pgsql:5432/sg?sslmode=disable&timezone=UTC...
migrator                         | ✅ Connection to postgres://sg:sg@pgsql:5432/sg?sslmode=disable&timezone=UTC succeeded
migrator                         | Attempting connection to postgres://sg:sg@codeintel-db:5432/sg?sslmode=disable...
migrator                         | ✅ Connection to postgres://sg:sg@codeintel-db:5432/sg?sslmode=disable succeeded
migrator                         | Attempting connection to postgres://postgres:password@codeinsights-db:5432/postgres?sslmode=disable...
migrator                         | ✅ Connection to postgres://postgres:password@codeinsights-db:5432/postgres?sslmode=disable succeeded
migrator                         | 👉 Migrating to v4.5 (step 1 of 2)
migrator                         | 👉 Running schema migrations
migrator                         | 👉 Running out of band migrations [19 20]
migrator                         | 👉 Migrating to v5.0 (step 2 of 2)
migrator                         | 👉 Running schema migrations
migrator exited with code 0
```

**Comment by DaedalusG** [comment]
This is also failing on a variation in the v5.1.3 tag

```yaml
  migrator:
    container_name: migrator
    image: 'index.docker.io/sourcegraph/migrator:5.1.3'
    cpus: 0.5
    mem_limit: '500m'
    command: ['upgrade', '--from=v4.5.1', '--to=v5.1.2', '--dry-run', '-ignore-migrator-update']
```

```
λ ~/deploy-sourcegraph-docker/docker-compose/ v4.5.1 docker-compose up migrator
Pulling migrator (index.docker.io/sourcegraph/migrator:5.1.3)...
5.1.3: Pulling from sourcegraph/migrator
991834a5ce8b: Already exists
1e00d2aaaa64: Pull complete
1ede377f836d: Pull complete
Digest: sha256:a184f09b8840c811e8705729726c655f6b4d30f0bed0d471446a0212f11dc93d
Status: Downloaded newer image for sourcegraph/migrator:5.1.3
codeintel-db is up-to-date
pgsql is up-to-date
codeinsights-db is up-to-date
Recreating migrator ... done
Attaching to migrator
migrator                         | ✱ Sourcegraph migrator 5.1.3
migrator                         | ℹ️ Connection DSNs used: frontend => postgres://sg:sg@pgsql:5432/sg?sslmode=disable, codeintel => postgres://sg:sg@codeintel-db:5432/sg?sslmode=disable, codeinsights => postgres://postgres:password@codeinsights-db:5432/postgres?sslmode=disable
migrator                         | Attempting connection to postgres://sg:sg@pgsql:5432/sg?sslmode=disable...
migrator                         | ✅ Connection to "postgres://sg:sg@pgsql:5432/sg?sslmode=disable" succeeded
migrator                         | {"SeverityText":"FATAL","Timestamp":1689696567620752200,"InstrumentationScope":"migrator","Caller":"migrator/main.go:29","Function":"main.main","Body":"unknown tag \"v5.1.0\"","Resource":{"service.name":"migrator","service.version":"5.1.3","service.instance.id":"4b39ecca-18af-4a1e-81fb-c9153c8a7fc2"},"Attributes":{}}
```

**Comment by DaedalusG** [comment]
The maxVersionString for multiversion upgrades should have been updated in the when `release.ts` was run during the releases: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/src/release.ts?L1094-1103

This behavior was refactored recently in: https://github.com/sourcegraph/sourcegraph/pull/48656/files from previous behavior set in https://github.com/sourcegraph/sourcegraph/pull/47636/files

The last known successful update appears to have run in the v5.0.0 release: https://github.com/sourcegraph/sourcegraph/commit/7e5ac7aafe317643166dcea8b617771c695593e6#diff-a5202e48ac77dc6a83646d96d6c80d64370db74dbf863b41ecc643a86b5731ccL11

**Comment by DaedalusG** [comment]
Further evidence that the release tool isn't updating the `maxVersionString` in `v5.1.0`:
- https://github.com/sourcegraph/sourcegraph/commit/d6695ad4fcfc9f2a7a1829bd486512147183a542
- https://github.com/sourcegraph/sourcegraph/commit/09c0e2941e8759113497e4b50d372e770e1059ff

**Comment by DaedalusG** [comment]
Manually updating the `maxVersionString` and building locally I run into a problem with migrations in the [`overlayDefinition`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@bb0a340ce38549ac0d3908eac0168b5e096c3ef9/-/blob/internal/database/migration/stitch/stitch.go?L155) function: 
```
λ ~/sourcegraph/ main* go install ./cmd/migrator
λ ~/sourcegraph/ main* migrator upgrade --from=v5.0.0 --to=v5.1.0
✱ Sourcegraph migrator 0.0.0+dev
ℹ️ Connection DSNs used: frontend => postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable, codeintel => postgres://warrengifford@127.0.0.1:5432, codeinsights => postgres://warrengifford@127.0.0.1:5432
✅ Connection to "postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable" succeeded
{"SeverityText":"FATAL","Timestamp":1690179222855280000,"InstrumentationScope":"migrator","Caller":"migrator/main.go:23","Function":"main.main","Body":"unknown tag \"v5.1.0\"","Resource":{"service.name":"migrator","service.version":"0.0.0+dev","service.instance.id":"1ff5b7b1-914f-44a8-b6cf-a7286791840c"},"Attributes":{}}
λ ~/sourcegraph/ main* cd internal/database/migration/shared && go run ./data/cmd/generator --write-frozen=false
Generating stitched migration files for range [3.20, 5.1]
panic: error: a migration (1648628900) from a previous version was unexpectedly edited in this release - if this change was intentional add this migration to the allowedOverrideMap  v5.1.0:
up.sql:

down.sql:
  (
  	"""
  	... // 26 identical lines

  	-- create the old view
- 	CREATE OR REPLACE VIEW gitserver_localclone_jobs_with_repo_name AS
- 	  SELECT glj.*, r.name AS repo_name
- 	  FROM gitserver_localclone_jobs glj
- 	  JOIN repo r ON r.id = glj.repo_id;
+ 	CREATE OR REPLACE VIEW gitserver_localclone_jobs_with_repo_name AS SELECT glj.id,
+ 	  glj.state,
+ 	  glj.failure_message,
+ 	  glj.started_at,
+ 	  glj.finished_at,
+ 	  glj.process_after,
+ 	  glj.num_resets,
+ 	  glj.num_failures,
+ 	  glj.last_heartbeat_at,
+ 	  glj.execution_logs,
+ 	  glj.worker_hostname,
+ 	  glj.repo_id,
+ 	  glj.source_hostname,
+ 	  glj.dest_hostname,
+ 	  glj.delete_source,
+ 	  glj.queued_at,
+ 	  r.name AS repo_name
+ 	FROM (gitserver_localclone_jobs glj
+ 	JOIN repo r ON ((r.id = glj.repo_id)));
  	"""
  )

goroutine 1 [running]:
main.main()
	/Users/warrengifford/sourcegraph/internal/database/migration/shared/data/cmd/generator/main.go:18 +0x74
exit status 2
```

**Comment by DaedalusG** [comment]
Theres some internal evidence that the `run release release:bake-content` step failed during the v5.1.0 release process -- see internal thread: https://sourcegraph.slack.com/archives/C032Z79NZQC/p1686938945880999

Subsequent patch releases won't rerun this: 
```go
            if (release.version.patch !== 0) {
                console.log('content bake is only required for major / minor versions')
                exit(1)
            }
```
So working hypothesis is that due to a separate failure in the `v5.1.0` release `maxVersionString` wasn't updated, and in subsequent patch releases the [`bake-content`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/src/release.ts?L1076-1155) also isn't run. I haven't found any other basis in the code for why the `combyUpdate` part of the `Edit[]` [wouldn't have run](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:diff+message:%22bake+constants+and+static+content%22+maxVersionString&patternType=standard&sm=1&groupBy=author).

I'll continue to attempt to correct this locally and validate that with the `maxVersionString` update the migrator `upgrade` command will work. Either way we'll need to manually run the steps in the v5.1.5 release since the release tooling will automatically skip this step. 

cc: @coury-clark @unknwon mind checking my thinking here?

**Comment by coury-clark** [comment]
@DaedalusG sounds reasonable. I wonder if for some reason that comby query isn't guaranteed to match. @BolajiOlajide is scheduled to be the patch captain, looping him in here. We ca manually fix this in a PR in this patch, and try to figure out how to make this more stable, or hard fail for next release.

**Comment by DaedalusG** [comment]
Internal fix tracking thread: https://sourcegraph.slack.com/archives/C032Z79NZQC/p1690213127490079

**Comment by DaedalusG** [comment]
Confirmed that the changes in this PR will resolve this issue: https://github.com/sourcegraph/sourcegraph/pull/55237
```
λ ~/sourcegraph/internal/database/migration/shared/ main git checkout bo/update-database-stitch
Updating files: 100% (3648/3648), done.
branch 'bo/update-database-stitch' set up to track 'origin/bo/update-database-stitch'.
Switched to a new branch 'bo/update-database-stitch'
λ ~/sourcegraph/internal/database/migration/shared/ bo/update-database-stitch cd ../../../..
λ ~/sourcegraph/ bo/update-database-stitch go install ./enterprise/cmd/migrator
λ ~/sourcegraph/ bo/update-database-stitch migrator upgrade --from=v5.0.0 --to=v5.1.0
✱ Sourcegraph migrator 0.0.0+dev
ℹ️ Connection DSNs used: frontend => postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable, codeintel => postgres://warrengifford@127.0.0.1:5432, codeinsights => postgres://warrengifford@127.0.0.1:5432
✅ Connection to "postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable" succee...
ℹ️ Connection DSNs used: frontend => postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable&timezone=UTC, codeintel => postgres://warrengifford@127.0.0.1:5432, codeinsights => postgres://warrengifford@127.0.0.1:5432
{"SeverityText":"FATAL","Timestamp":1690221062689610000,"InstrumentationScope":"migrator","Caller":"migrator/main.go:29","Function":"main.main","Body":"version assertion failed: \"0.0\" != \"5.0\". Re-invoke with --skip-version-check to ignore this check","Resource":{"service.name":"migrator","service.version":"0.0.0+dev","service.instance.id":"42e227c9-ff0a-4ea0-9f3a-8278009c7d56"},"Attributes":{}}
λ ~/sourcegraph/ bo/update-database-stitch psql
psql (14.8 (Homebrew))
Type "help" for help.

sourcegraph=# select * from versions;
 service  |  version  |          updated_at           | first_version | auto_upgrade
----------+-----------+-------------------------------+---------------+--------------
 frontend | 0.0.0+dev | 2023-06-29 11:30:35.714985-07 | 0.0.0         | t
(1 row)

sourcegraph=# UPDATE versions SET version='5.0.0';
UPDATE 1
sourcegraph=# \q
λ ~/sourcegraph/ bo/update-database-stitch migrator upgrade --from=v5.0.0 --to=v5.1.0
✱ Sourcegraph migrator 0.0.0+dev
ℹ️ Connection DSNs used: frontend => postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable, codeintel => postgres://warrengifford@127.0.0.1:5432, codeinsights => postgres://warrengifford@127.0.0.1:5432
✅ Connection to "postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable" succee...
ℹ️ Connection DSNs used: frontend => postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable&timezone=UTC, codeintel => postgres://warrengifford@127.0.0.1:5432, codeinsights => postgres://warrengifford@127.0.0.1:5432
✅ Connection to "postgres://sourcegraph:sourcegraph@localhost:5432/sourcegraph?sslmode=disable&timezon...
✅ Connection to "postgres://warrengifford@127.0.0.1:5432" succeeded
✅ Connection to "postgres://warrengifford@127.0.0.1:5432" succeeded
❌ Schema drift detected for frontend
❌ Schema drift detected for codeintel
❌ Schema drift detected for codeinsights
💡 Before continuing with this operation, run the migrator's drift command and follow instructions to repair the schema to the expected current state. See https://docs.sourcegraph.com/admin/how-to/manual_database_migrations#drift for additional instructions.

{"SeverityText":"FATAL","Timestamp":1690221169381137000,"InstrumentationScope":"migrator","Caller":"migrator/main.go:29","Function":"main.main","Body":"database drift detected","Resource":{"service.name":"migrator","service.version":"0.0.0+dev","service.instance.id":"cf95440e-005e-4f83-a958-09319224eefa"},"Attributes":{}}
```

_Note the drift warning here is expected because I've manually set the db version and the db is actually in a release branch_

**Comment by DaedalusG** [comment]
Closing this issue since the issue of migrator images being being built with no image tag is resolved. https://github.com/sourcegraph/sourcegraph/pull/55237/files

A new issue is present in v5.1.5: https://github.com/sourcegraph/sourcegraph/issues/55414
