### ISSUE TITLE
JetBrains: embeddings exception

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#55963]
I'm seeing this exception in my logs

```
.IOException: GraphQL request failed with status code 301
        at com.sourcegraph.cody.context.embeddings.EmbeddingsStatusLoader.getRepoIdIfEmbeddingExists(EmbeddingsStatusLoader.java:60)
        at com.sourcegraph.cody.context.embeddings.EmbeddingsStatusLoader.getRepoId(EmbeddingsStatusLoader.java:32)
        at com.sourcegraph.cody.context.EmbeddingStatusView.lambda$updateEmbeddingStatusView$1(EmbeddingStatusView.java:102)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor
```

**Comment by olafurpg** [comment]
Closing as fixed since this code path has been removed.
