### ISSUE TITLE
JetBrains: Cog icon in "Find with Sourcegraph" window doesn't work

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#56232]
At the top-right of the “Find with Sourcegraph” (⌥S) window, there’s a cog icon to open settings.
Clicking it fails with an uncaught exception.
This is reproducible both with an old intelliJ version and the latest one.

Stack trace:

```
java.lang.AssertionError: Cannot find configurable for specified predicate
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:128)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:107)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:99)
	at com.sourcegraph.config.OpenPluginSettingsAction.actionPerformed(OpenPluginSettingsAction.java:22)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:158)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:464)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
```

**Comment by morgangauth** [comment]
Issue also reported by customer here:
https://discord.com/channels/969688426372825169/1151185313012658206
