### ISSUE TITLE
JetBrains: settings are not loading

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56534]
```
com.intellij.diagnostic.PluginException: Can't instantiate configurable for Sourcegraph Cody + Code Search [Plugin: com.sourcegraph.jetbrains]
        at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:121)
        at com.intellij.openapi.options.newEditor.SettingsTreeView.isBeta(SettingsTreeView.java:796)
        at com.intellij.openapi.options.newEditor.SettingsTreeView$MyRenderer.getTreeCellRendererComponent(SettingsTreeView.java:671)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3223)
        at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNod
```

**Comment by olafurpg** [comment]
Closing as fixed in alpha.7
