### ISSUE TITLE
search: panic in search query code that "should never happen"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#56544]
We got the following panic stacktrace on GCP:

```
goroutine 64049103 [running]: runtime/debug.Stack() GOROOT/src/runtime/debug/stack.go:24 +0x65 github.com/sourcegraph/sourcegraph/internal/trace.loggingRecoverer.func1.1() internal/trace/httptrace.go:264 +0x209 panic({0x3c157e0, 0xc0511db9e0}) GOROOT/src/runtime/panic.go:884 +0x213 github.com/sourcegraph/sourcegraph/internal/search/query.Parameters.Repositories.func1({0xc00ff0c960, 0xf}, 0xa0?, {0x0, {{0x0, 0x0}, {0x0, 0x0}}}) internal/search/query/types.go:622 +0x2f4 github.com/sourcegraph/sourcegraph/internal/search/query.VisitField.func1({0x458f42e?, 0x3c157e0?}, {0xc00ff0c960, 0xf}, 0x0?, {0x0, {{0x0, 0x0}, {0x0, 0x0}}}) internal/search/query/visitor.go:70 +0xa5 github.com/sourcegraph/sourcegraph/internal/search/query.(*Visitor).Visit(0x7fb77c710b38?, {0xd350ba8?, 0xc074e68af0?}) internal/search/query/visitor.go:24 +0x17d github.com/sourcegraph/sourcegraph/internal/search/query.VisitParameter(...) internal/search/query/visitor.go:51 github.com/sourcegraph/sourcegraph/internal/search/query.VisitField({0xc0511db9b0?, 0x1, 0x40ffca?}, {0x458f42e?, 0x18?}, 0x18?) internal/search/query/visitor.go:68 +0xa7 github.com/sourcegraph/sourcegraph/internal/search/query.Parameters.Repositories({0xc05577e370, 0x1, 0xc0706a55e0?}) internal/search/query/types.go:611 +0x1d7 github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.toRepoOptions({{_, _, _}, {_, _}}, _) internal/search/job/jobutil/job.go:724 +0xb0 github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.NewBasicJob(0xc0c393f3b0, {{0xc05577e370, 0x1, 0x1}, {0x0, 0x0}}) internal/search/job/jobutil/job.go:98 +0x225 github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.NewPlanJob.func1({{0xc05577e370, 0x1, 0x1}, {0x0, 0x0}}) internal/search/job/jobutil/job.go:45 +0x4f github.com/sourcegraph/sourcegraph/internal/search/smartsearch.NewSmartSearchJob.func1(0xc012e2b300) internal/search/smartsearch/smart_search_job.go:43 +0x63 github.com/sourcegraph/sourcegraph/internal/search/smartsearch.(*FeelingLuckySearchJob).Run(0xc01212c9f0, {0xd369168?, 0xc01212cb40?}, {{0xd381908, 0xc002547780}, {0xd4006a0, 0xc0027a40d8}, {0xd36fac0, 0xc002648b40}, 0xc00508f080, ...}, ...) internal/search/smartsearch/smart_search_job.go:115 +0x54b github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.(*alertJob).Run(0xc056e79e78, {0xd369168?, 0xc01212cab0?}, {{0xd381908, 0xc002547780}, {0xd4006a0, 0xc0027a40d8}, {0xd36fac0, 0xc002648b40}, 0xc00508f080, ...}, ...) internal/search/job/jobutil/alert.go:41 +0x21f github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.(*LogJob).Run(0xc056e79e90, {0xd369168?, 0xc01212c030?}, {{0xd381908, 0xc002547780}, {0xd4006a0, 0xc0027a40d8}, {0xd36fac0, 0xc002648b40}, 0xc00508f080, ...}, ...) internal/search/job/jobutil/log_job.go:44 +0x184 github.com/sourcegraph/sourcegraph/internal/search/client.(*searchClient).Execute(0xc00160e480, {0xd369168?, 0xc02e23b680?}, {0xd3312a0, 0xc0c393f4d0}, 0xc0c393f3b0) internal/search/client/client.go:167 +0x2a2 github.com/sourcegraph/sourcegraph/cmd/frontend/internal/search.(*streamHandler).serveHTTP.func2({0xd369168, 0xc02e23b680}, 0xc0025477c0, 0xc0027a40d8?, 0xc09f3af309?, 0x2?, 0x0?, 0xc0126f6370?, 0x45?) cmd/frontend/internal/search/search.go:170 +0x1c3 github.com/sourcegraph/sourcegraph/cmd/frontend/internal/search.(*streamHandler).serveHTTP(0xc0025477c0, 0xc012c87f00, {{0xd380e60?, 0xfd976c0?}}, 0x0?) cmd/frontend/internal/search/search.go:171 +0xacf github.com/sourcegraph/sourcegraph/cmd/frontend/internal/search.(*streamHandler).ServeHTTP(0xc012c87d00?, {0xd368670, 0xc0077ca3c0}, 0xc012c87e00) cmd/frontend/internal/search/search.go:77 +0x2c5 github.com/gorilla/mux.(*Router).ServeHTTP(0xc002872c00, {0xd368670, 0xc0077ca3c0}, 0xc012c87c00) external/com_github_gorilla_mux/mux.go:210 +0x1cf github.com/gorilla/mux.(*Router).ServeHTTP(0xc000208300, {0xd368670, 0xc0077ca3c0}, 0xc012c87a00) external/com_github_gorilla_mux/mux.go:210 +0x1cf net/http.(*ServeMux).ServeHTTP(0xd3690f8?, {0xd368670, 0xc0077ca3c0}, 0xc012c87a00) GOROOT/src/net/http/server.go:2500 +0x149 github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/authz.Init.func6.1({0xd368670, 0xc0077ca3c0}, 0xc012c87a00) enterprise/cmd/frontend/internal/authz/init.go:176 +0x449 net/http.HandlerFunc.ServeHTTP(0xd369168?, {0xd368670?, 0xc0077ca3c0?}, 0xfd976c0?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/internal/featureflag.Middleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87900) internal/featureflag/middleware.go:33 +0x336 net/http.HandlerFunc.ServeHTTP(0xd369168?, {0xd368670?, 0xc0077ca3c0?}, 0x7fb77c70e5b8?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/internal/actor.AnonymousUIDMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87800) internal/actor/http.go:177 +0x1ef net/http.HandlerFunc.ServeHTTP(0xd369168?, {0xd368670?, 0xc0077ca3c0?}, 0x0?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/cmd/frontend/auth.glob..func2.1({0xd368670, 0xc0077ca3c0}, 0xc012c87800) cmd/frontend/auth/non_public.go:53 +0xcc net/http.HandlerFunc.ServeHTTP(0xd369168?, {0xd368670?, 0xc0077ca3c0?}, 0x200000003feb340?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect.handleOpenIDConnectAuth({0xd4006a0?, 0xc0027a40d8?}, {0xd368670, 0xc0077ca3c0}, 0xc012c87800, {0xd33bd00, 0xc002772708}, 0x0) enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go:112 +0x4c3 github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/openidconnect.Middleware.func2.1({0xd368670?, 0xc0077ca3c0?}, 0x3000106?) enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go:64 +0x45 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd368670?, 0xc0077ca3c0?}, 0xc00252b7a0?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/sourcegraphoperator.Middleware.func2.1({0xd368670?, 0xc0077ca3c0?}, 0xc012cdb9f8?) enterprise/cmd/frontend/internal/auth/sourcegraphoperator/middleware.go:46 +0xa8 net/http.HandlerFunc.ServeHTTP(0xd369168?, {0xd368670?, 0xc0077ca3c0?}, 0x3032633464353766?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml.authHandler({0xd4006a0?, 0xc0027a40d8?}, {0xd368670, 0xc0077ca3c0}, 0xc012c87800, {0xd33bd00, 0xc00425e0c0}, 0x0) enterprise/cmd/frontend/internal/auth/saml/middleware.go:74 +0x370 github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/saml.Middleware.func2.1({0xd368670?, 0xc0077ca3c0?}, 0xc012cdbb80?) enterprise/cmd/frontend/internal/auth/saml/middleware.go:37 +0x45 net/http.HandlerFunc.ServeHTTP(0x4631a07?, {0xd368670?, 0xc0077ca3c0?}, 0x7fb77c70e5b8?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/httpheader.middleware.func1.1({0xd368670, 0xc0077ca3c0}, 0xc012c87800) enterprise/cmd/frontend/internal/auth/httpheader/middleware.go:48 +0xa69 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd368670?, 0xc0077ca3c0?}, 0xd30cef8?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87800) enterprise/cmd/frontend/internal/auth/oauth/middleware.go:76 +0xa97 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd368670?, 0xc0077ca3c0?}, 0xd30cef8?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87800) enterprise/cmd/frontend/internal/auth/oauth/middleware.go:76 +0xa97 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd368670?, 0xc0077ca3c0?}, 0xd30cef8?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87800) enterprise/cmd/frontend/internal/auth/oauth/middleware.go:76 +0xa97 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd368670?, 0xc0077ca3c0?}, 0xd30cef8?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/oauth.NewMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87800) enterprise/cmd/frontend/internal/auth/oauth/middleware.go:76 +0xa97 net/http.HandlerFunc.ServeHTTP(0xd369168?, {0xd368670?, 0xc0077ca3c0?}, 0xd30cef8?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/githubappauth.newMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87800) enterprise/cmd/frontend/internal/auth/githubappauth/middleware.go:69 +0x2f5 net/http.HandlerFunc.ServeHTTP(0xd369168?, {0xd368670?, 0xc0077ca3c0?}, 0xd31a090?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/auth/confauth.setAllowAnonymousUsageContextKey.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87700) enterprise/cmd/frontend/internal/auth/confauth/middleware.go:17 +0x219 net/http.HandlerFunc.ServeHTTP(0xc012c87700?, {0xd368670?, 0xc0077ca3c0?}, 0x44d4220?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.OpenGraphMetadataMiddleware.func1({0xd368670?, 0xc0077ca3c0}, 0xc0971d4e01?) cmd/frontend/internal/cli/middleware/opengraph.go:120 +0x10f net/http.HandlerFunc.ServeHTTP(0xd381908?, {0xd368670?, 0xc0077ca3c0?}, 0xc0027a40d8?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/internal/session.CookieMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87600) internal/session/session.go:333 +0x254 net/http.HandlerFunc.ServeHTTP(0xc02e23ae40?, {0xd368670?, 0xc0077ca3c0?}, 0x5?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi.AccessTokenAuthMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87600) cmd/frontend/internal/httpapi/auth.go:292 +0x2e2e net/http.HandlerFunc.ServeHTTP(0xd369168?, {0xd368670?, 0xc0077ca3c0?}, 0xfd976c0?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/internal/requestclient.httpMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc012c87500) internal/requestclient/http.go:85 +0x35c net/http.HandlerFunc.ServeHTTP(0xc012c87400?, {0xd368670?, 0xc0077ca3c0?}, 0x4?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/internal/deviceid.Middleware.func1({0xd368670, 0xc0077ca3c0?}, 0xc012c87400) internal/deviceid/middleware.go:29 +0x3f7 net/http.HandlerFunc.ServeHTTP(0xd368670?, {0xd368670?, 0xc0077ca3c0?}, 0x459c36e?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.secureHeadersMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0x0?) cmd/frontend/internal/cli/http.go:241 +0x389 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd368670?, 0xc0077ca3c0?}, 0x0?) GOROOT/src/net/http/server.go:2122 +0x2f net/http.(*ServeMux).ServeHTTP(0x50?, {0xd368670, 0xc0077ca3c0}, 0xc012c87400) GOROOT/src/net/http/server.go:2500 +0x149 github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.Trace.func1({0xd368670?, 0xc0077ca3c0?}, 0xc000c5b830?) cmd/frontend/internal/cli/middleware/trace.go:27 +0x18e net/http.HandlerFunc.ServeHTTP(0xc0971d6688?, {0xd368670?, 0xc0077ca3c0?}, 0xc?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/gorilla/context.ClearHandler.func1({0xd368670?, 0xc0077ca3c0?}, 0x0?) external/com_github_gorilla_context/context.go:141 +0x73 net/http.HandlerFunc.ServeHTTP(0x41cc1e0?, {0xd368670?, 0xc0077ca3c0?}, 0xc?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli.healthCheckMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0x0?) cmd/frontend/internal/cli/http.go:134 +0xb4 net/http.HandlerFunc.ServeHTTP(0xc06414f9c0?, {0xd368670?, 0xc0077ca3c0?}, 0xc02e23af60?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.BlackHole.func1({0xd368670, 0xc0077ca3c0}, 0xc06414f8c0?) cmd/frontend/internal/cli/middleware/blackhole.go:17 +0x9d net/http.HandlerFunc.ServeHTTP(0x42320c0?, {0xd368670?, 0xc0077ca3c0?}, 0x6?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/cmd/frontend/internal/cli/middleware.SourcegraphComGoGetHandler.func1({0xd368670?, 0xc0077ca3c0}, 0xc012c87400) cmd/frontend/internal/cli/middleware/goimportpath.go:48 +0xd7 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd368670?, 0xc0077ca3c0?}, 0xc045e98540?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/internal/auth.ForbidAllRequestsMiddleware.func1({0xd368670, 0xc0077ca3c0}, 0xc045e98540?) internal/auth/forbid_all.go:19 +0x8e net/http.HandlerFunc.ServeHTTP(0x4103a7?, {0xd368670?, 0xc0077ca3c0?}, 0x496601?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/felixge/httpsnoop.CaptureMetrics.func1({0xd368670?, 0xc0077ca3c0?}) external/com_github_felixge_httpsnoop/capture_metrics.go:29 +0x39 github.com/felixge/httpsnoop.(*Metrics).CaptureMetrics(0xc02d17fd70, {0xd366390, 0xc00af53b20}, 0xc0971d6a68) external/com_github_felixge_httpsnoop/capture_metrics.go:84 +0x1ff github.com/felixge/httpsnoop.CaptureMetricsFn(...) external/com_github_felixge_httpsnoop/capture_metrics.go:39 github.com/felixge/httpsnoop.CaptureMetrics({0xd33bd00?, 0xc002772960?}, {0xd366390, 0xc00af53b20}, 0x3ad0c20?) external/com_github_felixge_httpsnoop/capture_metrics.go:28 +0x90 github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1({0xd366390, 0xc00af53b20}, 0xc012c87300) internal/trace/httptrace.go:144 +0x430 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd366390?, 0xc00af53b20?}, 0x0?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/internal/trace.loggingRecoverer.func1({0xd366390?, 0xc00af53b20?}, 0x0?) internal/trace/httptrace.go:269 +0x96 net/http.HandlerFunc.ServeHTTP(0x0?, {0xd366390?, 0xc00af53b20?}, 0x0?) GOROOT/src/net/http/server.go:2122 +0x2f github.com/sourcegraph/sourcegraph/internal/instrumentation.HTTPMiddleware.func1({0xd366390, 0xc00af53b20}, 0xc012c87300) internal/instrumentation/http.go:74 +0x28f net/http.HandlerFunc.ServeHTTP(0x0?, {0xd366390?, 0xc00af53b20?}, 0x0?) GOROOT/src/net/http/server.go:2122 +0x2f go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc0045040c0, {0xd366390?, 0xc00af53b20}, 0xc012c87300) external/io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp/handler.go:126 +0x138 github.com/sourcegraph/sourcegraph/internal/instrumentation.HTTPMiddleware.func2({0xd366390, 0xc00af53b20}, 0xc012c87200) internal/instrumentation/http.go:92 +0x234 net/http.HandlerFunc.ServeHTTP(0xc09f3af2a3?, {0xd366390?, 0xc00af53b20?}, 0x4708ae?) GOROOT/src/net/http/server.go:2122 +0x2f net/http.serverHandler.ServeHTTP({0xc092fc3bc0?}, {0xd366390, 0xc00af53b20}, 0xc012c87200) GOROOT/src/net/http/server.go:2936 +0x316 net/http.(*conn).serve(0xc0750fdef0, {0xd369168, 0xc003e4e9c0}) GOROOT/src/net/http/server.go:1995 +0x612 created by net/http.(*Server).Serve GOROOT/src/net/http/server.go:3089 +0x5ed
```

The panic comes from here:

https://github.com/sourcegraph/sourcegraph/blob/30877e5b143737b008dff222861b92891d3d87f5/internal/search/query/types.go#L622

We should probably investigate why something that's described as "should never happen" (in the comment above) happpened.

**Comment by jtibshirani** [comment]
I looked at the logs for this panic, and it's comes from running a generated smart search query:

```
panic({0x3c157e0, 0xc01b874e40})
	GOROOT/src/runtime/panic.go:884 +0x213
github.com/sourcegraph/sourcegraph/internal/search/query.Parameters.Repositories.func1({0xc058648e50, 0xf}, 0xa0?, {0x0, {{0x0, 0x0}, {0x0, 0x0}}})
	internal/search/query/types.go:622 +0x2f4
github.com/sourcegraph/sourcegraph/internal/search/query.VisitField.func1({0x458f42e?, 0x3c157e0?}, {0xc058648e50, 0xf}, 0x0?, {0x0, {{0x0, 0x0}, {0x0, 0x0}}})
	internal/search/query/visitor.go:70 +0xa5
github.com/sourcegraph/sourcegraph/internal/search/query.(*Visitor).Visit(0x7fbac4487fe8?, {0xd350ba8?, 0xc02e68b770?})
	internal/search/query/visitor.go:24 +0x17d
github.com/sourcegraph/sourcegraph/internal/search/query.VisitParameter(...)
	internal/search/query/visitor.go:51
github.com/sourcegraph/sourcegraph/internal/search/query.VisitField({0xc01b874e10?, 0x1, 0x40ffca?}, {0x458f42e?, 0x18?}, 0x18?)
	internal/search/query/visitor.go:68 +0xa7
github.com/sourcegraph/sourcegraph/internal/search/query.Parameters.Repositories({0xc0267058b0, 0x1, 0xc01bf1a000?})
	internal/search/query/types.go:611 +0x1d7
github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.toRepoOptions({{_, _, _}, {_, _}}, _)
	internal/search/job/jobutil/job.go:724 +0xb0
github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.NewBasicJob(0xc05fd9a000, {{0xc0267058b0, 0x1, 0x1}, {0x0, 0x0}})
	internal/search/job/jobutil/job.go:98 +0x225
github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.NewPlanJob.func1({{0xc0267058b0, 0x1, 0x1}, {0x0, 0x0}})
	internal/search/job/jobutil/job.go:45 +0x4f
github.com/sourcegraph/sourcegraph/internal/search/smartsearch.NewSmartSearchJob.func1(0xc024996b80)
	internal/search/smartsearch/smart_search_job.go:43 +0x63
github.com/sourcegraph/sourcegraph/internal/search/smartsearch.(*FeelingLuckySearchJob).Run(0xc0050b2ba0, {0xd369168?, 0xc0050b2cc0?}, {{0xd381908, 0xc001454400}, {0xd4006a0, 0xc00275ee58}, {0xd36fac0, 0xc00261c880}, 0xc0020696e0, ...}, ...)
	internal/search/smartsearch/smart_search_job.go:115 +0x54b
```

Relevant line: https://github.com/sourcegraph/sourcegraph/blob/0411aeb7b5f9aae722ea243c340cc802dec7bfc3/internal/search/smartsearch/smart_search_job.go#L43

I didn't manage to reproduce the exact error, but found something very similar and opened https://github.com/sourcegraph/sourcegraph/pull/57601 with a fix.
