### ISSUE TITLE
Cody plugin doesn't seem to work at all in JetBrains Client 2023.2.2

### ISSUE THREAD

**Issue by Enalmada** [sourcegraph/sourcegraph#57569]
## Installation information
JetBrains Client 2023.2.2
Build #JBC-232.9921.47, built on September 12, 2023
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
Controller in Remote Development (IU), direct control type: Lux
GC: G1 Young Generation, G1 Old Generation
Memory: 4088M
Cores: 24
Registry:
    editor.input.method.inlay=true
    ide.experimental.ui=true
    rdclient.backend.actionHandlers=false

Non-Bundled Plugins:
    com.intellij.plugins.eclipsekeymap (232.8660.88)
    com.sourcegraph.jetbrains (3.4.1)
    com.intellij.plugins.visualstudiokeymap (232.8660.88)
    com.intellij.plugins.netbeanskeymap (232.8660.88)

## (optional) Error message or idea.log output
Cannot create configurable
   
   com.intellij.diagnostic.PluginException: Cannot create class com.sourcegraph.cody.config.ui.AccountConfigurable (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Sourcegraph Cody + Code Search, id=com.sourcegraph.jetbrains, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\JetBrainsClient232.9921.47\plugins\Sourcegraph, version=3.4.1, package=null, isBundled=false), packagePrefix=null, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1003)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:954)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1022)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:429)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:338)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:39)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:116)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:95)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$showSettingsDialog$3.invoke(ShowSettingsUtilImpl.kt:116)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$showSettingsDialog$3.invoke(ShowSettingsUtilImpl.kt:116)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog$lambda$2(ShowSettingsUtilImpl.kt:116)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$showSettingsDialog$config$1.accept(ShowSettingsUtilImpl.kt:130)
	at com.intellij.openapi.options.ex.ConfigurableVisitor.test(ConfigurableVisitor.java:23)
	at com.intellij.openapi.options.ex.ConfigurableVisitor.test(ConfigurableVisitor.java:18)
	at com.intellij.openapi.options.ex.ConfigurableVisitor.find(ConfigurableVisitor.java:57)
	at com.intellij.openapi.options.ex.ConfigurableVisitor.find(ConfigurableVisitor.java:64)
	at com.intellij.openapi.options.ex.ConfigurableVisitor.find(ConfigurableVisitor.java:46)
	at com.intellij.openapi.options.ex.ConfigurableVisitor.find(ConfigurableVisitor.java:30)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.kt:132)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.kt:116)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.kt:109)
	at com.sourcegraph.config.CodySignedOutNotification$show$1$2.actionPerformed(CodySignedOutNotification.kt:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.fileEditor.impl.IdeUiServiceImpl.performActionDumbAwareWithCallbacks(IdeUiServiceImpl.java:114)
	at com.intellij.notification.Notification.fire(Notification.java:283)
	at com.intellij.notification.impl.NotificationComponent.runAction(NotificationsToolWindow.kt:1177)
	at com.intellij.notification.impl.NotificationComponent.createAction$lambda$1(NotificationsToolWindow.kt:1089)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:175)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:389)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:362)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:976)
	... 78 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/collaboration/ui/SimpleEventListener
	at com.sourcegraph.cody.auth.SingleValueModel.<init>(SingleValueModel.kt:8)
	at com.sourcegraph.cody.auth.ui.AccountsListModelBase.<init>(AccountsListModelBase.kt:20)
	at com.sourcegraph.cody.config.CodyAccountListModel.<init>(CodyAccountListModel.kt:15)
	at com.sourcegraph.cody.config.ui.AccountConfigurable.<init>(AccountConfigurable.kt:30)
	... 84 more
Caused by: java.lang.ClassNotFoundException: com.intellij.collaboration.ui.SimpleEventListener PluginClassLoader(plugin=PluginDescriptor(name=Sourcegraph Cody + Code Search, id=com.sourcegraph.jetbrains, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\JetBrainsClient232.9921.47\plugins\Sourcegraph, version=3.4.1, package=null, isBundled=false), packagePrefix=null, state=active)
	... 88 more

## Steps to reproduce
* Install cody from Jetbrains marketplace: https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search by clicking "Install to Client 2023.2.2" button at the top right.
* click install on the popup that comes up in client.
* Click the "Manage Account" button that comes up in the toast notification.
<img width="406" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/1892132/e56f28d4-3273-4a7d-adff-4d27c236b260">

The Sign in for free with Sourcegraph.com button also does nothing when clicked.

## Expected behavior
expected happy path to work.  New user being able to install plugin, login, try it out.

## Additional Info
This is a windows machine connecting to client on WSL through Jetbrains Gateway.
Some plugins don't support Jetbrains Gateway client.  Perhaps sourcegraph plugin doesn't either?

**Comment by jdorfman** [comment]
Thanks @Enalmada 

Possibly related https://github.com/sourcegraph/sourcegraph/issues/56556
