### ISSUE TITLE
JetBrains: Cody autocomplete limit reached with Cody Pro

### ISSUE THREAD

**Issue by rkkautsar** [sourcegraph/sourcegraph#59407]
## Installation information

```
WebStorm 2023.3.2
Build #WS-233.13135.66, built on December 14, 2023
Licensed to ***

Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.villains.intelij.plugin.newoceantheme (1.2.3)
  com.thvardhan.gradianto (5.5)
  com.nasller.CodeGlancePro (1.7.7)
  com.fernandojimenez.mattecarbon.theme (3.0.0)
  com.jetbrains.darkPurpleTheme (1.3)
  com.jetbrains.space (233.13135.68)
  me.x150.intellij-code-screenshots (1.4.4)
  com.github.catppuccin.jetbrains (3.2.2)
  hu.aradipatrik.nightowlnative (1.1)
  com.markskelton.one-dark-theme (5.9.0)
  com.github.milankinen.ideaicebergtheme (0.7.0)
  AceJump (3.8.18)
  com.sourcegraph.jetbrains (5.2.15221)
  org.jetbrains.plugins.docker.gateway (233.13135.68)
```

## (optional) Error message or idea.log output

```
2024-01-09 09:03:03,573 [2095140] SEVERE - #c.i.o.a.i.ActionUpdater - CodyStatusBarActionGroup#Update@popup (com.sourcegraph.cody.statusbar.CodyStatusBarActionGroup), actionId=CodyStatusBarActions, text='Cody'
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: GraphQLAPIClientConfig is not set
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.common.UpgradeToCodyProNotification$Companion.isCodyProJetbrains(UpgradeToCodyProNotification.kt:91)
	at com.sourcegraph.cody.statusbar.CodyStatusBarActionGroup.deriveWarningAction(CodyStatusBarActionGroup.kt:44)
	at com.sourcegraph.cody.statusbar.CodyStatusBarActionGroup.update(CodyStatusBarActionGroup.kt:26)
	...
2024-01-09 09:03:03,580 [2095147] SEVERE - #c.i.o.a.i.ActionUpdater - WebStorm 2023.3.2  Build #WS-233.13135.66
2024-01-09 09:03:03,581 [2095148] SEVERE - #c.i.o.a.i.ActionUpdater - JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-01-09 09:03:03,581 [2095148] SEVERE - #c.i.o.a.i.ActionUpdater - OS: Mac OS X
2024-01-09 09:03:03,581 [2095148] SEVERE - #c.i.o.a.i.ActionUpdater - Plugin to blame: Sourcegraph Cody + Code Search version: 5.2.15221
2024-01-09 09:03:03,581 [2095148] SEVERE - #c.i.o.a.i.ActionUpdater - Last Action: cody.restartAgent

2024-01-09 09:03:04,114 [2095681]   WARN - #com.sourcegraph.cody.agent.CodyAgent - telemetry: evaluated export mode: 5.2.4+
2024-01-09 09:03:04,910 [2096477]   WARN - #com.sourcegraph.cody.agent.CodyAgent - No Git repository for URI file:///Users/***
2024-01-09 09:03:04,913 [2096480]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ LocalEmbeddingsController: constructor
2024-01-09 09:03:05,222 [2096789]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatManager:constructor: init has local embeddings controller
2024-01-09 09:03:05,222 [2096789]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:constructor: init
2024-01-09 09:03:05,610 [2097177]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:initialized: fireworks/starcoder-hybrid
2024-01-09 09:03:05,930 [2097497]   WARN - #com.sourcegraph.cody.agent.CodyAgent - No Git repository for URI file:///Users/***
2024-01-09 09:03:05,939 [2097506]   INFO - #com.sourcegraph.cody.agent.CodyAgent - connected to Cody agent cody-agent
2024-01-09 09:03:05,939 [2097506]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ Cody:publishConfig: configForWebview 
2024-01-09 09:03:05,939 [2097506]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase 
2024-01-09 09:03:05,939 [2097506]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ logEvent: CodyJetBrainsPlugin:Auth:connected JetBrains {"opts":{"agent":true}}
2024-01-09 09:03:05,939 [2097506]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.auth/connected: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":1},{"key":"chatPredictions","value":0},{"key":"guardrails","value":0}]}}
2024-01-09 09:03:05,947 [2097514]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase ***
2024-01-09 09:03:05,947 [2097514]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ LocalEmbeddingsController: setAccessToken is dotcom
2024-01-09 09:03:05,947 [2097514]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ LocalEmbeddingsController: setAccessToken is dotcom
2024-01-09 09:03:06,257 [2097824]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:initialized: fireworks/starcoder-hybrid
2024-01-09 09:03:06,570 [2098137]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:initialized: fireworks/starcoder-hybrid
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent - autocomplete failed _RateLimitError
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ getInlineCompletions:error:  RateLimitError
    at complete (/snapshot/dist/agent.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /snapshot/dist/agent.js
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at complete (/snapshot/dist/agent.js)
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at async /snapshot/dist/agent.js {
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   userMessage: "You've used all autocompletions for today.",
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   retryAfterDate: 2024-01-13T22:06:47.000Z,
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   retryMessage: 'Usage will reset Sunday at 5:06 AM',
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   feature: 'autocompletions',
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   upgradeIsAvailable: false,
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   limit: 4000,
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   retryAfter: 'Sat, 13 Jan 2024 22:06:47 UTC'
2024-01-09 09:03:13,401 [2104968]   WARN - #com.sourcegraph.cody.agent.CodyAgent - }
2024-01-09 09:03:14,060 [2105627]   WARN - #com.sourcegraph.cody.agent.CodyAgent - autocomplete failed _RateLimitError
```

## Steps to reproduce

May or may not be related, but I have been rate limited just before upgrading to cody pro

- Logged in to jetbrains cody extension with a Cody Pro account
- Trigger autocomplete by typing anything

## Expected behavior

- Unlimited autocomplete

**Comment by rkkautsar** [comment]
will check in discord support channel instead since this is a known issue there
