### ISSUE TITLE
JetBrains: Unusable while behind proxy

### ISSUE THREAD

**Issue by biaji** [sourcegraph/sourcegraph#60602]
I'm using Android Studio with cody plugin installed.

We have to connect internet through a proxy. And the plugin seemed not support http proxy. I can read the error cody complained like:

```
2024-02-19 18:18:09,412 [  54582] SEVERE - #c.i.o.a.i.ApplicationImpl - java.lang.Exception: Failed to start Cody agent
java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.getNow(Unknown Source)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.isConnected(CodyAgentService.kt:143)
	at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.didStatusChanged(CodyAutocompleteStatusService.kt:64)
	at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.onCodyAutocompleteStatusReset$lambda$1(CodyAutocompleteStatusService.kt:43)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: Failed to start Cody agent
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:82)
	... 10 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:69)
	... 10 more
```
and

```
2024-02-19 18:18:51,508 [  96678]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatManager:constructor: init no local embeddings
2024-02-19 18:18:51,509 [  96679]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:constructor: init
2024-02-19 18:18:51,509 [  96679]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CommandsController:disposeWatchers: watchers disposed
2024-02-19 18:18:51,509 [  96679]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CommandsController:fileWatcherInit: watchers created
2024-02-19 18:18:51,509 [  96679]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - window.showErrorMessage: Continue setting up Cody
2024-02-19 18:18:51,509 [  96679]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed  {}
2024-02-19 18:18:51,509 [  96679]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-02-19 18:18:51,513 [  96683]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ symf: downloading symf from https://github.com/sourcegraph/symf/releases/download/v0.0.6/symf-x86_64-macos.zip
2024-02-19 18:18:51,516 [  96686]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ Symf: downloading from URL https://github.com/sourcegraph/symf/releases/download/v0.0.6/symf-x86_64-macos.zip
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent - window.withProgress: uncaught error AxiosError: connect ENETUNREACH 140.82.112.3:443
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at Function.from (/snapshot/dist/agent.js)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at RedirectableRequest.handleRequestError (/snapshot/dist/agent.js)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at RedirectableRequest.emit (node:events:537:28)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at RedirectableRequest.emit (node:domain:482:12)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at ClientRequest.<anonymous> (/snapshot/dist/agent.js)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at ClientRequest.emit (node:events:537:28)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at ClientRequest.emit (node:domain:482:12)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at TLSSocket.socketErrorListener (node:_http_client:465:9)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - window.showErrorMessage: Failed to download symf: Error: connect ENETUNREACH 140.82.112.3:443
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at TLSSocket.emit (node:events:537:28)
2024-02-19 18:18:55,562 [ 100732]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at TLSSocket.emit (node:domain:482:12)
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at emitErrorNT (node:internal/streams/destroy:151:8)
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   port: 443,
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   address: '140.82.112.3',
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   syscall: 'connect',
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   code: 'ENETUNREACH',
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   errno: -51,
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   config: {
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     transitional: {
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       silentJSONParsing: true,
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       forcedJSONParsing: true,
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       clarifyTimeoutError: false
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     },
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     adapter: [ 'xhr', 'http' ],
2024-02-19 18:18:55,563 [ 100733]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     transformRequest: [ [Function: transformRequest] ],
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     transformResponse: [ [Function: transformResponse] ],
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     timeout: 0,
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     xsrfCookieName: 'XSRF-TOKEN',
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     xsrfHeaderName: 'X-XSRF-TOKEN',
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     maxContentLength: -1,
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     maxBodyLength: -1,
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     env: { FormData: [Function], Blob: [class Blob] },
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     validateStatus: [Function: validateStatus],
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     headers: AxiosHeaders {
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       Accept: 'application/json, text/plain, */*',
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       'User-Agent': 'axios/1.3.6',
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       'Accept-Encoding': 'gzip, compress, deflate, br'
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     },
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     url: 'https://github.com/sourcegraph/symf/releases/download/v0.0.6/symf-x86_64-macos.zip',
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     method: 'get',
2024-02-19 18:18:55,564 [ 100734]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     responseType: 'stream',
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     maxRedirects: 10,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     data: undefined
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   },
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   request: <ref *1> Writable {
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _writableState: WritableState {
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       objectMode: false,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       highWaterMark: 16384,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       finalCalled: false,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       needDrain: false,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       ending: false,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       ended: false,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       finished: false,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       destroyed: false,
2024-02-19 18:18:55,565 [ 100735]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       decodeStrings: true,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       defaultEncoding: 'utf8',
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       length: 0,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       writing: false,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       corked: 0,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       sync: true,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       bufferProcessing: false,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       onwrite: [Function: bound onwrite],
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       writecb: null,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       writelen: 0,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       afterWriteTickInfo: null,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       buffered: [],
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       bufferedIndex: 0,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       allBuffers: true,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       allNoop: true,
2024-02-19 18:18:55,566 [ 100736]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       pendingcb: 0,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       constructed: true,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       prefinished: false,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       errorEmitted: false,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       emitClose: true,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       autoDestroy: true,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       errored: null,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       closed: false,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       closeEmitted: false,
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       [Symbol(kOnFinished)]: []
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     },
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _events: [Object: null prototype] {
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       response: [Function: handleResponse],
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       error: [Function: handleRequestError],
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       socket: [Function: handleRequestSocket]
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     },
2024-02-19 18:18:55,567 [ 100737]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _eventsCount: 3,
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _maxListeners: undefined,
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _options: {
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       maxRedirects: 10,
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       maxBodyLength: Infinity,
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       protocol: 'https:',
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       path: '/sourcegraph/symf/releases/download/v0.0.6/symf-x86_64-macos.zip',
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       method: 'GET',
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       headers: [Object: null prototype],
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       agents: [Object],
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       auth: undefined,
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       beforeRedirect: [Function: dispatchBeforeRedirect],
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       beforeRedirects: [Object],
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       hostname: 'github.com',
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       port: '',
2024-02-19 18:18:55,568 [ 100738]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       agent: undefined,
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       nativeProtocols: [Object],
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       pathname: '/sourcegraph/symf/releases/download/v0.0.6/symf-x86_64-macos.zip'
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     },
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _ended: true,
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _ending: true,
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _redirectCount: 0,
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _redirects: [],
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _requestBodyLength: 0,
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _requestBodyBuffers: [],
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _onNativeResponse: [Function (anonymous)],
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _currentRequest: ClientRequest {
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _events: [Object: null prototype],
2024-02-19 18:18:55,569 [ 100739]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _eventsCount: 7,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _maxListeners: undefined,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       outputData: [],
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       outputSize: 0,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       writable: true,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       destroyed: false,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _last: true,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       chunkedEncoding: false,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       shouldKeepAlive: false,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       maxRequestsOnConnectionReached: false,
2024-02-19 18:18:55,570 [ 100740]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _defaultKeepAlive: true,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       useChunkedEncodingByDefault: false,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       sendDate: false,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _removedConnection: false,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _removedContLen: false,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _removedTE: false,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _contentLength: 0,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _hasBody: true,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _trailer: '',
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       finished: true,
2024-02-19 18:18:55,571 [ 100741]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _headerSent: true,
2024-02-19 18:18:55,572 [ 100742]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _closed: false,
2024-02-19 18:18:55,572 [ 100742]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       socket: [TLSSocket],
2024-02-19 18:18:55,572 [ 100742]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _header: 'GET /sourcegraph/symf/releases/download/v0.0.6/symf-x86_64-macos.zip HTTP/1.1\r\n' +
2024-02-19 18:18:55,573 [ 100743]   WARN - #com.sourcegraph.cody.agent.CodyAgent -         'Accept: application/json, text/plain, */*\r\n' +
2024-02-19 18:18:55,573 [ 100743]   WARN - #com.sourcegraph.cody.agent.CodyAgent -         'User-Agent: axios/1.3.6\r\n' +
2024-02-19 18:18:55,574 [ 100744]   WARN - #com.sourcegraph.cody.agent.CodyAgent -         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
2024-02-19 18:18:55,574 [ 100744]   WARN - #com.sourcegraph.cody.agent.CodyAgent -         'Host: github.com\r\n' +
2024-02-19 18:18:55,574 [ 100744]   WARN - #com.sourcegraph.cody.agent.CodyAgent -         'Connection: close\r\n' +
2024-02-19 18:18:55,574 [ 100744]   WARN - #com.sourcegraph.cody.agent.CodyAgent -         '\r\n',
2024-02-19 18:18:55,575 [ 100745]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _keepAliveTimeout: 0,
2024-02-19 18:18:55,577 [ 100747]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _onPendingData: [Function: nop],
2024-02-19 18:18:55,577 [ 100747]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       agent: [Agent],
2024-02-19 18:18:55,578 [ 100748]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       socketPath: undefined,
2024-02-19 18:18:55,578 [ 100748]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       method: 'GET',
2024-02-19 18:18:55,578 [ 100748]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       maxHeaderSize: undefined,
2024-02-19 18:18:55,578 [ 100748]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       insecureHTTPParser: undefined,
2024-02-19 18:18:55,578 [ 100748]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       path: '/sourcegraph/symf/releases/download/v0.0.6/symf-x86_64-macos.zip',
2024-02-19 18:18:55,578 [ 100748]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _ended: false,
2024-02-19 18:18:55,578 [ 100748]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       res: null,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       aborted: false,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       timeoutCb: null,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       upgradeOrConnect: false,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       parser: null,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       maxHeadersCount: null,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       reusedSocket: false,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       host: 'github.com',
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       protocol: 'https:',
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       _redirectable: [Circular *1],
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       [Symbol(kCapture)]: false,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       [Symbol(kNeedDrain)]: false,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       [Symbol(corked)]: 0,
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       [Symbol(kOutHeaders)]: [Object: null prototype],
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       [Symbol(kUniqueHeaders)]: null
2024-02-19 18:18:55,579 [ 100749]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     },
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     _currentUrl: 'https://github.com/sourcegraph/symf/releases/download/v0.0.6/symf-x86_64-macos.zip',
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     [Symbol(kCapture)]: false
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   },
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   cause: Error: connect ENETUNREACH 140.82.112.3:443
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     errno: -51,
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     code: 'ENETUNREACH',
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     syscall: 'connect',
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     address: '140.82.112.3',
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     port: 443
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent -   }
2024-02-19 18:18:55,580 [ 100750]   WARN - #com.sourcegraph.cody.agent.CodyAgent - }
```

While vscode plugin works like charm.

**Comment by taylorsperry** [comment]
Thanks for reporting this issue, @biaji! This issue is on our list https://github.com/sourcegraph/jetbrains/issues/436. I'm going to close this issue in favor of the parent.
