### ISSUE TITLE
syntect_server bug causing failure to display repo contents?

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6280]
Intermittently, I've noticed these errors when trying to navigate to view code files:
![image](https://user-images.githubusercontent.com/1646931/67907055-e1b2b500-fb33-11e9-89d0-4b5069229287.png)

This occurs at the same time as this shows up in the logs:
```
16:37:40         syntect_server | 2019/10/30 23:37:40 request / http://localhost:45857
16:37:42         syntect_server | 2019/10/30 23:37:42 worker 15: dial tcp: i/o timeout
16:37:42               frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: cmd/frontend/backend/repos.go, repo_name: github.com/sourcegraph/sourcegraph, revision: 9ae81827e5ffd1a11113d7175e46dc8eb8d837a9, snippet: "package ba"…, error: http://localhost:9238: unknown error="worker 15: dial tcp: i/o timeout" code="hss_unknown_error"
```

**Comment by beyang** [comment]
@slimsag any idea what might be going on here? This might be related to an issue a customer reported earlier in the day, as well.

**Comment by slimsag** [comment]
Can you provide more logs? Unfortunately the real error was probably further up

**Comment by slimsag** [comment]
One issue I see here is that you are by accident running an older version of syntect_server against your newer dev server code: this explains why we didn't fallback to plaintext mode when this error did happen, and could explain the entire problem (but hard to say without more logs).

I will push up a PR to ensure we're all running the correct syntect_server version, for now you can fix this on your local dev instance via `docker rm -f syntect_server` and relaunching the dev script.

**Comment by beyang** [comment]
Tried removing the Docker image, but still encountered the same error. Here are the logs:
```
17:57:33                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?HighlightedFile from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752: Configured for production.                                                                                                                                                                                                                                   
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752:     => address: 0.0.0.0                                                                                                                                                                                                                                      
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752:     => port: 33125                                                                                                                                                                                                                                           
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752:     => log: critical                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752:     => workers: 24                                                                                                                                                                                                                                           
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752:     => secret key: provided                                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752:     => limits: forms = 32KiB, json* = 10MiB                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752:     => keep-alive: disabled                                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752:     => tls: disabled                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 752: Rocket has launched from http://0.0.0.0:33125                                                                                                                                                                                                                
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753: Configured for production.                                                                                                                                                                                                                                   
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753:     => address: 0.0.0.0                                                                                                                                                                                                                                      
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753:     => port: 40907                                                                                                                                                                                                                                           
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753:     => log: critical                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753:     => workers: 24                                                                                                                                                                                                                                           
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753:     => secret key: provided                                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753:     => limits: forms = 32KiB, json* = 10MiB                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753:     => keep-alive: disabled                                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753:     => tls: disabled                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 753: Rocket has launched from http://0.0.0.0:40907                                                                                                                                                                                                                
17:57:33               frontend | ERROR ui HTTP handler error response, method: GET, request_uri: /searchq=repo:%5Egithub%5C.com/facebook/react%24+componentDidMount%5C%28%5C%29+%7B%5Cn%5Cs*this%5C.props%5C.sourcegraph%5C%28+index:no&patternType=regexp, status_code: 404, error: repo not found: name="searchq=repo:^githu
b\\.com/facebook/react$+componentDidMount\\(\\)+{\\n\\s*this\\.props\\.sourcegraph\\(+index:no&patternType=regexp", error_id: hprSHt, trace: https://app.lightstep.com/sourcegraph-dev/trace?span_guid=6f49a95265ef2905&at_micros=1572569853651298#span-6f49a95265ef2905                                                       
17:57:33         syntect_server | 2019/11/01 00:57:33 request / http://localhost:41661                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 request / http://localhost:38169                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 700: restarting due to timeout                                                                                                                                                                                                                                    
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 701: restarting due to timeout                                                                                                                                                                                                                                    
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 701:                                                                                                                                                                                                                                                              
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 701: signal: killed                                                                                                                                                                                                                                               
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 700:                                                                                                                                                                                                                                                              
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 700: signal: killed                                                                                                                                                                                                                                               
17:57:33                    web | { Error: socket hang up                                                                                                                                                                                                                                                                      
17:57:33                    web |     at createHangUpError (_http_client.js:323:15)                                                                                                                                                                                                                                            
17:57:33                    web |     at Socket.socketCloseListener (_http_client.js:364:25)                                                                                                                                                                                                                                   
17:57:33                    web |     at Socket.emit (events.js:203:15)                                                                                                                                                                                                                                                        
17:57:33                    web |     at Socket.EventEmitter.emit (domain.js:466:23)                                                                                                                                                                                                                                           
17:57:33                    web |     at TCP._handle.close (net.js:606:12) code: 'ECONNRESET' }                                                                                                                                                                                                                                
17:57:33                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?Extensions from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)                                                                                       
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804: started on port 34421                                                                                                                                                                                                                                        
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805: started on port 35875                                                                                                                                                                                                                                        
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804: Configured for production.                                                                                                                                                                                                                                   
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805: Configured for production.                                                                                                                                                                                                                                   
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805:     => address: 0.0.0.0                                                                                                                                                                                                                                      
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805:     => port: 35875                                                                                                                                                                                                                                           
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805:     => log: critical                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805:     => workers: 24                                                                                                                                                                                                                                           
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805:     => secret key: provided                                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805:     => limits: forms = 32KiB, json* = 10MiB                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805:     => keep-alive: disabled                                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805:     => tls: disabled                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804:     => address: 0.0.0.0                                                                                                                                                                                                                                      
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804:     => port: 34421                                                                                                                                                                                                                                           
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804:     => log: critical                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804:     => workers: 24                                                                                                                                                                                                                                           
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804:     => secret key: provided                                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804:     => limits: forms = 32KiB, json* = 10MiB                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804:     => keep-alive: disabled                                                                                                                                                                                                                                  
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804:     => tls: disabled                                                                                                                                                                                                                                         
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 805: Rocket has launched from http://0.0.0.0:35875                                                                                                                                                                                                                
17:57:33         syntect_server | 2019/11/01 00:57:33 worker 804: Rocket has launched from http://0.0.0.0:34421                                                                                                                                                                                                                
17:57:34         syntect_server | 2019/11/01 00:57:34 request / http://localhost:33125                                                                                                                                                                                                                                         
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 752: restarting due to timeout                                                                                                                                                                                                                                    
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 752:                                                                                                                                                                                                                                                              
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 752: signal: killed                                                                                                                                                                                                                                               
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856: started on port 46165                                                                                                                                                                                                                                        
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856: Configured for production.                                                                                                                                                                                                                                   
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856:     => address: 0.0.0.0                                                                                                                                                                                                                                      
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856:     => port: 46165                                                                                                                                                                                                                                           
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856:     => log: critical                                                                                                                                                                                                                                         
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856:     => workers: 24                                                                                                                                                                                                                                           
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856:     => secret key: provided                                                                                                                                                                                                                                  
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856:     => limits: forms = 32KiB, json* = 10MiB                                                                                                                                                                                                                  
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856:     => keep-alive: disabled                                                                                                                                                                                                                                  
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856:     => tls: disabled                                                                                                                                                                                                                                         
17:57:34         syntect_server | 2019/11/01 00:57:34 worker 856: Rocket has launched from http://0.0.0.0:46165                                                                                                                                                                                                                
17:57:37                    web | { Error: socket hang up                                                                                                                                                                                                                                                                      
17:57:37                    web |     at createHangUpError (_http_client.js:323:15)                                                                                                                                                                                                                                            
17:57:37                    web |     at Socket.socketCloseListener (_http_client.js:364:25)                                                                                                                                                                                                                                   
17:57:37                    web |     at Socket.emit (events.js:203:15)                                                                                                                                                                                                                                                        
17:57:37                    web |     at Socket.EventEmitter.emit (domain.js:466:23)                                                                                                                                                                                                                                           
17:57:37                    web |     at TCP._handle.close (net.js:606:12) code: 'ECONNRESET' }                                                                                                                                                                                                                                
17:57:37                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?Extensions from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)                                                                                       
17:57:38           repo-updater | INFO server.external-service-sync, synced: GITHUB                                                                                                                                                                                                                                            
17:57:42           repo-updater | INFO server.external-service-sync, synced: GITHUB                                                                                                                                                                                                                                            
17:57:42               frontend | WARN searchFilesInRepo failed, error: context canceled, repo: github.com/gorilla/mux                                                                                                                                                                                                         
17:57:42               frontend | WARN searchFilesInRepo failed, error: context canceled, repo: github.com/status-im/status-go                                                                                                                                                                                                 
17:57:42               frontend | WARN searchFilesInRepo failed, error: context canceled, repo: github.com/DirectXMan12/k8s-prometheus-adapter                                                                                                                                                                                 
17:57:42               frontend | WARN searchFilesInRepo failed, error: context canceled, repo: github.com/iovisor/kubectl-trace                                                                                                                                                                                               
17:57:42               frontend | WARN searchFilesInRepo failed, error: context canceled, repo: github.com/DataDog/datadog-agent                                                                                                                                                                                               
17:57:42         syntect_server | 2019/11/01 00:57:42 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:42         syntect_server | 2019/11/01 00:57:42 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:42         syntect_server | 2019/11/01 00:57:42 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:42         syntect_server | 2019/11/01 00:57:42 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:43         syntect_server | 2019/11/01 00:57:43 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:43         syntect_server | 2019/11/01 00:57:43 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:43         syntect_server | 2019/11/01 00:57:43 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:43         syntect_server | 2019/11/01 00:57:43 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:43         syntect_server | 2019/11/01 00:57:43 request / http://localhost:34421                                                                                                                                                                                                                                         
17:57:43         syntect_server | 2019/11/01 00:57:43 request / http://localhost:35875                                                                                                                                                                                                                                         
17:57:43         syntect_server | 2019/11/01 00:57:43 request / http://localhost:40907                                                                                                                                                                                                                                         
17:57:43         syntect_server | 2019/11/01 00:57:43 request / http://localhost:34421                                                                                                                                                                                                                                         
17:57:43                    web | { Error: socket hang up                                                                                                                                                                                                                                                                      
17:57:43                    web |     at createHangUpError (_http_client.js:323:15)                                                                                                                                                                                                                                            
17:57:43                    web |     at Socket.socketCloseListener (_http_client.js:364:25)                                                                                                                                                                                                                                   
17:57:43                    web |     at Socket.emit (events.js:203:15)                                                                                                                                                                                                                                                        
17:57:43                    web |     at Socket.EventEmitter.emit (domain.js:466:23)                                                                                                                                                                                                                                           
17:57:43                    web |     at TCP._handle.close (net.js:606:12) code: 'ECONNRESET' }                                                                                                                                                                                                                                
17:57:43                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?HighlightedFile from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)                                                                                  
17:57:43                    web | { Error: socket hang up                                                                                                                                                                                                                                                                      
17:57:43                    web |     at createHangUpError (_http_client.js:323:15)
17:57:43                    web |     at Socket.socketCloseListener (_http_client.js:364:25)
17:57:43                    web |     at Socket.emit (events.js:203:15)
17:57:43                    web |     at Socket.EventEmitter.emit (domain.js:466:23)
17:57:43                    web |     at TCP._handle.close (net.js:606:12) code: 'ECONNRESET' }
17:57:43                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?HighlightedFile from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
17:57:43               frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: ui/package-lock.json, repo_name: github.com/inbucket/inbucket, revision: 0956a136186551660c79d6785abba9ab563bb9ce, snippet: "{\n  \"name\""…, error: making request to http://localhost:9238/: Post http://localhost:9238/: context canceled
17:57:43                    web | { Error: socket hang up
17:57:43                    web |     at createHangUpError (_http_client.js:323:15)
17:57:43                    web |     at Socket.socketCloseListener (_http_client.js:364:25)
17:57:43                    web |     at Socket.emit (events.js:203:15)
17:57:43                    web |     at Socket.EventEmitter.emit (domain.js:466:23)
17:57:43                    web |     at TCP._handle.close (net.js:606:12) code: 'ECONNRESET' }
17:57:43                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?HighlightedFile from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 804: restarting due to timeout
17:57:43               frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: vendor/k8s.io/apimachinery/pkg/util/validation/field/errors_test.go, repo_name: github.com/munnerz/kube-plex, revision: b49dc174846ce91d9cffd6c8d8974945f461cfb5, snippet: "/*\nCopyrig"…, error: making request to http://localhost:9238/: Post http://localhost:9238/: context canceled
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 804: EOF
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 804:
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 804: signal: killed
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 753: restarting due to timeout
17:57:43               frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: static/ueditor/third-party/video-js/video.dev.js, repo_name: github.com/3xxx/engineercms, revision: adc94da23d7304bb4ea86a46d6b6cbc5deda3b1f, snippet: "/**\n * @fi"…, error: making request to http://localhost:9238/: Post http://localhost:9238/: context canceled
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 753:
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 753: signal: killed
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882: started on port 42775
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883: started on port 35525
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883: Configured for production.
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883:     => address: 0.0.0.0
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883:     => port: 35525
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883:     => log: critical
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883:     => workers: 24
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883:     => secret key: provided
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883:     => limits: forms = 32KiB, json* = 10MiB
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883:     => keep-alive: disabled
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883:     => tls: disabled
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882: Configured for production.
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882:     => address: 0.0.0.0
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 883: Rocket has launched from http://0.0.0.0:35525
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882:     => port: 42775
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882:     => log: critical
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882:     => workers: 24
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882:     => secret key: provided
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882:     => limits: forms = 32KiB, json* = 10MiB
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882:     => keep-alive: disabled
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882:     => tls: disabled
17:57:43         syntect_server | 2019/11/01 00:57:43 worker 882: Rocket has launched from http://0.0.0.0:42775
17:57:44         syntect_server | 2019/11/01 00:57:44 request / http://localhost:35875
17:57:46         syntect_server | 2019/11/01 00:57:46 request / http://localhost:35875
17:57:47         syntect_server | 2019/11/01 00:57:47 request / http://localhost:35875
17:57:50         syntect_server | 2019/11/01 00:57:50 request / http://localhost:35875
17:57:51           repo-updater | INFO server.external-service-sync, synced: GITHUB
17:57:53         syntect_server | 2019/11/01 00:57:53 request / http://localhost:35875
17:58:25         syntect_server | 2019/11/01 00:58:25 request / http://localhost:35875
17:58:28         syntect_server | 2019/11/01 00:58:28 request / http://localhost:35875
17:58:49               frontend | ERROR Invalid access token., token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, err: access token not found
17:58:51    zoekt-indexserver-0 | 2019/10/31 17:58:51 restoring shards from trash for github.com/theupdateframework/notary
17:58:51    zoekt-indexserver-0 | 2019/10/31 17:58:51 restoring shards from trash for github.com/codecov/sourcegraph-codecov
17:58:51    zoekt-indexserver-1 | 2019/10/31 17:58:51 restoring shards from trash for github.com/GetStream/Winds
17:58:54                    web | { Error: socket hang up
17:58:54                    web |     at createHangUpError (_http_client.js:323:15)
17:58:54                    web |     at Socket.socketCloseListener (_http_client.js:364:25)
17:58:54                    web |     at Socket.emit (events.js:203:15)
17:58:54                    web |     at Socket.EventEmitter.emit (domain.js:466:23)
17:58:54                    web |     at TCP._handle.close (net.js:606:12) code: 'ECONNRESET' }
17:58:54                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?Extensions from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
17:58:54         syntect_server | 2019/11/01 00:58:54 request / http://localhost:35875
17:58:56         syntect_server | 2019/11/01 00:58:56 worker 805: dial tcp: i/o timeout
```

**Comment by beyang** [comment]
@slimsag seeing this again now:

```
10:34:07                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?Extensions from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
10:34:07         syntect_server | 2019/11/09 18:34:07 request / http://localhost:33481
10:34:09         syntect_server | 2019/11/09 18:34:09 worker 12: dial tcp: i/o timeout
10:34:09               frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: cmd/frontend/backend/repos.go, repo_name: github.com/sourcegraph/sourcegraph, revision: 7d557b9cbcaa5d4f612016bddd2f4ef0a7efed25, snippet: "package ba"…, error: http://localhost:9238: unknown error="worker 12: dial tcp: i/o timeout" code="hss_unknown_error"
10:34:19           repo-updater | INFO server.external-service-sync, synced: GITHUB
10:34:23         syntect_server | 2019/11/09 18:34:23 request / http://localhost:33481
10:34:25         syntect_server | 2019/11/09 18:34:25 worker 12: dial tcp: i/o timeout
10:34:25               frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: cmd/frontend/authz/header.go, repo_name: github.com/sourcegraph/sourcegraph, revision: c543dfd3936019befe94b881ade89e637d1a3dc3, snippet: "package au"…, error: http://localhost:9238: unknown error="worker 12: dial tcp: i/o timeout" code="hss_unknown_error"
10:34:27         syntect_server | 2019/11/09 18:34:27 request / http://localhost:33481
10:34:29         syntect_server | 2019/11/09 18:34:29 worker 12: dial tcp: i/o timeout
10:34:29               frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: cmd/frontend/authz/header.go, repo_name: github.com/sourcegraph/sourcegraph, revision: c543dfd3936019befe94b881ade89e637d1a3dc3, snippet: "package au"…, error: http://localhost:9238: unknown error="worker 12: dial tcp: i/o timeout" code="hss_unknown_error"
```

**Comment by beyang** [comment]
Another failure:
```
11:37:54         syntect_server | 2019/11/09 19:37:54 request / http://localhost:33477
11:37:56         syntect_server | 2019/11/09 19:37:56 worker 14: dial tcp: i/o timeout
11:37:56               frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: browser/config/webpack/base.config.ts, repo_name: github.com/sourcegraph/sourcegraph, revision: c543dfd3936019befe94b881ade89e637d1a3dc3, snippet: "import Min"…, error: http://localhost:9238: unknown error="worker 14: dial tcp: i/o timeout" code="hss_unknown_error"
```

But this one was transient (succeeded on refresh).
