### ISSUE TITLE
sourcegraph/codeintel-java - Fetching servers via workspace/configuration failed: {} java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by wusthuke** [sourcegraph/sourcegraph#630]
```shell
➜  .sourcegraph docker run sourcegraph/codeintel-java
Unable to find image 'sourcegraph/codeintel-java:latest' locally
latest: Pulling from sourcegraph/codeintel-java
1be7f2b886e8: Pull complete
6fbc4a21b806: Pull complete
c71a6f8e1378: Pull complete
4be3072e5a37: Pull complete
06c6d2f59700: Pull complete
40dae1a41f0b: Pull complete
a9940fe8e118: Pull complete
b96fdefb761f: Pull complete
28a0ea06ecc3: Pull complete
d7f35a75f8ff: Pull complete
757be9779c6a: Pull complete
48a83395341e: Pull complete
f4af5aba4d24: Pull complete
fb8dcb3732a4: Pull complete
2bc41d47dd50: Pull complete
Digest: sha256:cbc57bfca3aa76e80486a6a3f7aa1f3b396369eb26a28c9e8010d18fc3cd254a
Status: Downloaded newer image for sourcegraph/codeintel-java:latest
Logging level (com.sourcegraph,root)=(DEBUG,INFO)
Configuration:
	EXECUTE_GRADLE_ORIGINAL_ROOT_PATHS:	[]
	LIGHTSTEP_INCLUDE_SENSITIVE:	false
	LIGHTSTEP_PROJECT:	null
	LIGHTSTEP_TOKEN:	null
	ANDROID_JAR_PATH:	null
	IGNORE_DEPENDENCY_RESOLUTION_CACHE:	false
	LANGSERVER_ROOT:	/root/.java-langserver
	LSP_TIMEOUT:	20
	PRIVATE_ARTIFACT_REPO_ID:	null
	PRIVATE_ARTIFACT_REPO_USERNAME:	null
	PRIVATE_ARTIFACT_REPO_PASSWORD:	null
13:15:33.221 [main] ERROR com.sourcegraph.common.Config - It appears Android support libraries are not installed in LANGSERVER_ROOT. Use the Android Maven SDK deployer script to add them or else Android support libraries will not be resolved.
!!! WARNING: it is highly recommend you pass -Dsun.zip.disableMemoryMapping=true as a JVM argument to avoid fatal crashes. See: https://bugs.openjdk.java.net/browse/JDK-8142508.
13:15:33.251 [main] INFO  c.sourcegraph.langserver.Application - JVM properties (TotalMemory=0.03GB, MaxMemory=0.47GB)
13:15:33.431 [main] INFO  com.sourcegraph.lsp.jsonrpc.Broker - Listening for TCP connections on port 2088
13:19:04.331 [pool-5-thread-1] INFO  com.sourcegraph.utils.Util - ••• [▶] initialize	originalRootUri=git://gitlabtower.test.alipay.net/linkcode/linkc?45b3ffcd9dd9cf49e83b0282f425eaaef4166ef2
13:19:04.459 [pool-5-thread-1] ERROR c.s.langserver.JavaLspHandlerService - Fetching servers via workspace/configuration failed: {}
java.lang.NullPointerException: null
	at com.sourcegraph.langserver.JavaLspHandlerService.getServers(JavaLspHandlerService.java:328)
	at com.sourcegraph.langserver.JavaLspHandlerService.initialize(JavaLspHandlerService.java:84)
	at com.sourcegraph.lsp.Controller.lambda$handleRequest$6(Controller.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
13:19:04.492 [pool-5-thread-1] INFO  com.sourcegraph.utils.Util - ••• [■] initialize	originalRootUri=git://gitlabtower.test.alipay.net/linkcode/linkc?45b3ffcd9dd9cf49e83b0282f425eaaef4166ef2 elapsed=159ms
13:19:04.792 [Thread-0] INFO  c.s.l.l.workspace.Workspaces - A javaconfig.json file was not found.
```

**Comment by wusthuke** [comment]
@sqs Is this a bug or a problem with my use?

**Comment by sqs** [comment]
@beyang ^

**Comment by beyang** [comment]
@wusthuke the error message should be better here, but this indicates that the language server didn't discover build files. It looks for `pom.xml` and `build.gradle` files and if it can't find any, it looks for a `javaconfig.json`, which is a format that lets you specify explicitly the information the language server needs to parse the code.

If your codebase has `pom.xml` or `build.gradle` files, then this is a bug in our handling of those files. If not, would it be possible for you to add a `javaconfig.json` (format described here: https://docs.sourcegraph.com/extensions/language_servers/java#custom-configuration)?

**Comment by wusthuke** [comment]
@beyang  I'm import a new maven project(name: test)，the same error reported. 

the lastest [sourcegraph/codeintel-java](https://hub.docker.com/r/sourcegraph/codeintel-java/tags/) build for 4 months ago。 And i used sourcegraph/server all of the version  ["insiders", "2.13-insiders", "2.12.3"].

![image](https://user-images.githubusercontent.com/9316160/47896372-37fd0180-dea8-11e8-8a42-bb73369b575f.png)

```
05:57:23.127 [pool-5-thread-1] INFO  com.sourcegraph.utils.Util - ▼▼▼ [▶] initialize	originalRootUri=git://gitlabtower.test.alipay.net/huke/test?6045c822dac18cd82849b99fcd51318e63ad3bc3
05:57:23.242 [pool-5-thread-1] ERROR c.s.langserver.JavaLspHandlerService - Fetching servers via workspace/configuration failed: {}
java.lang.NullPointerException: null
	at com.sourcegraph.langserver.JavaLspHandlerService.getServers(JavaLspHandlerService.java:328)
	at com.sourcegraph.langserver.JavaLspHandlerService.initialize(JavaLspHandlerService.java:84)
	at com.sourcegraph.lsp.Controller.lambda$handleRequest$6(Controller.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
05:57:23.285 [pool-5-thread-1] INFO  com.sourcegraph.utils.Util - ▼▼▼ [■] initialize	originalRootUri=git://gitlabtower.test.alipay.net/huke/test?6045c822dac18cd82849b99fcd51318e63ad3bc3 elapsed=156ms
05:57:23.679 [Thread-0] INFO  c.s.l.l.workspace.Workspaces - A javaconfig.json file was not found.
```

**Comment by jaytaylor** [comment]
I'm also running into was looks like the same issue:

```18:30:39.038 [pool-11-thread-1] INFO  com.sourcegraph.utils.Util - ⋃⋃⋃ [▶] initialize	originalRootUri=git://<censored>?ea114ca1b98db7f649c72f85c01d1ff54ffdbb55
18:30:39.043 [pool-11-thread-1] ERROR c.s.langserver.JavaLspHandlerService - Fetching servers via workspace/configuration failed: {}
java.lang.NullPointerException: null
	at com.sourcegraph.langserver.JavaLspHandlerService.getServers(JavaLspHandlerService.java:328)
	at com.sourcegraph.langserver.JavaLspHandlerService.initialize(JavaLspHandlerService.java:84)
	at com.sourcegraph.lsp.Controller.lambda$handleRequest$6(Controller.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Along with errors further down in the logs such as:

```
18:30:41.616 [pool-11-thread-1] ERROR c.s.l.langservice.CompilerService - Workspace not found for file:///some/project/directory/src/main/java/myord/myproject/a_component/something/SomethingServer.java, returning empty analyze result
18:30:41.616 [pool-11-thread-1] INFO  com.sourcegraph.utils.Util -     [■] textDocument/hover	elapsed=1ms
```

**Comment by beyang** [comment]
Thanks for the traces. We've shipped a new version of the Java container: https://hub.docker.com/r/sourcegraph/codeintel-java/tags/.

If you are building Sourcegraph from source, you'll need to run the newest `latest` tag of the `sourcegraph/codeintel-java` container.

If you are running Sourcegraph from the official Docker container ([these instructions](https://docs.sourcegraph.com/)), do the following:
1. Exec into the running Docker container: `docker exec -it $(docker ps | grep sourcegraph/server | awk '{ print $1 }') sh`
1. Kill and remove the old Java container: `docker kill $(docker ps | grep codeintel-java | awk '{ print $1 }') && docker rm $(docker ps | grep codeintel-java | awk '{ print $1 }')`
1. Go to the site config page (`/site-admin/configuration`) on your Sourcegraph instance, change the value of the `langservers` field slightly, hit "Save changes", then change it back, hit "Save changes" again. This is to trigger a refetch of the latest `sourcegraph/codeintel-java` image.
1. Go back to your shell where you are exec'd into the Sourcegraph container. Run `docker ps` to check that the `sourcegraph/codeintel-java` container is present again.
1. Try visiting a Java file now.

FYI, we are vastly simplifying the deployment of language servers in the next 1-2 months, so the overall ease of debugging should be getting much easier soon. In the meantime, thanks for your patience and for using Sourcegraph!

**Comment by sqs** [comment]
We removed the Java lang server that caused this (see https://about.sourcegraph.com/blog/java-php-experimental_language_servers-temporarily-unavailable).

The preferred way to get Java code intelligence is (for now) to use the basic-code-intel extension; see https://about.sourcegraph.com/blog/sourcegraph-3.0-beta-is-now-available#basic-code-intelligence-for-all-languages for info. (On Feb 4, 5 days from when I'm currently writing this, Sourcegraph 3.0 will be released, at which point there will be a **Java** extension that is enabled by default on all instances; see #2035. Then this will just work out of the box.)
