### ISSUE TITLE
a8n: Frontend panics on close campaign

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#7345]
- **Sourcegraph version:** 3.11, master

#### Steps to reproduce:

1. Start a new npm campaign, targetting `sourcegraph/automation-testing`
2. Create the campaign, wait for changeset to be created on codehost
3. Verify it's created on GH.com
4. Click close
5. Choose "close all changesets"
6. Hit close

#### Expected behavior:

The campaign and the changeset are closed on the codehost.

#### Actual behavior:

The frontend service crashes with a panic

```
20:29:15            frontend | panic: runtime error: index out of range [-1]
20:29:15            frontend | goroutine 21475 [running]:
20:29:15            frontend | github.com/sourcegraph/sourcegraph/enterprise/internal/a8n.(*Store).ListChangesets(0xc000360320, 0x2df3460, 0xc0019cd710, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
20:29:15            frontend |  /sourcegraph/enterprise/internal/a8n/store.go:398 +0x16a
20:29:15            frontend | github.com/sourcegraph/sourcegraph/enterprise/internal/a8n.(*Service).CloseCampaign.func2(0xc0014cf950, 0xc0014cf830, 0xc000011288)
20:29:15            frontend |  /sourcegraph/enterprise/internal/a8n/service.go:443 +0x110
20:29:15            frontend | created by github.com/sourcegraph/sourcegraph/enterprise/internal/a8n.(*Service).CloseCampaign
20:29:15            frontend |  /sourcegraph/enterprise/internal/a8n/service.go:440 +0x585
```

**Comment by ryanslade** [comment]
Closed by mistake as the PR hasn't been merged yet
