### ISSUE TITLE
Browser extension silently breaks instead of saying "repo not on your sourcegraph instance"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7599]
I observed a user try to use the browser extension on some private repositories they had not added to their Sourcegraph instance yet. Instead of being told anything, the browser extension just "did not work" and it was not clear at all why.

If we can make requests to the instance but the repository doesn't exist, we should probably indicate that to users?

**Comment by frenata** [comment]
Might be running into this issue -- starting about last week the extension seemed to break on our private repo (when it previously was working), removing and readding the extension provoked this error in the console:

```
inject.bundle.js:1 Uncaught RepoNotFoundError: repo github.com/<my-private-repo> not found
    at Function.<anonymous> (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:8:144)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:2:25985)
    at t.next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:2:3574)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:2:26083)
    at t.next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:2:3574)
    at t.notifyNext (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:59:3333)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:29:16171)
    at t.next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:2:3574)
    at chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:59:54060
```

**Comment by felixfbecker** [comment]
Related #9411
