### ISSUE TITLE
test:regression:core test fails: User settings are saved and applied

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#8470]
- 3.13
- local docker

#### Steps to reproduce:

1. IMAGE=sourcegraph/server:3.13.0-rc.1 ./dev/run-server-image.sh
2. Configure external URL, add license, create sudo token
3. source these  env vars in your shell

```
export SOURCEGRAPH_BASE_URL='http://localhost:7080'
export SOURCEGRAPH_SUDO_TOKEN=xxxxxxx your token from above xxxxx
export SOURCEGRAPH_SUDO_USER=your instance user

you need a bunch more, they are in our 1password/shared/test:regression e2e environment variables:

https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/gm5dfflq6sfclmotneuayfdj5q

```
4. cd web
5.  yarn run test:regression:core 

#### Expected behavior:

test suite passess

#### Actual behavior:

4 tests pass, 1 fails

<img width="1107" alt="Screen Shot 2020-02-17 at 6 07 19 PM" src="https://user-images.githubusercontent.com/534011/74698080-7b6ca380-51b1-11ea-8930-9b44b89cb6b5.png">

![Core_functionality_regression_test_suite_2_2_1_User_settings_are_saved_and_applied](https://user-images.githubusercontent.com/534011/74698295-21201280-51b2-11ea-9720-86b1eeb1719c.png)

**Comment by uwedeportivo** [comment]
i get this one pretty consistently, so maybe it's legit:

```
~/work/src/github.com/sourcegraph/sourcegraph/web(3.13*) » yarn run test:regression:core                                                                                                                                                                                         uwe@maxx
yarn run v1.21.1
$ mocha ./src/regression/core.test.ts


  Core functionality regression test suite
    1) 2.2.1 User settings are saved and applied
📸  Saved screenshot of failure to ../puppeteer/Core_functionality_regression_test_suite_2_2_1_User_settings_are_saved_and_applied.png
    ✓ 2.2.2 User profile page (1381ms)
    ✓ 2.2.3. User emails page (1165ms)
    ✓ 2.2.4 Access tokens work and invalid access tokens return "401 Unauthorized" (2808ms)
    ✓ 2.5 Quicklinks: add a quicklink, test that it appears on the front page and works.
Test resource destroyed: Global setting "quicklinks"
    ✓ 2.4 Explore page


        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
        @@@@ Manual verification steps required!!! @@@@
        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

        Please verify the following screenshots match the corresponding descriptions:

        navbar-toggle-is-bart-simpson.png:	"Navbar toggle avatar is Bart Simpson"

        


  5 passing (25s)
  1 failing

  1) Core functionality regression test suite
       2.2.1 User settings are saved and applied:
     Error: Settings "{ /* These are new settings */}" did not match (old) saved settings "{\n      // add settings here (Ctrl+Space to see hints)\n}\n}"
      at Context.<anonymous> (src/regression/core.test.ts:143:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by uwedeportivo** [comment]
tested failing case by hand and it works, so test needs tweaks

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
fixed
