### ISSUE TITLE
test:regression:search fails

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#8472]
- 3.13
- local docker

#### Steps to reproduce:

1. IMAGE=sourcegraph/server:3.13.0-rc.1 ./dev/run-server-image.sh
2. Configure external URL, add license, create sudo token
3. source these  env vars in your shell

```
export SOURCEGRAPH_BASE_URL='http://localhost:7080'
export SOURCEGRAPH_SUDO_TOKEN=xxxxxxx your token from above xxxxx
export SOURCEGRAPH_SUDO_USER=your instance user

you need a bunch more, they are in our 1password/shared/test:regression e2e environment variables:

https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/gm5dfflq6sfclmotneuayfdj5q

```
4. cd web
5.  yarn run test:regression:search

#### Expected behavior:

test suite passess

#### Actual behavior:

46 tests pass, 4 fail

```
~/work/src/github.com/sourcegraph/sourcegraph/web(3.13*) » yarn run test:regression:search                                                                                                                                                                               uwe@maxx
yarn run v1.21.1
$ mocha ./src/regression/search.test.ts


  Search regression test suite
    Search over a dozen repositories
      ✓ Global text search with 0 results. (2213ms)
      ✓ Global text search with double-quoted string constant ("error type:") with a few results.
      ✓ Global text search excluding repository ("error type:") with a few results.
      ✓ Global text search (error) with many results.
      ✓ Global text search (error count:>1000), expect many results. (4099ms)
      ✓ Global text search (repohasfile:copying), expect many results.
      ✓ Global text search (repohascommitafter:"5 years ago") (1590ms)
      ✓ Global text search for something with more than 1000 results and use "count:1000". (4966ms)
      ✓ Global text search for a regular expression without indexed search: (index:no ^func.*$), expect many results. (2958ms)
      ✓ Global text search for a regular expression with only indexed search: (index:only ^func.*$), expect many results. (1890ms)
      ✓ Search for a repository by name. (1108ms)
      1) Single repository, case-sensitive search.
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Single_repository__case_sensitive_search_.png
      ✓ Global text search, fork:only, few results
      ✓ Global text search, fork:only, 1 result
      ✓ Global text search, fork:no, 0 results
      2) Text search non-master branch, large repository, many results
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Text_search_non_master_branch__large_repository__many_results.png
      ✓ Global text search filtering by language (2350ms)
      ✓ Global search for a filename with 0 results
      3) Global search for a filename with a few results
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Global_search_for_a_filename_with_a_few_results.png
      ✓ Global search for a filename with many results
      ✓ Global symbol search with many results
      ✓ Global symbol search with 0 results
      ✓ Global symbol search ("type:symbol ^newroute count:100") with a few results (1046ms)
      ✓ Indexed multiline search, many results
      ✓ Non-indexed multiline search, many results (1107ms)
      ✓ Indexed multiline search, 0 results
      ✓ Non-indexed multiline search, 0 results
      ✓ Indexed-only structural search, one or more results (2021ms)
      ✓ Commit search, nonzero result (1295ms)
      ✓ Diff search, nonzero result
      ✓ Search timeout
      ✓ Search repo group
      ✓ Search suggestions (3035ms)
      ✓ Search filters (1097ms)
    Interactive search mode
      ✓ Toggling between plain and interactive mode shows correct elements
      ✓ Clicking repo filter button displays selected filters row and repo filter input
      4) Conducting a plain search query correctly returns results
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Interactive_search_mode_Conducting_a_plain_search_query_correctly_returns_results.png
      ✓ Adding a repo filter correctly returns results
      ✓ Adding a term to query input correctly returns results
      ✓ Adding a file filter to query correctly returns results
      ✓ Adding a language filter from the dropdown correctly returns results
      ✓ Filters are properly parsed and displayed in the selected filters row
      ✓ Landing on search results page parses query filters properly
      ✓ Going to search homepage from search results page clears all filters
      ✓ Querying from a repository tree page produces correct query and filter values (1230ms)
      ✓ Toggling from interactive to plain text mode produces correct query
      ✓ Toggling from plain text to interactive mode correctly identifies filters
      ✓ Filter input suggestions
      ✓ Editing text filters
      ✓ Adding and editing finite filters


  46 passing (1m)
  4 failing

  1) Search regression test suite
       Search over a dozen repositories
         Single repository, case-sensitive search.:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:454:12)
      at Frame.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:657:28)
      at Page.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:1144:29)
      at Context.<anonymous> (src/regression/search.test.ts:271:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Search regression test suite
       Search over a dozen repositories
         Text search non-master branch, large repository, many results:
     Error: net::ERR_ABORTED at http://localhost:7080/search?q=repo:%5Egithub%5C.com/facebook/react%24%400.3-stable+"var+ExecutionEnvironment+%3D+require%28%27ExecutionEnvironment%27%29%3B"
      at navigate (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:120:37)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at FrameManager.navigateFrame (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:94:17)
      at Frame.goto (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:406:12)
      at Page.goto (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:675:12)
      at Context.<anonymous> (src/regression/search.test.ts:287:13)
    -- ASYNC --
      at Frame.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:111:15)
      at Page.goto (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:675:49)
      at Page.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:112:23)
      at Context.<anonymous> (src/regression/search.test.ts:287:31)
      at processImmediate (internal/timers.js:439:21)

  3) Search regression test suite
       Search over a dozen repositories
         Global search for a filename with a few results:
     Error: net::ERR_ABORTED at http://localhost:7080/search?q=file:router.go
      at navigate (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:120:37)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at FrameManager.navigateFrame (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:94:17)
      at Frame.goto (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:406:12)
      at Page.goto (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:675:12)
      at Context.<anonymous> (src/regression/search.test.ts:318:13)
    -- ASYNC --
      at Frame.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:111:15)
      at Page.goto (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:675:49)
      at Page.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:112:23)
      at Context.<anonymous> (src/regression/search.test.ts:318:31)
      at processImmediate (internal/timers.js:439:21)

  4) Search regression test suite
       Interactive search mode
         Conducting a plain search query correctly returns results:
     Error: Node is either not visible or not an HTMLElement
      at ElementHandle._clickablePoint (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/JSHandle.js:217:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at ElementHandle.click (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/JSHandle.js:283:20)
      at DOMWorld.click (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:367:5)
      at Context.<anonymous> (src/regression/search.test.ts:613:13)
    -- ASYNC --
      at ElementHandle.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:111:15)
      at DOMWorld.click (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:367:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Context.<anonymous> (src/regression/search.test.ts:613:13)
    -- ASYNC --
      at Frame.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:111:15)
      at Page.click (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:1067:29)
      at Context.<anonymous> (src/regression/search.test.ts:613:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by uwedeportivo** [comment]
similar run

  45 passing (4m)
  5 failing


```
~/work/src/github.com/sourcegraph/sourcegraph/web(3.13*) » yarn run test:regression:search                                                                                                                                                                                       uwe@maxx
yarn run v1.21.1
$ mocha ./src/regression/search.test.ts


  Search regression test suite
    Search over a dozen repositories
      ✓ Global text search with 0 results. (1902ms)
      ✓ Global text search with double-quoted string constant ("error type:") with a few results. (1643ms)
      ✓ Global text search excluding repository ("error type:") with a few results. (1548ms)
      ✓ Global text search (error) with many results.
      ✓ Global text search (error count:>1000), expect many results. (3156ms)
      ✓ Global text search (repohasfile:copying), expect many results. (1263ms)
      ✓ Global text search (repohascommitafter:"5 years ago") (1460ms)
      ✓ Global text search for something with more than 1000 results and use "count:1000". (17477ms)
      1) Global text search for a regular expression without indexed search: (index:no ^func.*$), expect many results.
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Global_text_search_for_a_regular_expression_without_indexed_search___index_no__func______expect_many_results_.png
      ✓ Global text search for a regular expression with only indexed search: (index:only ^func.*$), expect many results.
      ✓ Search for a repository by name.
      2) Single repository, case-sensitive search.
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Single_repository__case_sensitive_search_.png
      ✓ Global text search, fork:only, few results
      ✓ Global text search, fork:only, 1 result
      ✓ Global text search, fork:no, 0 results
      3) Text search non-master branch, large repository, many results
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Text_search_non_master_branch__large_repository__many_results.png
      ✓ Global text search filtering by language (3566ms)
      ✓ Global search for a filename with 0 results
      ✓ Global search for a filename with a few results
      ✓ Global search for a filename with many results
      ✓ Global symbol search with many results
      ✓ Global symbol search with 0 results
      ✓ Global symbol search ("type:symbol ^newroute count:100") with a few results
      ✓ Indexed multiline search, many results
      4) Non-indexed multiline search, many results
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Non_indexed_multiline_search__many_results.png
      ✓ Indexed multiline search, 0 results
      ✓ Non-indexed multiline search, 0 results
      5) Indexed-only structural search, one or more results
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Indexed_only_structural_search__one_or_more_results.png
      ✓ Commit search, nonzero result (1214ms)
      ✓ Diff search, nonzero result
      ✓ Search timeout
      ✓ Search repo group
      ✓ Search suggestions (2760ms)
      ✓ Search filters (1035ms)
    Interactive search mode
      ✓ Toggling between plain and interactive mode shows correct elements
      ✓ Clicking repo filter button displays selected filters row and repo filter input
      ✓ Conducting a plain search query correctly returns results
      ✓ Adding a repo filter correctly returns results (4016ms)
      ✓ Adding a term to query input correctly returns results (1058ms)
      ✓ Adding a file filter to query correctly returns results
      ✓ Adding a language filter from the dropdown correctly returns results
      ✓ Filters are properly parsed and displayed in the selected filters row
      ✓ Landing on search results page parses query filters properly
      ✓ Going to search homepage from search results page clears all filters
      ✓ Querying from a repository tree page produces correct query and filter values (1259ms)
      ✓ Toggling from interactive to plain text mode produces correct query
      ✓ Toggling from plain text to interactive mode correctly identifies filters
      ✓ Filter input suggestions
      ✓ Editing text filters
      ✓ Adding and editing finite filters


  45 passing (4m)
  5 failing

  1) Search regression test suite
       Search over a dozen repositories
         Global text search for a regular expression without indexed search: (index:no ^func.*$), expect many results.:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:454:12)
      at Frame.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:657:28)
      at Page.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:1144:29)
      at Context.<anonymous> (src/regression/search.test.ts:254:31)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Search regression test suite
       Search over a dozen repositories
         Single repository, case-sensitive search.:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:454:12)
      at Frame.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:657:28)
      at Page.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:1144:29)
      at Context.<anonymous> (src/regression/search.test.ts:271:31)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) Search regression test suite
       Search over a dozen repositories
         Text search non-master branch, large repository, many results:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:454:12)
      at Frame.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:657:28)
      at Page.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:1144:29)
      at Context.<anonymous> (src/regression/search.test.ts:291:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) Search regression test suite
       Search over a dozen repositories
         Non-indexed multiline search, many results:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:454:12)
      at Frame.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:657:28)
      at Page.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:1144:29)
      at Context.<anonymous> (src/regression/search.test.ts:364:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  5) Search regression test suite
       Search over a dozen repositories
         Indexed-only structural search, one or more results:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/DOMWorld.js:454:12)
      at Frame.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:657:28)
      at Page.waitForFunction (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:1144:29)
      at Context.<anonymous> (src/regression/search.test.ts:391:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by rvantonder** [comment]
My output reproduces some issues:

```
rvt:web/ (master) $ yarn run test:regression:search                                                                                                                                                                        [15:22:41]
yarn run v1.19.1
$ mocha ./src/regression/search.test.ts


  Search regression test suite
    Search over a dozen repositories
      ✓ Global text search with 0 results.
      ✓ Global text search with double-quoted string constant ("error type:") with a few results.
      ✓ Global text search excluding repository ("error type:") with a few results.
      ✓ Global text search (error) with many results.
      ✓ Global text search (error count:>1000), expect many results. (4137ms)
      1) Global text search (repohasfile:copying), expect many results.
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Global_text_search__repohasfile_copying___expect_many_results_.png
      ✓ Global text search (repohascommitafter:"5 years ago") (1920ms)
      ✓ Global text search for something with more than 1000 results and use "count:1000". (7327ms)
      ✓ Global text search for a regular expression without indexed search: (index:no ^func.*$), expect many results. (2289ms)
      ✓ Global text search for a regular expression with only indexed search: (index:only ^func.*$), expect many results. (3089ms)
      ✓ Search for a repository by name. (1884ms)
      2) Single repository, case-sensitive search.
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Single_repository__case_sensitive_search_.png
      ✓ Global text search, fork:only, few results
      ✓ Global text search, fork:only, 1 result
      ✓ Global text search, fork:no, 0 results
      ✓ Text search non-master branch, large repository, many results (1601ms)
      ✓ Global text search filtering by language (4225ms)
      ✓ Global search for a filename with 0 results
      ✓ Global search for a filename with a few results
      ✓ Global search for a filename with many results
      ✓ Global symbol search with many results
      ✓ Global symbol search with 0 results
      ✓ Global symbol search ("type:symbol ^newroute count:100") with a few results
      ✓ Indexed multiline search, many results
      ✓ Non-indexed multiline search, many results (1257ms)
      ✓ Indexed multiline search, 0 results (1061ms)
      ✓ Non-indexed multiline search, 0 results
      ✓ Indexed-only structural search, one or more results (3849ms)
      ✓ Commit search, nonzero result (2290ms)
      ✓ Diff search, nonzero result (1842ms)
      ✓ Search timeout
      ✓ Search repo group
      ✓ Search suggestions (5545ms)
      ✓ Search filters (2619ms)
    Interactive search mode
      ✓ Toggling between plain and interactive mode shows correct elements (1004ms)
      ✓ Clicking repo filter button displays selected filters row and repo filter input
      3) Conducting a plain search query correctly returns results
📸  Saved screenshot of failure to ../puppeteer/Search_regression_test_suite_Interactive_search_mode_Conducting_a_plain_search_query_correctly_returns_results.png
      ✓ Adding a repo filter correctly returns results (2309ms)
      ✓ Adding a term to query input correctly returns results (3133ms)
      ✓ Adding a file filter to query correctly returns results
      ✓ Adding a language filter from the dropdown correctly returns results
      ✓ Filters are properly parsed and displayed in the selected filters row
      ✓ Landing on search results page parses query filters properly
      ✓ Going to search homepage from search results page clears all filters
      ✓ Querying from a repository tree page produces correct query and filter values (4541ms)
      ✓ Toggling from interactive to plain text mode produces correct query (1375ms)
      ✓ Toggling from plain text to interactive mode correctly identifies filters
      ✓ Filter input suggestions (2019ms)
      ✓ Editing text filters
      ✓ Adding and editing finite filters (1345ms)


  47 passing (2m)
  3 failing

  1) Search regression test suite
       Search over a dozen repositories
         Global text search (repohasfile:copying), expect many results.:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld.waitForFunction (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/DOMWorld.js:454:12)
      at Frame.waitForFunction (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/FrameManager.js:657:28)
      at Page.waitForFunction (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/Page.js:1144:29)
      at Context.<anonymous> (src/regression/search.test.ts:231:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Search regression test suite
       Search over a dozen repositories
         Single repository, case-sensitive search.:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld.waitForFunction (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/DOMWorld.js:454:12)
      at Frame.waitForFunction (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/FrameManager.js:657:28)
      at Page.waitForFunction (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/Page.js:1144:29)
      at Context.<anonymous> (src/regression/search.test.ts:271:31)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) Search regression test suite
       Interactive search mode
         Conducting a plain search query correctly returns results:
     Error: Node is either not visible or not an HTMLElement
      at ElementHandle._clickablePoint (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/JSHandle.js:217:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at ElementHandle.click (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/JSHandle.js:283:20)
      at DOMWorld.click (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/DOMWorld.js:367:5)
      at Context.<anonymous> (src/regression/search.test.ts:613:13)
    -- ASYNC --
      at ElementHandle.<anonymous> (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/helper.js:111:15)
      at DOMWorld.click (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/DOMWorld.js:367:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Context.<anonymous> (src/regression/search.test.ts:613:13)
    -- ASYNC --
      at Frame.<anonymous> (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/helper.js:111:15)
      at Page.click (/Users/rvt/sourcegraph-x/node_modules/puppeteer/lib/Page.js:1067:29)
      at Context.<anonymous> (src/regression/search.test.ts:613:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)



error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There is definitely flakiness. In @uwedeportivo's output, this structural search test fails:

```
  5) Search regression test suite
       Search over a dozen repositories
         Indexed-only structural search, one or more results:
     TimeoutError: waiting for function failed: timeout 30000ms exceeded
```

But not for me. I'm unsure about the others.

**Comment by uwedeportivo** [comment]
i ran 3.12.7 image and 3.12 branch regression tests

```
~/work/src/github.com/sourcegraph/sourcegraph/web(3.12*) » yarn run test:regression:search                                                                                                                                                                                       uwe@maxx
yarn run v1.21.1
$ jest --coverage=false --runInBand ./regression/search.test.ts
 FAIL   web  src/regression/search.test.ts (38.997s)
  Search regression test suite
    Search over a dozen repositories
      ✓ Global text search with 0 results. (260ms)
      ✓ Global text search with double-quoted string constant ("error type:") with a few results. (444ms)
      ✓ Global text search excluding repository ("error type:") with a few results. (457ms)
      ✓ Global text search (error) with many results. (548ms)
      ✓ Global text search (error count:>1000), expect many results. (2993ms)
      ✓ Global text search (repohasfile:copying), expect many results. (395ms)
      ✓ Global text search (repohascommitafter:"5 years ago") (978ms)
      ✓ Global text search for something with more than 1000 results and use "count:1000". (1574ms)
      ✓ Global text search for a regular expression without indexed search: (index:no ^func.*$), expect many results. (1118ms)
      ✓ Global text search for a regular expression with only indexed search: (index:only ^func.*$), expect many results. (1824ms)
      ✓ Search for a repository by name. (434ms)
      ✓ Single repository, case-sensitive search. (449ms)
      ✓ Global text search, fork:only, few results (444ms)
      ✓ Global text search, fork:only, 1 result (432ms)
      ✓ Global text search, fork:no, 0 results (142ms)
      ✓ Text search non-master branch, large repository, many results (1321ms)
      ✓ Global text search filtering by language (2302ms)
      ✓ Global search for a filename with 0 results (154ms)
      ✓ Global search for a filename with a few results (410ms)
      ✓ Global search for a filename with many results (402ms)
      ✓ Global symbol search with many results (442ms)
      ✓ Global symbol search with 0 results (362ms)
      ✓ Global symbol search ("type:symbol ^newroute count:100") with a few results (735ms)
      ✓ Indexed multiline search, many results (415ms)
      ✓ Non-indexed multiline search, many results (805ms)
      ✓ Indexed multiline search, 0 results (519ms)
      ✓ Non-indexed multiline search, 0 results (188ms)
      ✓ Indexed-only structural search, one or more results (509ms)
      ✓ Commit search, nonzero result (1038ms)
      ✓ Diff search, nonzero result (602ms)
      ✓ Search timeout (28ms)
      ✓ Search repo group (121ms)
      ✓ Search suggestions (2240ms)
      ✕ Search filters (10003ms)

  ● Search regression test suite › Search over a dozen repositories › Search filters

    : Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Error:

      510 |         })
      511 | 
    > 512 |         test('Search filters', async () => {
          |         ^
      513 |             const filterToToken = [
      514 |                 ['case:yes', 'case:yes'],
      515 |                 ['lang:go', 'lang:go'],

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.test (src/regression/search.test.ts:512:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 33 passed, 34 total
Snapshots:   0 total
Time:        39.264s
Ran all test suites matching /.\/regression\/search.test.ts/i.

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Saved screenshot of failure to puppeteer/Search_regression_test_suite_Search_over_a_dozen_repositories_Search_filters.png".

      50 |         console.log(`\u001B]1338;url="artifact://${path.relative(repoRootDir, filePath)}";alt="Screenshot"\u0007`)
      51 |     } else {
    > 52 |         console.log(`Saved screenshot of failure to ${path.relative(process.cwd(), filePath)}`)
         |                 ^
      53 |     }
      54 | }
      55 | 

      at CustomConsole.log (../node_modules/@jest/console/build/CustomConsole.js:186:10)
      at log (../shared/src/e2e/screenshotReporter.ts:52:17)

Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
(node:93765) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

Could not find element with text "case:yes", options: {"action":"click","selector":"button","wait":{"timeout":5000}}. Underlying error was: "waiting for function failed: timeout 5000ms exceeded". Debug expressions: Array.from(document.querySelectorAll("button")).filter(e => e.innerText && e.innerText.match(/^case:yes$/))
Array.from(document.querySelectorAll("button")).filter(e => e.innerText && e.innerText.match(/^case:yes\b/))
Array.from(document.querySelectorAll("button")).filter(e => e.innerText && e.innerText.match(/^\s+case:yes$/))
Array.from(document.querySelectorAll("button")).filter(e => e.innerText && e.innerText.match(/^\s+case:yes\b/))
(node:93765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:93765) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by uwedeportivo** [comment]
beyang helped me and we got this one to work, i'm leaving it open until i land the fixes (in the tests) but i'm removing the release-blocker label

**Comment by uwedeportivo** [comment]
fixed by

https://github.com/sourcegraph/sourcegraph/pull/8506

and

https://github.com/sourcegraph/sourcegraph/pull/8504


this one consistently passes for me now
