### ISSUE TITLE
test:regression:auth fails

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#8473]
- 3.13
- local docker

#### Steps to reproduce:

1. IMAGE=sourcegraph/server:3.13.0-rc.1 ./dev/run-server-image.sh
2. Configure external URL, add license, create sudo token
3. source these  env vars in your shell

```
export SOURCEGRAPH_BASE_URL='http://localhost:7080'
export SOURCEGRAPH_SUDO_TOKEN=xxxxxxx your token from above xxxxx
export SOURCEGRAPH_SUDO_USER=your instance user

you need a bunch more, they are in our 1password/shared/test:regression e2e environment variables:

https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/gm5dfflq6sfclmotneuayfdj5q

```
4. cd web
5.  yarn run test:regression:auth

#### Expected behavior:

test suite passess

#### Actual behavior:

0 tests pass, 2 fail

```
~/work/src/github.com/sourcegraph/sourcegraph/web(3.13*) » yarn run test:regression:auth                                                                                                                                                                                 uwe@maxx
yarn run v1.21.1
$ mocha ./src/regression/auth.test.ts


  Auth regression test suite
    1) Sign in via GitHub
    2) "after each" hook for "Sign in via GitHub"


  0 passing (3s)
  2 failing

  1) Auth regression test suite
       Sign in via GitHub:
     Error: Protocol error (Page.navigate): Session closed. Most likely the page has been closed.
      at CDPSession.send (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Connection.js:180:29)
      at navigate (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:118:39)
      at FrameManager.navigateFrame (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:95:7)
      at Frame.goto (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/FrameManager.js:406:37)
      at Frame.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:112:23)
      at Page.goto (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:675:49)
      at Page.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:112:23)
      at Object.login (src/regression/util/helpers.ts:250:23)
      at testLogin (src/regression/auth.test.ts:48:11)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Context.<anonymous> (src/regression/auth.test.ts:117:9)

  2) Auth regression test suite
       "after each" hook for "Sign in via GitHub":
     Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.
      at CDPSession.send (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Connection.js:180:29)
      at Page._screenshotTask (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/Page.js:929:24)
    -- ASYNC --
      at Page.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/node_modules/puppeteer/lib/helper.js:111:15)
      at takeScreenshot (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/shared/src/e2e/screenshotReporter.ts:36:16)
      at Context.<anonymous> (/Users/uwe/work/src/github.com/sourcegraph/sourcegraph/shared/src/e2e/screenshotReporter.ts:13:13)

```

**Comment by uwedeportivo** [comment]
for comparison: 3.12.7

```
~/work/src/github.com/sourcegraph/sourcegraph/web(3.12*) » yarn run test:regression:auth                                                                                                                                                                                         uwe@maxx
yarn run v1.21.1
$ jest --coverage=false --runInBand ./regression/auth.test.ts
  console.log ../shared/src/e2e/screenshotReporter.ts:52
    Saved screenshot of failure to puppeteer/Auth_regression_test_suite_Sign_in_via_GitHub.png

  console.log ../shared/src/e2e/screenshotReporter.ts:52
    Saved screenshot of failure to puppeteer/Auth_regression_test_suite_Sign_in_with_Okta_SAML.png

 FAIL   web  src/regression/auth.test.ts (54.864s)
  Auth regression test suite
    ✕ Sign in via GitHub (20003ms)
    ✓ Sign in with GitLab (5729ms)
    ✕ Sign in with Okta SAML (20003ms)
    ✓ Sign in with Okta OpenID Connect (5489ms)

  ● Auth regression test suite › Sign in via GitHub

    : Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Error:

      112 |     }, 10 * 1000)
      113 | 
    > 114 |     test(
          |     ^
      115 |         'Sign in via GitHub',
      116 |         async () => {
      117 |             await testLogin(driver, gqlClient, resourceManager, {

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.test (src/regression/auth.test.ts:114:5)

  ● Auth regression test suite › Sign in with Okta SAML

    : Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Error:

      149 |     )
      150 | 
    > 151 |     test(
          |     ^
      152 |         'Sign in with Okta SAML',
      153 |         async () => {
      154 |             await testLogin(driver, gqlClient, resourceManager, {

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.test (src/regression/auth.test.ts:151:5)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        54.97s
Ran all test suites matching /.\/regression\/auth.test.ts/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
(node:94016) UnhandledPromiseRejectionWarning: TimeoutError: Caught error after test environment was torn down

waiting for selector "#login_field" failed: timeout 30000ms exceeded
(node:94016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:94016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

**Comment by uwedeportivo** [comment]
both beyang and i got it to work (for me it was decreasing speed and increasing timeout and for beyang it was keeping browser window around). there will be some more work around e2e but there aren't regressions, so removing label

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
auth test needs a little bit of love: github wants "device token sent to email"

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
Closing a `:auth` was removed
