### ISSUE TITLE
Error: No project. (in TypeScript extension)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#993]
When hovering in https://sourcegraph.com/github.com/sourcegraph/lang-typescript/-/blob/server/src/server.ts, I get the following error (repeated many times), and hovers do not show up:

```
TypeScript server Error handling message { jsonrpc: '2.0',  id: 2,  method: 'textDocument/definition',  params:   { textDocument:      { uri:         'https://a8e8b476f6895c2b1641a955d7073ecde5b8bb6e@sourcegraph.com/github.com/sourcegraph/lang-typescript@9b723a92fe6fd7eb517f3a63f5e5b3003c045636/-/raw/server/src/server.ts' },     position: { line: 94, character: 20 } } }  { Error: Request textDocument/definition failed with message: Error processing request. No Project.Error: No Project.    at Object.ThrowNoProject (/srv/node_modules/typescript/lib/tsserver.js:119589:23)    at ProjectService.doEnsureDefaultProjectForFile (/srv/node_modules/typescript/lib/tsserver.js:121932:131)    at ProjectService.ensureDefaultProjectForFile (/srv/node_modules/typescript/lib/tsserver.js:121927:75)    at IOSession.Session.getFileAndProjectWorker (/srv/node_modules/typescript/lib/tsserver.js:124741:87)    at IOSession.Session.getFileAndProject (/srv/node_modules/typescript/lib/tsserver.js:124726:29)    at IOSession.Session.getDefinition (/srv/node_modules/typescript/lib/tsserver.js:124405:31)    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/srv/node_modules/typescript/lib/tsserver.js:123811:61)    at /srv/node_modules/typescript/lib/tsserver.js:125391:88    at IOSession.Session.executeWithRequestId (/srv/node_modules/typescript/lib/tsserver.js:125382:28)    at IOSession.Session.executeCommand (/srv/node_modules/typescript/lib/tsserver.js:125391:33)    at IOSession.Session.onMessage (/srv/node_modules/typescript/lib/tsserver.js:125413:35)    at Interface.<anonymous> (/srv/node_modules/typescript/lib/tsserver.js:126671:27)    at Interface.emit (events.js:182:13)    at Interface._onLine (readline.js:300:10)    at Interface._normalWrite (readline.js:443:12)    at Socket.ondata (readline.js:159:10)    at Socket.emit (events.js:182:13)    at addChunk (_stream_readable.js:283:12)    at readableAddChunk (_stream_readable.js:264:11)    at Socket.Readable.push (_stream_readable.js:219:10)    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)    at handleResponse (/srv/node_modules/vscode-jsonrpc/lib/main.js:436:48)    at processMessageQueue (/srv/node_modules/vscode-jsonrpc/lib/main.js:263:17)    at Immediate.setImmediate (/srv/node_modules/vscode-jsonrpc/lib/main.js:247:13)    at processImmediate (timers.js:632:19) code: -32603, data: undefined }
```

**Comment by felixfbecker** [comment]
I think this is a bug in tsserver, it starts hanging after running `yarn`. Seems to be https://github.com/Microsoft/TypeScript/issues/26651.
This did not happen before I made `yarn` run in the background. We may have to block init on it again, or restart `tsserver` after `yarn` is done (I wonder what is faster).
