### ISSUE TITLE
Code intelligence fails on Sourcegraph.com when other extensions throw errors

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#994]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Navigate to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/...v.2.13.3
2. Hover over deleted lines
3. Notice the hover tooltip never appears or only the loading indicator appears.
4. Tooltips work as expected when hovering over context lines or added lines, .

![hovertooltipserror](https://user-images.githubusercontent.com/4897310/48493359-854e6c80-e7e0-11e8-93fb-be174a91ac15.gif)

#### Extensions

- sourcegraph/codecov
- sourcegraph/code-discussions
- sourcegraph/git-extras
- felixbecker/lang-typescript
- sqs/sourcegraph-python
- langserver/go

#### Expected behavior:

Hover tooltips should be provided.

#### Actual behavior:

I've seen two issues happen:

1) The hover tooltip appears only after the python langserver throws an error. 

There appears to be a bug that prevents tooltip information from rendering while other requests are pending a response. Also note the python langserver is requesting hover info on a Go file.

2) Hover tooltip is never rendered because the python langserver extension throws an error on a Go file and prevents the hover tooltip from showing the hover information. Possible race condition that causes the tooltip to get stuck with the loading indicator after all requests have returned.

Relevant errors:

```
sqs/sourcegraph-python ◀▶ recv response #57: languageFeatures/$provideHover
trace.ts?fbbd:125 Error: {code: -32603, message: "root uri is not ready yet", data: {…}}
trace.ts?fbbd:129 Request: {jsonrpc: "2.0", id: 57, method: "languageFeatures/$provideHover", params: Array(3)}
trace.ts?fbbd:130 Duration: 16 msec

hover.ts?d398:50 ResponseError: root uri is not ready yet
    at handleResponse (webpack-internal:///../shared/src/api/protocol/jsonrpc2/connection.ts:348:36)
    at processMessageQueue (webpack-internal:///../shared/src/api/protocol/jsonrpc2/connection.ts:182:9)
    at setImmediateCompat (webpack-internal:///../shared/src/api/protocol/jsonrpc2/connection.ts:165:7)
    at module.exports (webpack-internal:///../node_modules/core-js/modules/_invoke.js:7:19)
    at queue.(anonymous function) (webpack-internal:///../node_modules/core-js/modules/_task.js:45:7)
    at Number.run (webpack-internal:///../node_modules/core-js/modules/_task.js:27:5)
    at MessagePort.listener (webpack-internal:///../node_modules/core-js/modules/_task.js:32:7)
```

**Comment by nicksnyder** [comment]
@sqs to triage and create action plan

**Comment by sqs** [comment]
Assigning to @chrismwendt because he is taking over the Python lang server
